Repository splunk/public-o11y-docs, pull requests merged in 2023-08, with the labels that each got.

#817 Pulling refs/heads/main into main
  admin/notif-services/slack.rst
Labels: sync, internal

#818 Pulling refs/heads/main into main
  locales/ja_JA/LC_MESSAGES/_includes.mo
  locales/ja_JA/LC_MESSAGES/_includes.po
  locales/ja_JA/LC_MESSAGES/admin.mo
  locales/ja_JA/LC_MESSAGES/admin.po
  locales/ja_JA/LC_MESSAGES/alerts-detectors-notifications.mo
  locales/ja_JA/LC_MESSAGES/alerts-detectors-notifications.po
  locales/ja_JA/LC_MESSAGES/analytics.mo
  locales/ja_JA/LC_MESSAGES/analytics.po
  locales/ja_JA/LC_MESSAGES/apm.mo
  locales/ja_JA/LC_MESSAGES/apm.po
  locales/ja_JA/LC_MESSAGES/data-visualization.mo
  locales/ja_JA/LC_MESSAGES/data-visualization.po
  locales/ja_JA/LC_MESSAGES/gdi.mo
  locales/ja_JA/LC_MESSAGES/gdi.po
  locales/ja_JA/LC_MESSAGES/get-started.mo
  locales/ja_JA/LC_MESSAGES/get-started.po
  locales/ja_JA/LC_MESSAGES/incident-intelligence.mo
  locales/ja_JA/LC_MESSAGES/incident-intelligence.po
  locales/ja_JA/LC_MESSAGES/index.mo
  locales/ja_JA/LC_MESSAGES/index.po
  locales/ja_JA/LC_MESSAGES/infrastructure.mo
  locales/ja_JA/LC_MESSAGES/infrastructure.po
  locales/ja_JA/LC_MESSAGES/logs.mo
  locales/ja_JA/LC_MESSAGES/logs.po
  locales/ja_JA/LC_MESSAGES/metrics-and-metadata.mo
  locales/ja_JA/LC_MESSAGES/metrics-and-metadata.po
  locales/ja_JA/LC_MESSAGES/references.mo
  locales/ja_JA/LC_MESSAGES/references.po
  locales/ja_JA/LC_MESSAGES/rum.mo
  locales/ja_JA/LC_MESSAGES/rum.po
  locales/ja_JA/LC_MESSAGES/splunkplatform.mo
  locales/ja_JA/LC_MESSAGES/splunkplatform.po
  locales/ja_JA/LC_MESSAGES/synthetics.mo
  locales/ja_JA/LC_MESSAGES/synthetics.po
  requirements.txt
Labels: sync, internal

#819 Pulling refs/heads/main into main
  gdi/opentelemetry/uninstall-the-collector.rst
Labels: sync, internal

#820 Pulling refs/heads/main into main
  _images/synthetics/ButtercupGames-naming-convention.png
  admin/subscription-usage/imm-billing.rst
  synthetics/browser-test/browser-test-results.rst
  synthetics/set-up-synthetics/set-up-synthetics.rst
  synthetics/synth-scenarios/synth-landing.rst
  synthetics/test-config/private-locations.rst
  synthetics/test-config/test-config.rst
Labels: sync, internal

#822 Pulling refs/heads/main into main
  gdi/get-data-in/application/nodejs/configuration/advanced-nodejs-otel-configuration.rst
  gdi/get-data-in/application/nodejs/nodejs-otel-requirements.rst
Labels: sync, internal

#804 OTL-2195: Fluentd disabled by default for installer scripts
  gdi/opentelemetry/install-linux.rst
  gdi/opentelemetry/install-windows.rst
Labels: gdi, collector, external, stop-alert

#823 Pulling refs/heads/main into main
  gdi/get-data-in/rum/browser/browser-rum-instrumentations.rst
  gdi/get-data-in/rum/browser/configure-rum-browser-instrumentation.rst
  gdi/get-data-in/rum/browser/get-browser-data-in.rst
  gdi/get-data-in/rum/browser/install-rum-browser.rst
  gdi/get-data-in/rum/browser/troubleshooting.rst
Labels: sync, internal

#824 Pulling refs/heads/main into main
  _static/jsonpull-splunk.js
Labels: sync, internal

#827 Pulling refs/heads/main into main
  Makefile
  _ext/newpage.py
  locales/ja_JA/LC_MESSAGES/_includes.mo
  locales/ja_JA/LC_MESSAGES/admin.mo
  locales/ja_JA/LC_MESSAGES/alerts-detectors-notifications.mo
  locales/ja_JA/LC_MESSAGES/analytics.mo
  locales/ja_JA/LC_MESSAGES/apm.mo
  locales/ja_JA/LC_MESSAGES/data-visualization.mo
  locales/ja_JA/LC_MESSAGES/gdi.mo
  locales/ja_JA/LC_MESSAGES/get-started.mo
  locales/ja_JA/LC_MESSAGES/incident-intelligence.mo
  locales/ja_JA/LC_MESSAGES/index.mo
  locales/ja_JA/LC_MESSAGES/infrastructure.mo
  locales/ja_JA/LC_MESSAGES/logs.mo
  locales/ja_JA/LC_MESSAGES/metrics-and-metadata.mo
  locales/ja_JA/LC_MESSAGES/references.mo
  locales/ja_JA/LC_MESSAGES/rum.mo
  locales/ja_JA/LC_MESSAGES/splunkplatform.mo
  locales/ja_JA/LC_MESSAGES/synthetics.mo
Labels: sync, internal

#826 Update scp.rst
  logs/scp.rst
Labels: external, stop-alert

#828 Pulling refs/heads/main into main
  _includes/troubleshooting-components.rst
  gdi/get-data-in/application/java/performance.rst
Labels: sync, internal

#829 Pulling refs/heads/main into main
  gdi/monitors-databases/microsoft-sql-server.md
  gdi/monitors-hosts/vsphere.md
Labels: sync, internal

#830 Pulling refs/heads/main into main
  gdi/get-data-in/application/otel-dotnet/configuration/advanced-dotnet-configuration.rst
  gdi/get-data-in/application/otel-dotnet/dotnet-requirements.rst
Labels: sync, internal

#831 Pulling refs/heads/main into main
  gdi/get-data-in/serverless/azure/instrument-azure-functions.rst
  gdi/get-data-in/serverless/instrument-serverless-functions.rst
Labels: sync, internal

#825 Update default value for fluentd and supported distros
  gdi/opentelemetry/deployments/deployments-chef.rst
  gdi/opentelemetry/deployments/deployments-linux-ansible.rst
  gdi/opentelemetry/deployments/deployments-linux-puppet.rst
  gdi/opentelemetry/deployments/deployments-salt.rst
  gdi/opentelemetry/deployments/deployments-windows-ansible.rst
  gdi/opentelemetry/deployments/deployments-windows-puppet.rst
Labels: gdi, collector, external

#832 Pulling refs/heads/main into main
  _images/get-started/dashboard-window-transformation.png
  analytics/signalflow.rst
  data-visualization/charts/chart-analytics-reference.rst
Labels: sync, internal

#834 Pulling refs/heads/main into main
  gdi/get-data-in/rum/ios/configure-rum-ios-instrumentation.rst
Labels: sync, internal

#833 Update splunk-collector-troubleshooting.rst
  gdi/opentelemetry/splunk-collector-troubleshooting.rst
Labels: external, stop-alert

#835 Pulling refs/heads/main into main
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/basic-auth-extension.rst
Labels: sync, internal

#836 Pulling refs/heads/main into main
  gdi/get-data-in/application/java/configuration/advanced-java-otel-configuration.rst
Labels: sync, internal

#837 Pulling refs/heads/main into main
  _templates/banner.html
  _templates/layout.html
  _templates/search.html
Labels: sync, internal

#838 Pulling refs/heads/main into main
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
Labels: sync, internal

#841 Update nodejs-otel-requirements.rst
  gdi/get-data-in/application/nodejs/nodejs-otel-requirements.rst
Labels: external, stop-alert

#840 Update common-dotnet-troubleshooting.rst
  gdi/get-data-in/application/dotnet/troubleshooting/common-dotnet-troubleshooting.rst
Labels: external, stop-alert

#839 Update Go supported libraries
  gdi/get-data-in/application/go/go-otel-requirements.rst
Labels: external, stop-alert

#842 Pulling refs/heads/main into main
  gdi/opentelemetry/components/windowsperfcounters-receiver.rst
Labels: sync, internal

#843 Pulling refs/heads/main into main
  infrastructure/monitor/gcp-infra-monitor.rst
Labels: sync, internal

#844 Pulling refs/heads/main into main
  gdi/get-data-in/application/nodejs/instrumentation/manual-instrumentation.rst
Labels: sync, internal

#845 Pulling refs/heads/main into main
  alerts-detectors-notifications/manage-notifications.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-linux.rst
  gdi/opentelemetry/collector-with-the-uf.rst
  gdi/opentelemetry/components/fluentd-receiver.rst
  gdi/opentelemetry/configure-the-collector.rst
  gdi/opentelemetry/deployment-modes.rst
  gdi/opentelemetry/install-linux.rst
  gdi/opentelemetry/opentelemetry.rst
  gdi/opentelemetry/smart-agent-migration-process.rst
  gdi/opentelemetry/smart-agent-migration-to-otel-collector.rst
  gdi/opentelemetry/troubleshoot-logs.rst
  infrastructure/monitor/monitor-services-hosts.rst
  infrastructure/network-explorer/network-explorer-setup.rst
  logs/LOconnect-troubleshoot.rst
Labels: sync, internal

#846 Pulling refs/heads/main into main
  gdi/get-data-in/application/nodejs/instrumentation/manual-instrumentation.rst
  gdi/get-data-in/application/python/instrumentation/python-manual-instrumentation.rst
  gdi/opentelemetry/components/windowsperfcounters-receiver.rst
Labels: sync, internal

#847 Pulling refs/heads/main into main
  _templates/layout.html
Labels: sync, internal

#848 Pulling refs/heads/main into main
  _ext/assetminify.py
  _static/mermaid.js
  _templates/layout.html
  conf.py
  gdi/opentelemetry/configure-the-collector-ootb.rst
  requirements.txt
Labels: sync, internal

#850 Pulling refs/heads/main into main
  infrastructure/network-explorer/network-explorer-setup.rst
Labels: sync, internal

#851 Pulling refs/heads/main into main
  _includes/gdi/default-translation-metrics.rst
  gdi/opentelemetry/components/host-metrics-receiver.rst
  gdi/opentelemetry/components/signalfx-exporter.rst
Labels: sync, internal

#852 Remove spaces that break :guilabel:
  gdi/get-data-in/application/java/instrumentation/java-servers-instructions.rst
Labels: external

#854 Pulling refs/heads/main into main
  _templates/layout.html
Labels: sync, internal

#856 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-apiconfig.rst
  gdi/get-data-in/connect/aws/aws-prereqs.rst
  gdi/get-data-in/connect/azure/azure.rst
  gdi/get-data-in/connect/gcp/gcp.rst
Labels: sync, internal

#857 Pulling refs/heads/main into main
  gdi/get-data-in/application/php/instrumentation/instrument-php-application.rst
  infrastructure/metrics-pipeline/metrics-pipeline-intro.rst
Labels: sync, internal

#858 Pulling refs/heads/main into main
  gdi/monitors-cloudfoundry/cloudfoundry-firehose-nozzle.md
  gdi/monitors-databases/apache-spark.md
  gdi/monitors-databases/cassandra.md
  gdi/monitors-databases/consul.md
  gdi/monitors-databases/etcd.md
  gdi/monitors-databases/hadoop.md
  gdi/monitors-databases/hadoopjmx.md
  gdi/monitors-hosts/amazon-ecs-metadata.md
  gdi/monitors-hosts/apache-httpserver.md
  gdi/monitors-hosts/apache-tomcat.md
  gdi/monitors-hosts/apache-zookeeper.md
  gdi/monitors-hosts/collectd-df.md
  gdi/monitors-hosts/coredns.md
  gdi/monitors-hosts/couchbase.md
  gdi/monitors-hosts/cpu.md
  gdi/monitors-hosts/cpufreq.md
  gdi/monitors-hosts/disk.md
  gdi/monitors-hosts/docker.md
  gdi/monitors-hosts/filesystems.md
  gdi/monitors-hosts/haproxy.md
  gdi/monitors-hosts/host-metadata.md
  gdi/monitors-hosts/host-processes.md
  gdi/monitors-hosts/host-processload.md
  gdi/monitors-languages/asp-dot-net.md
  gdi/monitors-languages/expvar.md
  gdi/monitors-languages/genericjmx.md
  gdi/monitors-languages/microsoft-dotnet.md
  gdi/monitors-messaging/apache-activemq.md
  gdi/monitors-messaging/apache-kafka.md
  gdi/monitors-monitoring/cadvisor.md
  gdi/monitors-monitoring/cgroups.md
  gdi/monitors-network/dns.md
  gdi/monitors-orchestration/mesos-marathon.md
Labels: sync, internal

#859 Update kubernetes-config-advanced.rst
  gdi/opentelemetry/kubernetes-config-advanced.rst
Labels: gdi, collector, external, stop-alert

#860 Pulling refs/heads/main into main
  gdi/opentelemetry/legacy-otel-mappings.md
Labels: sync, internal

#861 Pulling refs/heads/main into main
  gdi/get-data-in/rum/browser/manual-rum-browser-instrumentation.rst
Labels: sync, internal

#862 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-ts-metric-streams.rst
  gdi/monitors-hosts/nginx.md
Labels: sync, internal

#863 Update kubernetes-config-logs.rst
  gdi/opentelemetry/kubernetes-config-logs.rst
Labels: external, stop-alert

#864 Pulling refs/heads/main into main
  gdi/opentelemetry/deployment-modes.rst
Labels: sync, internal

#866 Pulling refs/heads/main into main
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-operator.rst
Labels: sync, internal

#867 Pulling refs/heads/main into main
  synthetics/test-config/private-locations.rst
Labels: sync, internal

#868 Pulling refs/heads/main into main
  gdi/get-data-in/application/php/instrumentation/instrument-php-application.rst
Labels: sync, internal

#869 Pulling refs/heads/main into main
  gdi/opentelemetry/components/host-metrics-receiver.rst
Labels: sync, internal

#870 Pulling refs/heads/main into main
  alerts-detectors-notifications/alerts-detectors-notifications.rst
Labels: sync, internal

#871 Pulling refs/heads/main into main
  synthetics/api-test/set-up-api-test.rst
  synthetics/browser-test/browser-test-metrics.rst
  synthetics/browser-test/set-up-browser-test.rst
  synthetics/intro-synthetics.rst
  synthetics/synth-metrics.rst
Labels: sync, internal

#874 Pulling refs/heads/main into main
  _images/gdi/gdi-prometheus-flink.png
  _includes/application-receiver-table.rst
  gdi/get-data-in/integrations.rst
  gdi/index.rst
  gdi/monitoring.rst
  gdi/monitors-orchestration/kubernetes-controller-manager.md
  gdi/monitors-orchestration/kubernetes-proxy.md
  gdi/monitors-prometheus/prometheus-exporter.md
  gdi/monitors-prometheus/prometheus-generic.rst
  gdi/monitors-prometheus/prometheus-go.md
  gdi/monitors-prometheus/prometheus-nginx-ingress.md
  gdi/monitors-prometheus/prometheus-nginx-vts.md
  gdi/monitors-prometheus/prometheus-node.md
  gdi/monitors-prometheus/prometheus-velero.md
  gdi/prometheus.rst
Labels: sync, internal

#875 Pulling refs/heads/main into main
  apm/span-tags/add-context-trace-span.rst
Labels: sync, internal

#872 Fixed custom_tags indentation in istio.rst
  gdi/get-data-in/application/istio/istio.rst
Labels: external, stop-alert

#876 Pulling refs/heads/main into main
  logs/lo-transition.rst
  logs/log-observer-landing.rst
  logs/pipeline.rst
Labels: sync, internal

#877 Pulling refs/heads/main into main
  gdi/opentelemetry/configure-the-collector.rst
  gdi/opentelemetry/environment-variables.rst
Labels: sync, internal

#878 simplify Node.js custom traces example
  gdi/get-data-in/application/nodejs/instrumentation/manual-instrumentation.rst
Labels: external, stop-alert

#879 Pulling refs/heads/main into main
  _images/apm/apm-detectors/new-detector-create-menu.png
  _images/apm/apm-detectors/new-detector-from-chart.png
  _images/apm/apm-detectors/new-detector-from-tag-spotlight.png
  _images/apm/apm-detectors/new-detector-landing-page.png
  _images/apm/apm-detectors/new-detector-service-map.png
  alerts-detectors-notifications/alert-message-variables-reference.rst
  alerts-detectors-notifications/create-detectors-for-alerts.rst
  apm/apm-alert-visualize/alert-conditions-apm.rst
  apm/apm-alert-visualize/alert-visualize.rst
  apm/apm-alert-visualize/apm-alerts.rst
  apm/apm-alert-visualize/apm-dashboards.rst
  apm/apm-scenarios/custom-metricset.rst
  apm/intro-to-apm.rst
  gdi/get-data-in/application/dotnet/get-started.rst
  gdi/get-data-in/application/dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/application/go/get-started.rst
  gdi/get-data-in/application/go/instrumentation/instrument-go-application.rst
  gdi/get-data-in/application/java/get-started.rst
  gdi/get-data-in/application/java/instrumentation/instrument-java-application.rst
  gdi/get-data-in/application/nodejs/get-started.rst
  gdi/get-data-in/application/nodejs/instrumentation/instrument-nodejs-application.rst
  gdi/get-data-in/application/otel-dotnet/get-started.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/application/php/get-started.rst
  gdi/get-data-in/application/php/instrumentation/instrument-php-application.rst
  gdi/get-data-in/application/python/get-started.rst
  gdi/get-data-in/application/python/instrumentation/instrument-python-application.rst
  gdi/get-data-in/application/python/instrumentation/instrument-python-frameworks.rst
  gdi/get-data-in/application/ruby/get-started.rst
  gdi/get-data-in/application/ruby/instrumentation/instrument-ruby-application.rst
  gdi/get-data-in/application/ruby/instrumentation/ruby-manual-instrumentation.rst
  gdi/get-data-in/compute/compute.rst
  index.rst
  references/glossary.rst
Labels: sync, internal

#880 Pulling refs/heads/main into main
  gdi/opentelemetry/components/filter-processor.rst
  gdi/opentelemetry/components/kubernetes-cluster-receiver.rst
  gdi/opentelemetry/deployment-modes.rst
Labels: sync, internal

#881 Pulling refs/heads/main into main
  gdi/get-data-in/application/dotnet/configuration/dotnet-metrics-attributes.rst
  metrics-and-metadata/metrics.rst
Labels: sync, internal

#882 Pulling refs/heads/main into main
  incident-intelligence/manage-notifications/example-notifications.rst
Labels: sync, internal

#883 Pulling refs/heads/main into main
  requirements.txt
  synthetics/test-config/private-locations.rst
Labels: sync, internal

#884 Improve OTel mapping conflicts explanation
  gdi/opentelemetry/legacy-otel-mappings.md
  gdi/opentelemetry/smart-agent-migration-process.rst
Labels: collector, external, stop-alert

#888 Pulling refs/heads/main into main
  index.rst
  rum/sample-app.rst
  rum/set-up-rum.rst
  synthetics/browser-test/set-up-browser-test.rst
Labels: sync, internal

#889 Pulling refs/heads/main into main
  gdi/get-data-in/application/python/instrumentation/python-manual-instrumentation.rst
Labels: sync, internal
