Repository splunk/public-o11y-docs, pull requests merged in 2023-03, with the labels that each got.

#364 Pulling refs/heads/main into main
  incident-intelligence/create-configure-incident-policies.rst
  incident-intelligence/create-manage-on-call-schedules/example-schedule-scenarios.rst
Labels: sync

#375 Pulling refs/heads/main into main
  _images/rum/TBT-range.png
  _images/rum/rum-synth-filter.png
  _images/rum/tag-spotlight-rum-snyth.png
  _images/rum/web-vital-example.png
  rum/error-aggregates.rst
  synthetics/api-test/api-test-results.rst
  synthetics/browser-test/browser-test-results.rst
  synthetics/set-up-synthetics/set-up-synthetics.rst
  synthetics/test-config/rum-synth.rst
  synthetics/test-config/test-config.rst
  synthetics/uptime-test/uptime-test-results.rst
Labels: sync

#380 Pulling refs/heads/main into main
  _includes/gdi/zero-config-preview-header.rst
  gdi/elasticsearch-query/elasticsearch-query.md
  gdi/etcd/etcd.md
  gdi/expvar/expvar.md
  gdi/kubernetes-apiserver/kubernetes-apiserver.md
  gdi/kubernetes-proxy/kubernetes-proxy.md
  gdi/kubernetes-scheduler/kubernetes-scheduler.md
  gdi/logstash-tcp/logstash.md
  gdi/logstash/logstash.md
  gdi/mongodb/mongodb.md
  gdi/opentelemetry/components/prometheus-receiver.rst
  gdi/opentelemetry/install-windows-manual.rst
  gdi/opentelemetry/install-windows.rst
  gdi/opentelemetry/kubernetes-config.rst
  gdi/opentelemetry/otel-commands.rst
  gdi/opentelemetry/otel-upgrade.rst
  gdi/opentelemetry/resources.rst
  gdi/opentelemetry/security.rst
  gdi/opentelemetry/smart-agent-migration-monitors.rst
  gdi/pivotalcloudfoundry/pivotal-cloud-foundry.rst
  gdi/prometheus-exporter/prometheus-exporter.md
  gdi/vsphere/vsphere.md
Labels: sync

#381 Pulling refs/heads/main into main
  gdi/get-data-in/application/application.rst
  gdi/get-data-in/application/dotnet/configuration/advanced-dotnet-configuration.rst
  gdi/get-data-in/application/dotnet/get-started.rst
  gdi/get-data-in/application/dotnet/troubleshooting/common-dotnet-troubleshooting.rst
  gdi/get-data-in/application/java/configuration/advanced-java-otel-configuration.rst
  gdi/get-data-in/application/otel-dotnet/configuration/advanced-dotnet-configuration.rst
  gdi/get-data-in/application/otel-dotnet/configuration/dotnet-metrics-attributes.rst
  gdi/get-data-in/application/otel-dotnet/dotnet-requirements.rst
  gdi/get-data-in/application/otel-dotnet/get-started.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/manual-dotnet-instrumentation.rst
  gdi/get-data-in/application/otel-dotnet/troubleshooting/common-dotnet-troubleshooting.rst
  gdi/get-data-in/application/otel-dotnet/troubleshooting/migrate-signalfx-dotnet-to-dotnet-otel.rst
  gdi/get-data-in/application/python/configuration/advanced-python-otel-configuration.rst
  gdi/opentelemetry/legacy-otel-mappings.md
Labels: sync

#383 Pulling refs/heads/main into main
  gdi/get-data-in/rum/browser/rum-browser-data-model.rst
  metrics-and-metadata/metrics-finder-metadata-catalog.rst
  rum/error-aggregates.rst
  rum/rum-alerts.rst
  rum/rum-dashboards/rum-built-in-dashboards.rst
  rum/rum-terminology-concepts.rst
  rum/rum-use-case-library/rum-mobile-usecase.rst
  rum/rum-use-case-library/spa-custom-event.rst
  synthetics/api-test/api-test-metrics.rst
  synthetics/api-test/api-test-results.rst
  synthetics/browser-test/browser-test-metrics.rst
  synthetics/browser-test/browser-test-results.rst
  synthetics/browser-test/set-up-browser-test.rst
  synthetics/browser-test/set-up-transactional-browser-test.rst
  synthetics/intro-synthetics.rst
  synthetics/set-up-synthetics/set-up-synthetics.rst
  synthetics/synth-metrics.rst
  synthetics/synth-use-cases/browser-test-use-case.rst
  synthetics/test-config/built-in-variables.rst
  synthetics/test-config/global-variables.rst
  synthetics/test-config/private-locations.rst
  synthetics/test-config/rum-synth.rst
  synthetics/test-config/synth-alerts.rst
  synthetics/test-config/test-config.rst
  synthetics/uptime-test/uptime-test-results.rst
Labels: sync

#385 Pulling refs/heads/main into main
  CONTRIBUTING.md
  README.md
  apm/apm-spans-traces/apm-errors.rst
  apm/apm-spans-traces/service-map.rst
  apm/apm-spans-traces/traces-spans.rst
  apm/db-query-perf/db-perf-use-case.rst
  apm/db-query-perf/enable-db-perf.rst
  apm/key-concepts.rst
  apm/profiling/using-the-flamegraph.rst
  apm/set-up-apm/apm-gdi.rst
  apm/set-up-apm/apm-orientation.rst
  apm/set-up-apm/environments.rst
  apm/set-up-apm/sensitive-data-controls.rst
  apm/span-tags/cmms.rst
  apm/span-tags/index-span-tags.rst
  data-visualization/charts/chart-builder.rst
  data-visualization/charts/create-charts.rst
  data-visualization/dashboards/built-in-dashboards.rst
  data-visualization/dashboards/view-charts-dashboards.rst
  gdi/get-data-in/application/dotnet/troubleshooting/common-dotnet-troubleshooting.rst
  gdi/get-data-in/application/java/configuration/java-otel-metrics-attributes.rst
  gdi/get-data-in/application/java/troubleshooting/common-java-troubleshooting.rst
  gdi/get-data-in/application/nodejs/troubleshooting/migrate-signalfx-nodejs-agent-to-otel.rst
  gdi/get-data-in/application/otel-dotnet/configuration/dotnet-metrics-attributes.rst
  gdi/get-data-in/connect/aws/aws-apiconfig.rst
  gdi/get-data-in/connect/aws/aws-logs.rst
  gdi/get-data-in/connect/aws/aws-terraformconfig.rst
  gdi/get-data-in/connect/azure/azure-logs-ingestion.rst
  gdi/get-data-in/rum/android/configure-rum-android-instrumentation.rst
  gdi/haproxy/haproxy.md
  gdi/http/http.md
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/deployments/deployments-linux-ansible.rst
  gdi/opentelemetry/install-linux.rst
  gdi/opentelemetry/install-windows-manual.rst
  gdi/opentelemetry/install-windows.rst
  gdi/opentelemetry/kubernetes-config.rst
  gdi/opentelemetry/opentelemetry.rst
  gdi/opentelemetry/otel-commands.rst
  gdi/opentelemetry/troubleshoot-k8s.rst
  gdi/traefik/traefik.md
  get-started/use-cases/use-case.rst
Labels: sync

#386 Pulling refs/heads/main into main
  gdi/get-data-in/application/go/configuration/advanced-go-otel-configuration.rst
  gdi/get-data-in/application/go/configuration/go-otel-metrics.rst
  gdi/get-data-in/application/go/get-started.rst
  gdi/get-data-in/application/go/instrumentation/instrument-go-application.rst
  gdi/get-data-in/application/java/troubleshooting/common-java-troubleshooting.rst
  gdi/get-data-in/application/nodejs/configuration/nodejs-otel-metrics.rst
  gdi/get-data-in/application/nodejs/instrumentation/instrument-nodejs-application.rst
Labels: sync

#387 Pulling refs/heads/main into main
  _includes/metrics-pipeline/metrics-pipeline-preview-header.rst
  index.rst
  infrastructure/metrics-pipeline/aggregate-drop-use-case.rst
  infrastructure/metrics-pipeline/data-dropping-impact.rst
  infrastructure/metrics-pipeline/metrics-pipeline-intro.rst
  infrastructure/metrics-pipeline/metrics-pipeline-preview-sitemap.rst
  infrastructure/metrics-pipeline/metrics-pipeline.rst
  infrastructure/metrics-pipeline/metrics-usage-report.rst
  infrastructure/metrics-pipeline/use-metrics-pipeline.rst
Labels: sync

#388 Pulling refs/heads/main into main
  infrastructure/metrics-pipeline/use-metrics-pipeline.rst
Labels: sync

#392 Pulling refs/heads/main into main
  synthetics/test-config/global-variables.rst
Labels: sync

#393 Pulling refs/heads/main into main
  _images/apm/trace-analyzer/MetricTables.png
  _images/apm/trace-analyzer/TraceAnalyzerControls.png
  _images/apm/trace-analyzer/TraceDragDropChart.gif
  _images/apm/trace-analyzer/TraceSelectTag.png
  _images/apm/trace-analyzer/heatmap.png
  _images/apm/trace-analyzer/metric-tables.png
  _images/apm/trace-analyzer/trace-analyzer.png
  _images/apm/trace-analyzer/trace-drag-drop-chart.gif
  _images/apm/trace-analyzer/trace-error-chart.gif
  _images/apm/trace-analyzer/trace-select-tag.png
  apm/apm-spans-traces/trace-analyzer.rst
  apm/apm-spans-traces/trace-search.rst
  apm/apm-spans-traces/traces-spans.rst
  apm/apm-use-cases/apm-use-cases-intro.rst
  apm/apm-use-cases/specific-trace.rst
  apm/apm-use-cases/troubleshoot-traces.rst
  apm/intro-to-apm.rst
  apm/key-concepts.rst
  apm/set-up-apm/apm-orientation.rst
  get-started/use-case-landing.rst
Labels: sync

#394 Pulling refs/heads/main into main
  gdi/opentelemetry/components.rst
  logs/lo-connect-landing.rst
  logs/logviews.rst
  logs/save-share.rst
Labels: sync

#395 Update CODEOWNERS
  .github/CODEOWNERS
Labels: internal

#398 Pulling refs/heads/main into main
  _images/incident-intelligence/Incident-intelligence-take-shift-icon.png
  _images/incident-intelligence/Incident-intelligence-take-shift-icon.tiff
  _images/incident-intelligence/shift-reassign1.png
  _images/incident-intelligence/shift-reassign2.png
  _static/jsonpull-splunk.js
  _static/signalfx-alabaster.css
  admin/users/manage-users.rst
  conf.py
  incident-intelligence/create-manage-on-call-schedules/create-manage-on-call-schedules.rst
  incident-intelligence/create-manage-on-call-schedules/reassign-shift.rst
  index.rst
Labels: sync

#399 Pulling refs/heads/main into main
  README.md
  gdi/opentelemetry/sizing.rst
Labels: sync

#402 Pulling refs/heads/main into main
  gdi/opentelemetry/install-k8s.rst
  gdi/opentelemetry/install-the-collector.rst
Labels: sync

#403 Pulling refs/heads/main into main
  alerts-detectors-notifications/create-detectors-for-alerts.rst
Labels: sync

#404 Pulling refs/heads/main into main
  gdi/logstash/logstash.md
Labels: sync

#405 Pulling refs/heads/main into main
  _static/jsonpull-splunk.js
  _static/signalfx-includes.js
  gdi/opentelemetry/components/kubelet-stats-receiver.rst
Labels: sync

#406 Pulling refs/heads/main into main
  data-visualization/enablerelatedcontent.rst
  gdi/opentelemetry/collector-with-the-uf.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/databricks-receiver.rst
  gdi/opentelemetry/components/fluentd-receiver.rst
  gdi/opentelemetry/components/mongodb-atlas-receiver.rst
  gdi/opentelemetry/components/oracledb-receiver.rst
  gdi/opentelemetry/components/prometheus-receiver.rst
  gdi/opentelemetry/configure-the-collector.rst
  gdi/opentelemetry/install-linux.rst
  gdi/opentelemetry/install-windows.rst
  gdi/opentelemetry/sizing.rst
  gdi/opentelemetry/smart-agent-migration-to-otel-collector.rst
  gdi/opentelemetry/splunk-collector-troubleshooting.rst
  gdi/other-ingestion-methods/send-custom-metrics.rst
  logs/logs.rst
Labels: sync

#407 Pulling refs/heads/main into main
  gdi/get-data-in/application/application.rst
Labels: sync

#408 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-terraformconfig.rst
  gdi/get-data-in/connect/aws/aws-wizardconfig.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  gdi/get-data-in/connect/azure/azure.rst
  gdi/get-data-in/connect/connect.rst
  gdi/get-data-in/connect/gcp/gcp.rst
Labels: sync

#409 Pulling refs/heads/main into main
  gdi/logstash/logstash.md
Labels: sync

#410 Pulling refs/heads/main into main
  gdi/get-data-in/application/dotnet/instrumentation/connect-traces-logs.rst
Labels: sync

#411 Pulling refs/heads/main into main
  _images/apm/trace-analyzer/TraceAnalyzerLimit.png
  _images/apm/trace-analyzer/metric-tables.png
  _images/apm/trace-analyzer/trace-analyzer.png
  _images/apm/trace-analyzer/trace-select-tag.png
  apm/apm-spans-traces/trace-analyzer.rst
  apm/apm-spans-traces/trace-search.rst
  apm/apm-use-cases/apm-use-cases-intro.rst
  apm/apm-use-cases/specific-trace.rst
Labels: sync

#412 Pulling refs/heads/main into main
  _images/logs/setupLOC1.png
  _images/logs/setupLOC2.png
  logs/scp.rst
  metrics-and-metadata/metrics.rst
Labels: sync

#413 Pulling refs/heads/main into main
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/configure-the-collector.rst
  gdi/opentelemetry/opentelemetry.rst
  gdi/opentelemetry/resources.rst
  get-started/use-cases/use-case-collector.rst
Labels: sync

#414 Pulling refs/heads/main into main
  _includes/application-receiver-table.rst
Labels: sync

#415 Pulling refs/heads/main into main
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/attributes-processor.rst
  gdi/opentelemetry/components/prometheus-receiver.rst
  gdi/opentelemetry/components/resourcedetection-processor.rst
  gdi/opentelemetry/components/transform-processor.rst
Labels: sync

#416 Pulling refs/heads/main into main
  gdi/collectd/collectd-uptime.md
Labels: sync

#417 Pulling refs/heads/main into main
  gdi/get-data-in/application/application.rst
  gdi/get-data-in/application/dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/application/dotnet/troubleshooting/common-dotnet-troubleshooting.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
Labels: sync

#418 Pulling refs/heads/main into main
  index.rst
  references/per-product-limits.rst
Labels: sync

#419 Pulling refs/heads/main into main
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/databricks-receiver.rst
  gdi/opentelemetry/components/host-metrics-receiver.rst
  gdi/opentelemetry/components/kubelet-stats-receiver.rst
  gdi/opentelemetry/components/kubernetes-cluster-receiver.rst
  gdi/opentelemetry/components/logging-exporter.rst
  gdi/opentelemetry/components/mongodb-atlas-receiver.rst
  gdi/opentelemetry/components/oracledb-receiver.rst
  gdi/opentelemetry/components/prometheus-receiver.rst
  gdi/opentelemetry/components/receiver-creator-receiver.rst
  gdi/opentelemetry/components/resource-processor.rst
  gdi/opentelemetry/components/resourcedetection-processor.rst
  gdi/opentelemetry/components/splunk-apm-exporter.rst
  gdi/opentelemetry/components/splunk-hec-receiver.rst
  gdi/opentelemetry/components/windowsperfcounters-receiver.rst
  gdi/opentelemetry/splunk-collector-troubleshooting.rst
  gdi/windows/telegraf-win_perf_counters.md
Labels: sync

#420 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-apiconfig.rst
  gdi/get-data-in/connect/aws/aws-wizardconfig.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  infrastructure/monitor/aws-infra-metadata.rst
Labels: sync

#421 Pulling refs/heads/main into main
  gdi/get-data-in/application/dotnet/instrumentation/instrument-dotnet-application.rst
Labels: sync

#422 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/get-awstoc.rst
  gdi/opentelemetry/components/logging-exporter.rst
Labels: sync

#424 Pulling refs/heads/main into main
  _static/jsonpull-splunk.js
  incident-intelligence/create-manage-on-call-schedules/create-manage-on-call-schedules.rst
  logs/scp.rst
Labels: sync

#425 Pulling refs/heads/main into main
  gdi/opentelemetry/configure-the-collector.rst
  gdi/opentelemetry/install-k8s.rst
  gdi/opentelemetry/kubernetes-config-advanced.rst
  gdi/opentelemetry/kubernetes-config-logs.rst
  gdi/opentelemetry/kubernetes-config.rst
Labels: sync

#427 Pulling refs/heads/main into main
  .github/workflows/repo-sync.yml
Labels: sync

#426 Deprecate `process.cpu.utilization` for SFx for .NET
  gdi/get-data-in/application/dotnet/configuration/dotnet-metrics-attributes.rst
Labels: instrumentation, external

#429 Pulling refs/heads/main into main
  apm/span-tags/cmms.rst
  apm/span-tags/index-span-tags.rst
  apm/span-tags/index-tag-tips.rst
  apm/span-tags/metricsets.rst
  incident-intelligence/create-configure-incident-policies.rst
  incident-intelligence/create-manage-on-call-schedules/reassign-shift.rst
Labels: sync

#430 Pulling refs/heads/main into main
  logs/scp.rst
Labels: sync

#431 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-post-install.rst
  gdi/get-data-in/connect/aws/aws-troubleshooting.rst
Labels: sync

#435 Pulling refs/heads/main into main
  index.rst
Labels: sync

#438 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-architecture.rst
  gdi/opentelemetry/install-linux.rst
Labels: sync

#439 Pulling refs/heads/main into main
  get-started/core2o11y/setup-o11y/setup-o11y.rst
  incident-intelligence/ingest-alerts/ingest-alerts.rst
  incident-intelligence/ingest-alerts/ingest-splunk-alerts.rst
  synthetics/test-config/public-locations-table.csv
  synthetics/test-config/public-locations.csv
Labels: sync

#441 Pulling refs/heads/main into main
  gdi/opentelemetry/open-support-request.rst
  gdi/opentelemetry/splunk-collector-troubleshooting.rst
  gdi/opentelemetry/support-checklist.rst
  gdi/opentelemetry/troubleshoot-k8s.rst
  gdi/opentelemetry/troubleshoot-logs.rst
  gdi/opentelemetry/troubleshooting.rst
Labels: sync

#442 Pulling refs/heads/main into main
  gdi/get-data-in/application/dotnet/get-started.rst
  gdi/get-data-in/application/java/get-started.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-dotnet.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-k8s.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-linux.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java.rst
  gdi/opentelemetry/deployments/deployments-chef.rst
  gdi/opentelemetry/deployments/deployments-linux-ansible.rst
  gdi/opentelemetry/deployments/deployments-linux-puppet.rst
  gdi/opentelemetry/deployments/deployments-salt.rst
  gdi/opentelemetry/opentelemetry.rst
  gdi/opentelemetry/zero-config.rst
  index.rst
Labels: sync

#444 Test - Ignore Update README.md
  README.md
Labels: internal

#400 jmalin-fix-vale-errors: test
  admin/admin.rst
  admin/allow-services.rst
  admin/link-metadata-to-content.rst
Labels: internal

#451 Pulling refs/heads/main into main
  admin/users/manage-users.rst
  gdi/opentelemetry/collector-architecture.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/postgresql-receiver.rst
  gdi/opentelemetry/components/signalfx-exporter.rst
  gdi/opentelemetry/components/signalfx-receiver.rst
  gdi/opentelemetry/components/smartagent-receiver.rst
  gdi/opentelemetry/components/splunk-apm-exporter.rst
  incident-intelligence/ingest-alerts/ingest-alerts.rst
  incident-intelligence/ingest-alerts/ingest-splunk-alerts.rst
Labels: sync

#454 Pulling refs/heads/main into main
  sonar-project.properties
Labels: sync

#456 Pulling refs/heads/main into main
  _images/get-started/o11y-user-doc-hero-banner-v2.svg
Labels: sync

#458 Pulling refs/heads/main into main
  _images/apm/apm-use-cases/EndpointPerTagSpotlight.png
  _images/apm/apm-use-cases/EndpointPerfCompare.png
  _images/apm/apm-use-cases/EndpointPerfCompareResult.png
  _images/apm/apm-use-cases/EndpointPerfOverview.png
  _images/apm/apm-use-cases/EndpointPerfSearch.png
  _images/apm/apm-use-cases/EndpointPerfSort.png
  _images/apm/apm-use-cases/EndpointPerformanceCard.png
  _images/incident-intelligence/ii-snow-ticket.png
  admin/notif-services/servicenow.rst
  apm/apm-use-cases/apm-use-cases-intro.rst
  apm/apm-use-cases/endpoint-performance.rst
  apm/key-concepts.rst
  incident-intelligence/ingest-alerts/ingest-alerts.rst
  incident-intelligence/ingest-alerts/ingest-snow.rst
Labels: sync

#459 Pulling refs/heads/main into main
  apm/apm-use-cases/endpoint-performance.rst
  get-started/use-case-landing.rst
Labels: sync

#460 Pulling refs/heads/main into main
  gdi/get-data-in/application/java/instrumentation/connect-traces-logs.rst
Labels: sync

#461 Pulling refs/heads/main into main
  apm/set-up-apm/sensitive-data-controls.rst
  gdi/opentelemetry/components/attributes-processor.rst
  gdi/opentelemetry/configure-remove.rst
  gdi/opentelemetry/configure-the-collector.rst
  gdi/opentelemetry/tags.rst
  infrastructure/metrics-pipeline/metrics-pipeline-intro.rst
Labels: sync

#462 Pulling refs/heads/main into main
  apm/apm-use-cases/endpoint-performance.rst
Labels: sync

#463 Pulling refs/heads/main into main
  logs/individual-log.rst
  logs/logs-individual-log-connect.rst
  logs/logviews.rst
  logs/metricization.rst
Labels: sync

#464 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-architecture.rst
Labels: sync

#465 Pulling refs/heads/main into main
  logs/individual-log.rst
Labels: sync

#467 Pulling refs/heads/main into main
  _images/logs/error-log.png
  _images/logs/group-by-version.png
  _images/logs/related-content.png
  _images/logs/service-map.png
  logs/LOconnect-usecase.rst
  logs/lo-connect-landing.rst
  logs/queries.rst
Labels: sync

#468 Pulling refs/heads/main into main
  _includes/application-receiver-table.rst
  gdi/index.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/kubelet-stats-receiver.rst
  gdi/opentelemetry/components/kubernetes-attributes-processor.rst
  gdi/opentelemetry/components/kubernetes-cluster-receiver.rst
Labels: sync

#469 Pulling refs/heads/main into main
  metrics-and-metadata/metrics.rst
Labels: sync

#470 Pulling refs/heads/main into main
  _includes/gdi/next-steps.rst
  gdi/cadvisor/cadvisor.md
  gdi/elasticsearch/elasticsearch.md
  gdi/get-data-in/application/dotnet/configuration/advanced-dotnet-configuration.rst
  gdi/get-data-in/application/dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/application/go/configuration/advanced-go-otel-configuration.rst
  gdi/get-data-in/application/go/configuration/go-otel-metrics.rst
  gdi/get-data-in/application/go/instrumentation/instrument-go-application.rst
  gdi/get-data-in/application/go/troubleshooting/common-go-troubleshooting.rst
  gdi/get-data-in/application/java/configuration/advanced-java-otel-configuration.rst
  gdi/get-data-in/application/java/instrumentation/instrument-java-application.rst
  gdi/get-data-in/application/nodejs/configuration/advanced-nodejs-otel-configuration.rst
  gdi/get-data-in/application/nodejs/instrumentation/instrument-nodejs-application.rst
  gdi/get-data-in/application/python/configuration/advanced-python-otel-configuration.rst
  gdi/get-data-in/application/python/troubleshooting/common-python-troubleshooting.rst
  gdi/get-data-in/application/ruby/configuration/advanced-ruby-otel-configuration.rst
  gdi/get-data-in/connect/aws/aws-apiconfig.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  gdi/get-data-in/integrations.rst
  gdi/get-data-in/rum/android/configure-rum-android-instrumentation.rst
  gdi/get-data-in/rum/ios/install-rum-ios.rst
  gdi/get-data-in/serverless/aws/otel-lambda-layer/advanced-configuration.rst
  gdi/mongodb-atlas/mongodb-atlas.md
  gdi/mysql/mysql.md
  gdi/nagios/nagios.md
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-k8s.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-linux.rst
  gdi/opentelemetry/deployments/deployments-chef.rst
  gdi/opentelemetry/deployments/deployments-linux-ansible.rst
  gdi/opentelemetry/deployments/deployments-linux-puppet.rst
  gdi/opentelemetry/deployments/deployments-salt.rst
  gdi/opentelemetry/install-linux.rst
  gdi/opentelemetry/kubernetes-config-advanced.rst
  gdi/opentelemetry/otel-upgrade.rst
  gdi/opentelemetry/security.rst
  gdi/opentelemetry/sizing.rst
Labels: sync

#471 Pulling refs/heads/main into main
  data-visualization/charts/charts.rst
  data-visualization/dashboards/view-dashboards.rst
  logs/logviews.rst
Labels: sync

#473 Pulling refs/heads/main into main
  data-visualization/dashboards/dashboard-share-clone-mirror.rst
  infrastructure/quickstart-imm.rst
Labels: sync

#474 Pulling refs/heads/main into main
  infrastructure/metrics-pipeline/metrics-usage-report.rst
Labels: sync
