Repository splunk/public-o11y-docs, pull requests merged in 2023-11, with the labels that each got.

#1038 Update auto-instrumentation-operator.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-operator.rst
Labels: external, stop-alert

#1037 Pulling refs/heads/main into main
  admin/subscription-usage/imm-billing.rst
  admin/subscription-usage/monitor-imm-billing-usage.rst
  gdi/get-data-in/connect/aws/aws-connect-ms.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  gdi/monitors-hosts/nginx.rst
  infrastructure/metrics-pipeline/data-dropping-impact.rst
  logs/LOconnect-default-index.rst
  logs/infinite.rst
  logs/live-tail.rst
  logs/lo-connect-landing.rst
  logs/lo-transition.rst
  logs/processors.rst
  logs/search-time-rules.rst
  rum/rum-session-replay.rst
  splunkplatform/unified-id/unified-identity.rst
Labels: sync

#1041 Pulling refs/heads/main into main
  apm/span-tags/add-context-trace-span.rst
Labels: sync

#1042 Pulling refs/heads/main into main
  _images/apm/trace-analyzer/TraceAnalyzerControls_sampling.png
  apm/apm-spans-traces/trace-analyzer.rst
Labels: sync

#1043 Pulling refs/heads/main into main
  _includes/requirements/java.rst
  gdi/get-data-in/application/java/java-otel-requirements.rst
Labels: sync

#1044 Pulling refs/heads/main into main
  gdi/opentelemetry/kubernetes-config-advanced.rst
Labels: sync

#1045 Pulling refs/heads/main into main
  locales/ja_JA/LC_MESSAGES/_includes.mo
  locales/ja_JA/LC_MESSAGES/admin.mo
  locales/ja_JA/LC_MESSAGES/alerts-detectors-notifications.mo
  locales/ja_JA/LC_MESSAGES/analytics.mo
  locales/ja_JA/LC_MESSAGES/apm.mo
  locales/ja_JA/LC_MESSAGES/data-visualization.mo
  locales/ja_JA/LC_MESSAGES/gdi.mo
  locales/ja_JA/LC_MESSAGES/get-started.mo
  locales/ja_JA/LC_MESSAGES/incident-intelligence.mo
  locales/ja_JA/LC_MESSAGES/index.mo
  locales/ja_JA/LC_MESSAGES/infrastructure.mo
  locales/ja_JA/LC_MESSAGES/logs.mo
  locales/ja_JA/LC_MESSAGES/metrics-and-metadata.mo
  locales/ja_JA/LC_MESSAGES/references.mo
  locales/ja_JA/LC_MESSAGES/rum.mo
  locales/ja_JA/LC_MESSAGES/slo.mo
  locales/ja_JA/LC_MESSAGES/splunkplatform.mo
  locales/ja_JA/LC_MESSAGES/synthetics.mo
Labels: sync

#1046 Update discovery-mode.rst
  gdi/opentelemetry/discovery-mode.rst
Labels: external, stop-alert

#1048 Update discovery mode example
  gdi/opentelemetry/discovery-mode.rst
Labels: external, stop-alert

#1049 Pulling refs/heads/main into main
  gdi/opentelemetry/install-k8s.rst
Labels: sync

#1051 Pulling refs/heads/main into main
  _includes/requirements/java.rst
  apm/profiling/get-data-in-profiling.rst
Labels: sync

#1052 Pulling refs/heads/main into main
  apm/profiling/get-data-in-profiling.rst
  apm/profiling/profiling-memory-metrics.rst
  gdi/get-data-in/application/nodejs/configuration/advanced-nodejs-otel-configuration.rst
  gdi/get-data-in/application/nodejs/configuration/nodejs-otel-metrics.rst
  gdi/get-data-in/application/nodejs/get-started.rst
  gdi/get-data-in/application/nodejs/instrumentation/connect-traces-logs.rst
  gdi/get-data-in/application/nodejs/instrumentation/instrument-nodejs-application.rst
  gdi/get-data-in/application/nodejs/instrumentation/manual-instrumentation.rst
  gdi/get-data-in/application/nodejs/splunk-nodejs-otel-distribution.rst
  gdi/get-data-in/application/nodejs/troubleshooting/common-nodejs-troubleshooting.rst
  gdi/get-data-in/application/nodejs/troubleshooting/migrate-signalfx-nodejs-agent-to-otel.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/application/otel-dotnet/troubleshooting/common-dotnet-troubleshooting.rst
  gdi/get-data-in/serverless/aws/signalfx-lambda-wrappers.rst
  gdi/get-data-in/serverless/azure/instrument-azure-functions.rst
  index.rst
  locales/ja_JA/LC_MESSAGES/apm.po
  rum/intro-to-rum.rst
  rum/rum-dashboards/rum-custom-dashboards.rst
  rum/rum-identify-span-problems.rst
  rum/rum-scenario-library/identify-span-problems.rst
  rum/rum-scenario-library/rum-mobile-scenario.rst
  rum/rum-scenario-library/scenario-landingpage.rst
  rum/rum-scenario-library/scenario-monitoring.rst
  rum/rum-scenario-library/spa-custom-event.rst
  synthetics/synth-scenarios/api-test-scenario.rst
  synthetics/synth-scenarios/browser-test-scenario.rst
  synthetics/synth-scenarios/rum-synth-scenario.rst
  synthetics/synth-scenarios/synth-landing.rst
  synthetics/synth-scenarios/uptime-test-scenario.rst
  synthetics/test-config/rum-synth.rst
  synthetics/test-config/synth-configure-app.rst
Labels: sync

#1054 Update gcp-logs.rst
  gdi/get-data-in/connect/gcp/gcp-logs.rst
Labels: external, stop-alert

#1055 Pulling refs/heads/main into main
  _images/gdi/azure-collector-insights.png
  _images/gdi/gcp-collector-insights.png
  gdi/get-data-in/connect/azure/azure.rst
  gdi/get-data-in/connect/gcp/gcp.rst
Labels: sync

#1056 Pulling refs/heads/main into main
  data-visualization/use-time-range-selector.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-k8s.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-nodejs-k8s.rst
  metrics-and-metadata/relatedcontent.rst
Labels: sync

#1057 Pulling refs/heads/main into main
  infrastructure/manage-navigator-dashbds.rst
  infrastructure/use-navigators.rst
  synthetics/api-test/set-up-api-test.rst
  synthetics/browser-test/set-up-browser-test.rst
  synthetics/uptime-test/set-up-uptime-test.rst
Labels: sync

#1058 Pulling refs/heads/main into main
  _images/logs/chrome-secure1.png
  _images/logs/chrome-secure2.png
  _images/logs/chrome-secure3.png
  _includes/mpm-arm/mpm-arm-preview-header.rst
  _static/jsonpull-splunk.js
  alerts-detectors-notifications/alerts-detectors-notifications.rst
  apm/profiling/get-data-in-profiling.rst
  conf.py
  gdi/get-data-in/application/application.rst
  gdi/get-data-in/application/dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/rum/rum-instrumentation.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-k8s.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-nodejs-k8s.rst
  gdi/opentelemetry/configure-the-collector-ootb.rst
  gdi/opentelemetry/opentelemetry.rst
  gdi/opentelemetry/zero-config.rst
  get-started/o11y-architecture.rst
  infrastructure/metrics-pipeline/data-dropping-impact.rst
  infrastructure/metrics-pipeline/metrics-pipeline-intro.rst
  infrastructure/mpm-arm/aggregate-drop-use-case.rst
  infrastructure/mpm-arm/data-dropping-impact.rst
  infrastructure/mpm-arm/delete-metric-ruleset.rst
  infrastructure/mpm-arm/metrics-pipeline-intro.rst
  infrastructure/mpm-arm/metrics-pipeline.rst
  infrastructure/mpm-arm/metrics-usage-report.rst
  infrastructure/mpm-arm/mpm-arm-preview-sitemap.rst
  infrastructure/mpm-arm/pipeline-management-use-cases.rst
  infrastructure/mpm-arm/related-metrics.rst
  infrastructure/mpm-arm/use-MTS-aggregation-pipeline.rst
  infrastructure/mpm-arm/use-MTS-data-routing-pipeline.rst
  infrastructure/mpm-arm/use-metrics-pipeline.rst
  infrastructure/mpm-arm/view-metrics-usage-list.rst
  logs/scp.rst
  metrics-and-metadata/metrics.rst
Labels: sync

#1059 Pulling refs/heads/main into main
  gdi/opentelemetry/kubernetes-config-advanced.rst
  logs/scp.rst
Labels: sync

#1061 Update kubernetes-scheduler.rst
  gdi/monitors-orchestration/kubernetes-scheduler.rst
Labels: external

#1062 Update openshift-cluster.rst
  gdi/monitors-orchestration/openshift-cluster.rst
Labels: external

#1060 Pulling refs/heads/main into main
  apm/profiling/get-data-in-profiling.rst
  apm/profiling/intro-profiling.rst
  gdi/get-data-in/application/java/instrumentation/instrument-java-application.rst
  gdi/get-data-in/application/nodejs/instrumentation/instrument-nodejs-application.rst
  gdi/get-data-in/application/python/configuration/advanced-python-otel-configuration.rst
  gdi/get-data-in/application/python/instrumentation/instrument-python-application.rst
  gdi/opentelemetry/kubernetes-config-advanced.rst
  gdi/opentelemetry/metrics-ootb-k8s.rst
Labels: sync

#1063 Pulling refs/heads/main into main
  _includes/admin/roles_navigation.rst
  _includes/admin/roles_navigation1.rst
  _includes/log-observer-transition.rst
  _includes/requirements/collector-linux.rst
  admin/authentication/SSO/sso-AzureAD.rst
  admin/authentication/SSO/sso-Google.rst
  admin/authentication/SSO/sso-GoogleCloudIDP.rst
  admin/notif-services/webhook.rst
  admin/user-management/roles/roles-and-capabilities-table.rst
  admin/user-management/roles/users-assign-roles.rst
  admin/user-management/teams/configure-page.rst
  admin/user-management/teams/enhanced-team-security.rst
  admin/user-management/teams/manage-membership.rst
  admin/user-management/teams/manage-teams.rst
  admin/user-management/user-management-intro.rst
  admin/user-management/users/manage-users.rst
  get-started/service-description.rst
  metrics-and-metadata/link-metadata-to-content.rst
  private-preview/rbac/users-assign-roles.rst
Labels: sync

#1064 Pulling refs/heads/main into main
  _images/get-started/tutorial-aws-sources.png
  _images/get-started/tutorial-aws-wizard.png
  gdi/get-data-in/get-data-in.rst
  get-started/tutorials.rst
  get-started/tutorials/aws-tutorial/about-aws-tutorial.rst
  get-started/tutorials/aws-tutorial/tutorial-aws-start.rst
  get-started/tutorials/aws-tutorial/tutorial-aws-use.rst
  get-started/tutorials/k8s-infrastructure-tutorial/about-k8s-tutorial.rst
  get-started/tutorials/k8s-infrastructure-tutorial/get-started-k8s-imm.rst
  get-started/tutorials/k8s-infrastructure-tutorial/k8s-activate-detector.rst
  get-started/tutorials/k8s-infrastructure-tutorial/k8s-install-otel.rst
  get-started/tutorials/k8s-infrastructure-tutorial/k8s-monitor-with-navigators.rst
  index.rst
  infrastructure/k8s-infrastructure-tutorial/k8s-additional-resources.rst
Labels: sync

#1066 Pulling refs/heads/main into main
  _images/logs/chrome-secure1.png
  _images/logs/chrome-secure2.png
  infrastructure/intro-to-infrastructure.rst
  metrics-and-metadata/enablerelatedcontent.rst
  metrics-and-metadata/relatedcontent.rst
Labels: sync

#1065 OTel Go distribution sends metrics directly to ingest
  gdi/get-data-in/application/go/instrumentation/instrument-go-application.rst
Labels: external, stop-alert

#1067 Pulling refs/heads/main into main
  _templates/banner.html
Labels: sync

#1068 Pulling refs/heads/main into main
  gdi/opentelemetry/support-checklist.rst
Labels: sync

#1069 Update maven coordinates for upstream Android instrumentation
  gdi/get-data-in/rum/android/install-rum-android.rst
Labels: external, stop-alert

#1070 Update instrument-php-application.rst
  gdi/get-data-in/application/php/instrumentation/instrument-php-application.rst
Labels: external, stop-alert

#1071 Pulling refs/heads/main into main
  _includes/admin/roles_data_configuration.rst
  _includes/admin/roles_data_configuration1.rst
  _includes/admin/roles_help_support.rst
  _includes/admin/roles_help_support1.rst
  _includes/admin/roles_log_observer.rst
  _includes/admin/roles_log_observer1.rst
  _includes/admin/roles_navigation.rst
  _includes/admin/roles_navigation1.rst
  gdi/get-data-in/connect/aws/aws-connect-ms.rst
Labels: sync

#1072 Pulling refs/heads/main into main
  gdi/get-data-in/application/otel-dotnet/configuration/dotnet-metrics-attributes.rst
  gdi/get-data-in/application/otel-dotnet/dotnet-requirements.rst
  gdi/opentelemetry/deployment-modes.rst
  gdi/opentelemetry/install-k8s.rst
  gdi/opentelemetry/kubernetes-config-advanced.rst
  infrastructure/network-explorer/network-explorer-setup-non-k8s.rst
  infrastructure/network-explorer/network-explorer-setup.rst
  infrastructure/network-explorer/network-explorer.rst
Labels: sync

#1075 Pulling refs/heads/main into main
  gdi/get-data-in/application/nodejs/configuration/advanced-nodejs-otel-configuration.rst
  gdi/get-data-in/application/nodejs/get-started.rst
  gdi/get-data-in/application/nodejs/performance.rst
  gdi/get-data-in/application/otel-dotnet/get-started.rst
  gdi/get-data-in/application/otel-dotnet/performance.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-k8s.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-nodejs-k8s.rst
  synthetics/browser-test/browser-test-results.rst
Labels: sync

#1076 Fix instructions to uninstall the collector on Windows
  gdi/opentelemetry/uninstall-the-collector.rst
Labels: external, stop-alert
