Repository splunk/public-o11y-docs, pull requests merged in 2023-06, with the labels that each got.

#659 Pulling refs/heads/main into main
  _static/custom.css
  _static/customjs.js
  _static/signalfx-alabaster.css
  _static/signalfx-includes.css
  _static/signalfx-includes.js
  _templates/layout.html
Labels: sync

#660 Pulling refs/heads/main into main
  gdi/get-data-in/application/python/instrumentation/instrument-python-application.rst
Labels: sync

#661 Pulling refs/heads/main into main
  Makefile
Labels: sync

#663 Pulling refs/heads/main into main
  _includes/rum-data-model.rst
  gdi/get-data-in/rum/react/configure-rum-react-instrumentation.rst
  gdi/get-data-in/rum/react/get-react-native-data-in.rst
  gdi/get-data-in/rum/react/install-rum-react.rst
  gdi/get-data-in/rum/react/manual-rum-react-instrumentation.rst
  gdi/get-data-in/rum/react/rum-react-data-model.rst
  gdi/get-data-in/rum/rum-instrumentation.rst
  gdi/opentelemetry/components/batch-processor.rst
  gdi/opentelemetry/components/mongodb-atlas-receiver.rst
  gdi/opentelemetry/components/receiver-creator-receiver.rst
Labels: sync

#664 Pulling refs/heads/main into main
  apm/profiling/get-data-in-profiling.rst
  apm/profiling/profiling-troubleshooting.rst
Labels: sync

#666 Pulling refs/heads/main into main
  get-started/core2o11y/core2o11y-landing.rst
  get-started/core2o11y/practice-reliability/slis.rst
  get-started/core2o11y/setup-o11y/setup-o11y.rst
Labels: sync

#668 Pulling refs/heads/main into main
  admin/authentication-tokens/org-tokens.rst
  admin/org-metrics.md
  admin/subscription-usage/monitor-imm-billing-usage.rst
  admin/subscription-usage/subscription-usage-overview.rst
  references/per-product-limits.rst
  synthetics/test-config/eu-public-locations.csv
  synthetics/test-config/public-locations.rst
Labels: sync

#669 Pulling refs/heads/main into main
  gdi/opentelemetry/sizing.rst
Labels: sync

#672 Pulling refs/heads/main into main
  metrics-and-metadata/metrics-dimensions-mts.rst
  metrics-and-metadata/metrics-finder-metadata-catalog.rst
  metrics-and-metadata/metrics.rst
Labels: sync

#675 Pulling refs/heads/main into main
  apm/profiling/get-data-in-profiling.rst
  apm/profiling/profiling-memory-metrics.rst
Labels: sync

#676 Update java-otel-metrics-attributes.rst
  gdi/get-data-in/application/java/configuration/java-otel-metrics-attributes.rst
Labels: external

#677 Pulling refs/heads/main into main
  gdi/opentelemetry/components/signalfx-exporter.rst
Labels: sync

#679 Pulling refs/heads/main into main
  apm/profiling/profiling-memory-metrics.rst
  gdi/get-data-in/application/java/instrumentation/java-servers-instructions.rst
  gdi/get-data-in/application/python/instrumentation/instrument-python-application.rst
  gdi/get-data-in/connect/aws/aws-post-install.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  gdi/get-data-in/rum/ios/install-rum-ios.rst
  gdi/get-data-in/serverless/aws/otel-lambda-layer/instrument-lambda-functions.rst
  gdi/monitors-databases/microsoft-sql-server.md
  gdi/monitors-hosts/host-processlist.md
  gdi/monitors-languages/jmx.md
  gdi/opentelemetry/install-linux.rst
  gdi/smart-agent/smart-agent-resources.rst
  metrics-and-metadata/enablerelatedcontent.rst
Labels: sync

#680 Pulling refs/heads/main into main
  gdi/get-data-in/application/java/configuration/java-otel-metrics-attributes.rst
Labels: sync

#681 Pulling refs/heads/main into main
  alerts-detectors-notifications/mute-notifications.rst
Labels: sync

#682 Pulling refs/heads/main into main
  _images/apm/db-query-perf/apm-configuration.png
  apm/db-query-perf/db-perf-redis-scenario.rst
  apm/db-query-perf/db-perf-reference.rst
  apm/db-query-perf/db-perf-scenario.rst
  apm/db-query-perf/db-perf-troubleshooting.rst
  apm/db-query-perf/db-query-performance.rst
  apm/db-query-perf/turn-on-db-perf.rst
Labels: sync

#683 Pulling refs/heads/main into main
  gdi/opentelemetry/splunk-collector-troubleshooting.rst
Labels: sync

#684 Pulling refs/heads/main into main
  gdi/opentelemetry/components/splunk-hec-receiver.rst
Labels: sync

#686 Pulling refs/heads/main into main
  metrics-and-metadata/metrics-finder-metadata-catalog.rst
Labels: sync

#687 Pulling refs/heads/main into main
  alerts-detectors-notifications/autodetect/autodetect-list.rst
Labels: sync

#692 Pulling refs/heads/main into main
  gdi/databases.rst
Labels: sync

#693 Update Node.js version for Lambda
  gdi/get-data-in/serverless/aws/otel-lambda-layer/instrument-lambda-functions.rst
Labels: external, stop-alert

#694 Pulling refs/heads/main into main
  gdi/get-data-in/get-data-in.rst
  get-started/o11y.rst
  get-started/welcome.rst
Labels: sync

#696 Pulling refs/heads/main into main
  gdi/opentelemetry/components/splunk-hec-exporter.rst
  gdi/opentelemetry/data-processing.rst
Labels: sync

#698 Pulling refs/heads/main into main
  gdi/get-data-in/application/dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/application/go/instrumentation/instrument-go-application.rst
  gdi/get-data-in/application/java/instrumentation/instrument-java-application.rst
  gdi/get-data-in/application/nodejs/instrumentation/instrument-nodejs-application.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/application/other-languages.rst
  gdi/get-data-in/application/php/instrumentation/instrument-php-application.rst
  gdi/get-data-in/application/python/instrumentation/instrument-python-application.rst
  gdi/get-data-in/application/ruby/instrumentation/instrument-ruby-application.rst
  gdi/get-data-in/compute/k8s.rst
  gdi/get-data-in/compute/linux.rst
  gdi/get-data-in/compute/windows.rst
  gdi/get-data-in/connect/aws/aws-wizardconfig.rst
  gdi/get-data-in/connect/azure/azure.rst
  gdi/get-data-in/connect/gcp/gcp.rst
  gdi/get-data-in/integrations.rst
  gdi/get-data-in/rum/android/get-android-data-in.rst
  gdi/get-data-in/rum/android/install-rum-android.rst
  gdi/get-data-in/rum/browser/configure-rum-browser-instrumentation.rst
  gdi/get-data-in/rum/browser/get-browser-data-in.rst
  gdi/get-data-in/rum/browser/install-rum-browser.rst
  gdi/get-data-in/rum/ios/get-ios-data-in.rst
  gdi/get-data-in/rum/ios/install-rum-ios.rst
  gdi/get-data-in/rum/react/get-react-native-data-in.rst
  gdi/get-data-in/rum/react/install-rum-react.rst
  gdi/get-data-in/serverless/aws/otel-lambda-layer/instrument-lambda-functions.rst
  gdi/get-data-in/serverless/azure/instrument-azure-functions.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-dotnet.rst
  gdi/opentelemetry/components/splunk-apm-exporter.rst
  gdi/opentelemetry/components/splunk-hec-exporter.rst
  gdi/opentelemetry/deployments/deployments-ecs-ec2.rst
  gdi/opentelemetry/deployments/deployments-fargate.rst
  gdi/opentelemetry/install-the-collector.rst
  gdi/opentelemetry/legacy-otel-mappings.md
  gdi/opentelemetry/smart-agent-migration-process.rst
Labels: sync

#700 Pulling refs/heads/main into main
  gdi/databases.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  gdi/hosts-servers.rst
  gdi/monitoring.rst
  gdi/monitors-databases/postgresql.md
  gdi/monitors-hosts/procstat.md
  gdi/monitors-monitoring/prometheus-exporter.md
  gdi/monitors-monitoring/prometheus-go.md
  gdi/monitors-orchestration/kubernetes-controller-manager.md
  gdi/monitors-orchestration/kubernetes-proxy.md
  gdi/postgresql/postgresql.md
Labels: sync

#701 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/get-awstoc.rst
Labels: sync

#702 Pulling refs/heads/main into main
  apm/profiling/get-data-in-profiling.rst
  gdi/get-data-in/application/dotnet/dotnet-requirements.rst
  gdi/get-data-in/application/otel-dotnet/dotnet-requirements.rst
Labels: sync

#703 Pulling refs/heads/main into main
  _static/customjs.js
  _templates/banner.html
  _templates/layout.html
  _templates/search.html
  conf.py
  gdi/monitors-cloud/kong.md
  search.rts
Labels: sync

#704 Pulling refs/heads/main into main
  admin/org-metrics.md
  alerts-detectors-notifications/autodetect/autodetect-list.rst
Labels: sync

#707 Pulling refs/heads/main into main
  gdi/opentelemetry/components/signalfx-exporter.rst
  gdi/opentelemetry/deployment-modes.rst
Labels: sync

#708 Pulling refs/heads/main into main
  gdi/opentelemetry/configure-the-collector.rst
  gdi/opentelemetry/other-configuration-sources.rst
Labels: sync

#709 Pulling refs/heads/main into main
  gdi/get-data-in/application/dotnet/instrumentation/connect-traces-logs.rst
  gdi/get-data-in/application/go/instrumentation/connect-traces-logs.rst
  gdi/get-data-in/application/java/instrumentation/connect-traces-logs.rst
  gdi/get-data-in/application/nodejs/instrumentation/connect-traces-logs.rst
  gdi/get-data-in/application/python/instrumentation/connect-traces-logs.rst
  gdi/get-data-in/application/ruby/instrumentation/connect-traces-logs.rst
Labels: sync

#710 Pulling refs/heads/main into main
  _images/infrastructure/aws-metric-tag-wildcard2.png
  _images/infrastructure/aws-metric-tag2.png
  infrastructure/monitor/aws-infra-monitor.rst
Labels: sync

#711 Pulling refs/heads/main into main
  _includes/metric-categories.rst
  _includes/metric-defs.md
  admin/subscription-usage/monitor-imm-billing-usage.rst
  gdi/index.rst
Labels: sync

#714 Pulling refs/heads/main into main
  README.md
Labels: sync

#715 Pulling refs/heads/main into main
  gdi/opentelemetry/components/filter-processor.rst
Labels: sync

#716 Pulling refs/heads/main into main
  infrastructure/monitor/aws-infra-monitor.rst
Labels: sync

#718 Pulling refs/heads/main into main
  _templates/404.html
  _templates/layout.html
  _templates/search.html
  admin/notif-services/slack.rst
  alerts-detectors-notifications/autodetect/autodetect-list.rst
Labels: sync

#719 Pulling refs/heads/main into main
  infrastructure/monitor/k8s-nav.rst
Labels: sync

#723 Pulling refs/heads/main into main
  alerts-detectors-notifications/auto-clearing-alerts.rst
Labels: sync

#724 Pulling refs/heads/main into main
  _images/edit-docs.png
  _static/custom.css
  _templates/breadcrumbs.html
  _templates/layout.html
  _templates/search.html
  get-started/support.rst
  index.rst
  references/contribute.rst
Labels: sync

#725 Update identify-span-problems.rst
  rum/rum-scenario-library/identify-span-problems.rst
Labels: external

#726 Pulling refs/heads/main into main
  gdi/get-data-in/application/go/instrumentation/go-manual-instrumentation.rst
  gdi/get-data-in/application/java/configuration/java-otel-metrics-attributes.rst
  gdi/get-data-in/application/java/instrumentation/java-manual-instrumentation.rst
  gdi/get-data-in/application/nodejs/configuration/nodejs-otel-metrics.rst
  gdi/get-data-in/application/nodejs/get-started.rst
  gdi/get-data-in/application/nodejs/instrumentation/manual-instrumentation.rst
  gdi/other-ingestion-methods/send-custom-metrics.rst
Labels: sync

#727 Update send-custom-metrics.rst
  gdi/other-ingestion-methods/send-custom-metrics.rst
Labels: external

#736 Pulling refs/heads/main into main
  get-started/core2o11y/core2o11y-landing.rst
  get-started/core2o11y/unified-id/unified-identity.rst
Labels: sync

#737 Pulling refs/heads/main into main
  get-started/core2o11y/unified-id/unified-identity.rst
Labels: sync

#738 Remove mentions of java jaeger configuration
  gdi/get-data-in/application/java/configuration/advanced-java-otel-configuration.rst
  gdi/get-data-in/application/java/troubleshooting/common-java-troubleshooting.rst
  gdi/get-data-in/application/java/troubleshooting/migrate-signalfx-java-agent-to-otel.rst
Labels: external

#739 Pulling refs/heads/main into main
  gdi/opentelemetry/smart-agent-migration-process.rst
  infrastructure/metrics-pipeline/data-dropping-impact.rst
  infrastructure/metrics-pipeline/metrics-pipeline-intro.rst
Labels: sync

#740 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-terraformconfig.rst
Labels: sync

#741 Pulling refs/heads/main into main
  gdi/get-data-in/application/go/configuration/go-otel-metrics.rst
  gdi/get-data-in/application/go/instrumentation/go-manual-instrumentation.rst
Labels: sync

#742 Pulling refs/heads/main into main
  get-started/core2o11y/core2o11y-landing.rst
Labels: sync

#743 Pulling refs/heads/main into main
  apm/apm-spans-traces/inferred-services.rst
Labels: sync

#745 Remove duplicate entry for serviceusage.services.use
  gdi/get-data-in/connect/gcp/gcp.rst
Labels: external

#744 Pulling refs/heads/main into main
  alerts-detectors-notifications/autodetect/autodetect-list.rst
  gdi/opentelemetry/smart-agent-migration-to-otel-collector.rst
Labels: sync

#746 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-architecture.rst
  gdi/opentelemetry/collector-with-the-uf.rst
  gdi/opentelemetry/data-processing.rst
  gdi/opentelemetry/install-k8s.rst
  gdi/opentelemetry/install-the-collector.rst
Labels: sync

#747 Pulling refs/heads/main into main
  admin/subscription-usage/monitor-imm-billing-usage.rst
  gdi/monitors-databases/sql.md
Labels: sync

#748 Pulling refs/heads/main into main
  admin/subscription-usage/dpm-usage.rst
Labels: sync

#749 Pulling refs/heads/main into main
  gdi/monitors-hosts/jenkins.md
Labels: sync

#750 Pulling refs/heads/main into main
  gdi/monitors-hosts/jenkins.md
Labels: sync

#751 Pulling refs/heads/main into main
  gdi/monitors-databases/hadoopjmx.md
  gdi/monitors-databases/sql.md
  gdi/monitors-hosts/coredns.md
  gdi/monitors-hosts/php-fpm.md
  gdi/monitors-hosts/systemd.md
  gdi/monitors-languages/genericjmx.md
  gdi/monitors-monitoring/cgroups.md
  gdi/monitors-monitoring/prometheus-exporter.md
  gdi/monitors-monitoring/prometheus-nginx-ingress.md
  gdi/monitors-monitoring/prometheus-velero.md
  gdi/monitors-network/snmp.md
Labels: sync

#752 Pulling refs/heads/main into main
  gdi/get-data-in/application/otel-dotnet/configuration/advanced-dotnet-configuration.rst
  gdi/get-data-in/application/otel-dotnet/dotnet-requirements.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
Labels: sync

#753 Pulling refs/heads/main into main
  infrastructure/network-explorer/network-explorer-setup.rst
Labels: sync

#754 Pulling refs/heads/main into main
  apm/intro-to-apm.rst
Labels: sync

#755 Pulling refs/heads/main into main
  .github/workflows/check-links.yml
  Makefile
Labels: sync

#756 Pulling refs/heads/main into main
  apm/set-up-apm/sensitive-data-controls.rst
Labels: sync

#757 Pulling refs/heads/main into main
  gdi/get-data-in/rum/android/install-rum-android.rst
  gdi/get-data-in/rum/browser/install-rum-browser.rst
  gdi/get-data-in/rum/browser/rum-browser-data-model.rst
  gdi/get-data-in/rum/ios/install-rum-ios.rst
Labels: sync

#758 Pulling refs/heads/main into main
  gdi/opentelemetry/components.rst
Labels: sync

#759 Update README.md
  README.md
Labels: internal, test

#760 Pulling refs/heads/main into main
  gdi/opentelemetry/install-linux-manual.rst
  gdi/opentelemetry/install-windows-manual.rst
Labels: sync, internal

#761 Pulling refs/heads/main into main
  admin/SSO/sso-about.rst
  admin/authentication-tokens/manage-usage.rst
  gdi/monitors-gitlab/gitlab.md
  gdi/monitors-network/aws-appmesh.md
  gdi/monitors-orchestration/openshift-cluster.md
  gdi/opentelemetry/deployments/deployments-linux-puppet.rst
  incident-intelligence/respond-manage-incidents/snow-integration.rst
  infrastructure/network-explorer/network-explorer-troubleshoot.rst
  synthetics/browser-test/browser-test-metrics.rst
  synthetics/synth-metrics.rst
Labels: sync, internal

#762 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-prereqs.rst
  gdi/get-data-in/connect/aws/aws-wizardconfig.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  infrastructure/monitor/aws-infra-monitor.rst
Labels: sync, internal

#763 Pulling refs/heads/main into main
  gdi/index.rst
  gdi/opentelemetry/smart-agent-migration-to-otel-collector.rst
  gdi/smart-agent/smart-agent-commands.rst
  gdi/smart-agent/smart-agent-intro.rst
  gdi/smart-agent/smart-agent-resources.rst
Labels: sync, internal

#764 Pulling refs/heads/main into main
  gdi/get-data-in/rum/browser/rum-browser-data-model.rst
  rum/rum-terminology-concepts.rst
Labels: sync, internal
