Repository splunk/public-o11y-docs, pull requests merged in 2023-10, with the labels that each got.

#967 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/get-awstoc.rst
  gdi/private-connectivity/aws-privatelink.rst
  gdi/private-connectivity/private-connectivity-landing.rst
  index.rst
Labels: sync, internal

#968 Pulling refs/heads/main into main
  admin/authentication/SSO/sso-GeneralSAML.rst
Labels: sync, internal

#969 Pulling refs/heads/main into main
  gdi/opentelemetry/components/logging-exporter.rst
Labels: sync, internal

#971 Pulling refs/heads/main into main
  apm/span-tags/metricsets.rst
Labels: sync, internal

#972 Pulling refs/heads/main into main
  gdi/get-data-in/application/python/configuration/advanced-python-otel-configuration.rst
  gdi/get-data-in/application/python/configuration/python-otel-metrics.rst
  gdi/get-data-in/application/python/get-started.rst
  gdi/get-data-in/application/python/instrumentation/instrument-python-application.rst
  gdi/get-data-in/application/python/splunk-python-otel-distribution.rst
Labels: sync, internal

#974 .NET OTel Auto - fix Logs instrumentations table
  gdi/get-data-in/application/otel-dotnet/dotnet-requirements.rst
Labels: external

#973 Pulling refs/heads/main into main
  admin/references/supported-browsers.rst
  gdi/opentelemetry/collector-how-to.rst
  gdi/opentelemetry/configure-the-collector.rst
  gdi/opentelemetry/data-processing.rst
  gdi/opentelemetry/opentelemetry.rst
Labels: sync, internal

#975 Pulling refs/heads/main into main
  _images/apm/spans-traces/service-centric-view-endpoints.png
  _images/apm/spans-traces/service-centric-view-infra-metrics.png
  _images/apm/spans-traces/service-centric-view-logs.png
  _images/apm/spans-traces/service-centric-view-overview.png
  _static/signalfx-alabaster.css
  _templates/banner.html
  admin/org-metrics.rst
  apm/apm-spans-traces/service-centric-views.rst
  gdi/requirements.rst
  get-started/service-description.rst
  get-started/welcome.rst
  index.rst
  metrics-and-metadata/metrics-dimensions-mts.rst
  synthetics/api-test/api-test-metrics.rst
  synthetics/api-test/api-test-results.rst
  synthetics/api-test/api-test.rst
  synthetics/api-test/set-up-api-test.rst
  synthetics/browser-test/browser-test-metrics.rst
  synthetics/browser-test/browser-test-results.rst
  synthetics/browser-test/browser-test.rst
  synthetics/browser-test/set-up-browser-test.rst
  synthetics/browser-test/set-up-transactional-browser-test.rst
  synthetics/intro-synthetics.rst
  synthetics/key-concepts.rst
  synthetics/set-up-synthetics/set-up-synthetics.rst
  synthetics/synth-scenarios/api-test-scenario.rst
  synthetics/synth-scenarios/browser-test-scenario.rst
  synthetics/synth-scenarios/synth-landing.rst
  synthetics/synth-scenarios/uptime-test-scenario.rst
  synthetics/test-config/built-in-variables.rst
  synthetics/test-config/global-variables.rst
  synthetics/test-config/private-locations.rst
  synthetics/test-config/public-locations.rst
  synthetics/test-config/rum-synth.rst
  synthetics/test-config/synth-alerts.rst
  synthetics/test-config/synth-configure-app.rst
  synthetics/test-config/test-config.rst
  synthetics/test-config/try-now.rst
  synthetics/uptime-test/set-up-uptime-test.rst
  synthetics/uptime-test/uptime-test-results.rst
  synthetics/uptime-test/uptime-test.rst
Labels: sync, internal

#976 Pulling refs/heads/main into main
  apm/apm-spans-traces/service-centric-views.rst
Labels: sync, internal

#977 Pulling refs/heads/main into main
  README.md
  gdi/opentelemetry/configure-the-collector.rst
  gdi/opentelemetry/metrics-internal-collector.rst
  gdi/opentelemetry/metrics-ootb-k8s.rst
Labels: sync, internal

#978 Pulling refs/heads/main into main
  admin/org-metrics.rst
  admin/subscription-usage/parent-child-orgs.rst
  gdi/opentelemetry/collector-how-to.rst
  infrastructure/network-explorer/network-explorer-setup.rst
Labels: sync, internal

#979 Pulling refs/heads/main into main
  gdi/get-data-in/rum/rum-instrumentation.rst
  metrics-and-metadata/metrics-dimensions-mts.rst
Labels: sync, internal

#980 Pulling refs/heads/main into main
  _includes/report-issue.rst
  gdi/private-connectivity/aws-privatelink.rst
Labels: sync, internal

#981 Update Synthetics locations to include au0/jp0/us0 and add Local Zones
  synthetics/test-config/au0-public-locations.csv
  synthetics/test-config/eu-public-locations.csv
  synthetics/test-config/eu0-public-locations.csv
  synthetics/test-config/jp0-public-locations.csv
  synthetics/test-config/public-locations.rst
  synthetics/test-config/us0-public-locations.csv
  synthetics/test-config/us1-public-locations.csv
Labels: external, stop-alert

#982 Pulling refs/heads/main into main
  apm/apm-spans-traces/service-centric-views.rst
Labels: sync, internal

#983 Pulling refs/heads/main into main
  metrics-and-metadata/view-data-events.rst
Labels: sync, internal

#984 Pulling refs/heads/main into main
  requirements.txt
Labels: sync

#985 Update runner -> runs in Private Location queue purging
  synthetics/test-config/private-locations.rst
Labels: external

#986 Pulling refs/heads/main into main
  _includes/admin/roles_alerts_detectors.rst
  _includes/admin/roles_apm.rst
  _includes/admin/roles_data_configuration.rst
  _includes/admin/roles_help_support.rst
  _includes/admin/roles_log_observer.rst
  _includes/admin/roles_mpm.rst
  _includes/admin/roles_navigation.rst
  _includes/admin/rum-roles-caps.rst
  _includes/admin/synth-roles-caps.rst
  _includes/private-preview.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-operator.rst
  metrics-and-metadata/metric-names.rst
  private-preview/rbac/roles-and-capabilities-about.rst
  private-preview/rbac/roles-and-capabilities-table.rst
  private-preview/rbac/users-assign-roles.rst
Labels: sync, internal

#987 Pulling refs/heads/main into main
  _static/customjs.js
  _templates/layout.html
  _templates/search.html
  gdi/opentelemetry/components/kubernetes-cluster-receiver.rst
  gdi/opentelemetry/components/oracledb-receiver.rst
  gdi/opentelemetry/components/otlp-exporter.rst
  gdi/opentelemetry/components/otlphttp-exporter.rst
  get-started/service-description.rst
Labels: sync, internal

#989 Pulling refs/heads/main into main
  _includes/metric-categories.rst
  apm/span-tags/cmms.rst
  apm/span-tags/metricsets.rst
  gdi/opentelemetry/deployments/deployments-nomad.rst
  gdi/opentelemetry/install-linux-manual.rst
  infrastructure/metrics-pipeline/metrics-usage-report.rst
Labels: sync

#990 Pulling refs/heads/main into main
  infrastructure/dpm-retention.rst
  infrastructure/retention.rst
Labels: sync

#991 Pulling refs/heads/main into main
  _images/splunkplatform/Synthetics_test.png
  _images/splunkplatform/code_version.png
  _images/splunkplatform/glass_table-close-up.png
  _images/splunkplatform/glass_table.png
  _images/splunkplatform/service_map.png
  _images/splunkplatform/synthetics2apm.png
  _images/splunkplatform/synthetics_recentrun.png
  _images/splunkplatform/synthetics_video.png
  _includes/admin/roles_alerts_detectors.rst
  _includes/admin/roles_apm.rst
  _includes/admin/roles_data_configuration.rst
  _includes/admin/roles_help_support.rst
  _includes/admin/roles_log_observer.rst
  _includes/admin/roles_mpm.rst
  _includes/admin/roles_navigation.rst
  _includes/admin/roles_navs_dashbds.rst
  _includes/admin/roles_navs_dashbds1.rst
  _includes/admin/rum-roles-caps.rst
  _includes/admin/synth-roles-caps.rst
  admin/user-management/roles/roles-and-capabilities-table.rst
  gdi/opentelemetry/components/host-metrics-receiver.rst
  gdi/private-connectivity/aws-privatelink.rst
  get-started/scenarios/scenario-cross.rst
  index.rst
  logs/forward-logs.rst
  private-preview/rbac/roles-and-capabilities-about.rst
  private-preview/rbac/roles-and-capabilities-table.rst
  splunkplatform/practice-reliability/slis.rst
  splunkplatform/practice-reliability/splunkplatform-landing.rst
  splunkplatform/scenarios/integration-scenario-landing.rst
  splunkplatform/scenarios/integration-scenario1.rst
  synthetics/test-config/try-now.rst
Labels: sync

#992 Pulling refs/heads/main into main
  gdi/get-data-in/connect/gcp/gcp.rst
Labels: sync

#993 Update filesystems.rst
  gdi/monitors-hosts/filesystems.rst
Labels: external

#994 Update install-k8s.rst
  gdi/opentelemetry/install-k8s.rst
Labels: external, stop-alert

#996 clarify which request to explore in APM
  splunkplatform/scenarios/integration-scenario1.rst
Labels: external, stop-alert

#998 SYN-3238: Update certificates section to be more clear
  synthetics/test-config/private-locations.rst
Labels: external, stop-alert

#997 Pulling refs/heads/main into main
  admin/authentication/SSO/sso-GeneralSAML.rst
  admin/authentication/SSO/sso-Okta.rst
  admin/authentication/SSO/sso-PingOne.rst
Labels: sync

#1000 Update Synthetics Public Locations with information about AWS Local Zones
  synthetics/test-config/public-locations.rst
Labels: external, stop-alert

#1002 Pulling refs/heads/main into main
  _images/logs/lo-openinsplunk.png
  _includes/collector-components.rst
  _includes/logs/query-logs.rst
  _templates/404.html
  gdi/get-data-in/compute/compute.rst
  gdi/monitors-orchestration/openshift-cluster.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/configure-the-collector-ootb.rst
  gdi/opentelemetry/install-the-collector.rst
  gdi/opentelemetry/opentelemetry.rst
  gdi/opentelemetry/resources.rst
  infrastructure/monitor/aws.rst
  logs/keyword.rst
  logs/lo-connect-landing.rst
  logs/log-observer-landing.rst
  logs/open-logs-splunk.rst
  splunkplatform/practice-reliability/collaboration.rst
  splunkplatform/practice-reliability/incident-response.rst
  splunkplatform/practice-reliability/slis.rst
  splunkplatform/practice-reliability/splunkplatform-landing.rst
Labels: sync

#1003 Pulling refs/heads/main into main
  apm/profiling/intro-profiling.rst
Labels: sync

#1005 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-how-to.rst
  gdi/opentelemetry/kubernetes-config-logs.rst
  get-started/scenario-landing.rst
  splunkplatform/scenarios/integration-scenario1.rst
Labels: sync

#1006 Pulling refs/heads/main into main
  _includes/gdi/processor-architecture-native.rst
  _includes/gdi/processor-architecture-subprocess.rst
  gdi/get-data-in/application/java/instrumentation/instrument-java-application.rst
  gdi/opentelemetry/collector-architecture.rst
  gdi/opentelemetry/components/smartagent-receiver.rst
Labels: sync

#1007 Pulling refs/heads/main into main
  gdi/opentelemetry/deployments/deployments-fargate.rst
  gdi/opentelemetry/sizing.rst
Labels: sync

#1009 Pulling refs/heads/main into main
  apm/span-tags/index-span-tags.rst
  apm/span-tags/migrate-apm-custom-reporting.rst
  apm/span-tags/span-tags.rst
Labels: sync

#1010 Pulling refs/heads/main into main
  admin/references/system-limits/sys-limits-apm.rst
Labels: sync

#1011 Pulling refs/heads/main into main
  _images/gdi/dashboard-group-preview.png
  _images/gdi/instrumenting-preview.png
  _images/infrastructure/images-k8s-infrastructure-tutorial/k8s-activate-detector.png
  _images/infrastructure/images-k8s-infrastructure-tutorial/k8s-alert.png
  _images/infrastructure/images-k8s-infrastructure-tutorial/k8s-chart-actions.png
  _images/infrastructure/images-k8s-infrastructure-tutorial/k8s-containers.gif
  _images/infrastructure/images-k8s-infrastructure-tutorial/k8s-dashboard.gif
  _images/infrastructure/images-k8s-infrastructure-tutorial/k8s-data-ingestion.png
  _images/infrastructure/images-k8s-infrastructure-tutorial/k8s-install-collector.png
  _images/infrastructure/images-k8s-infrastructure-tutorial/k8s-integration-commands.png
  _images/infrastructure/images-k8s-infrastructure-tutorial/k8s-new-detector.png
  _images/infrastructure/images-k8s-infrastructure-tutorial/k8s-setup-wizard-new.png
  _images/infrastructure/linux-setup-wizard.png
  _images/infrastructure/linux-wizard-access.png
  index.rst
  infrastructure/k8s-infrastructure-tutorial/about-k8s-tutorial.rst
  infrastructure/k8s-infrastructure-tutorial/get-started-k8s-imm.rst
  infrastructure/k8s-infrastructure-tutorial/k8s-activate-detector.rst
  infrastructure/k8s-infrastructure-tutorial/k8s-additional-resources.rst
  infrastructure/k8s-infrastructure-tutorial/k8s-install-otel.rst
  infrastructure/k8s-infrastructure-tutorial/k8s-monitor-with-navigators.rst
  infrastructure/quickstart-imm.rst
Labels: sync

#1008 Go: No support for sending metrics directly to o11y
  gdi/get-data-in/application/go/instrumentation/instrument-go-application.rst
Labels: external, stop-alert

#1013 Pulling refs/heads/main into main
  admin/authentication/SSO/sso-ADSF.rst
  admin/authentication/SSO/sso-AzureAD.rst
  admin/authentication/SSO/sso-about.rst
  admin/authentication/SSO/sso.rst
  gdi/get-data-in/connect/azure/azure-logs-ingestion.rst
  gdi/get-data-in/connect/azure/azure.rst
  gdi/get-data-in/integrations.rst
Labels: sync

#1014 Pulling refs/heads/main into main
  gdi/get-data-in/compute/k8s.rst
  gdi/opentelemetry/install-k8s.rst
Labels: sync

#1015 Pulling refs/heads/main into main
  gdi/get-data-in/application/otel-dotnet/dotnet-requirements.rst
  gdi/get-data-in/serverless/aws/otel-lambda-layer/advanced-configuration.rst
Labels: sync

#1017 Pulling refs/heads/main into main
  admin/subscription-usage/analyze-apm-billing-usage.rst
Labels: sync

#1018 Pulling refs/heads/main into main
  gdi/opentelemetry/deployments/deployments-fargate.rst
Labels: sync

#1019 Pulling refs/heads/main into main
  _images/gdi/aws-console-splunk2.png
  gdi/get-data-in/connect/aws/aws-console-ms.rst
Labels: sync

#1020 Pulling refs/heads/main into main
  gdi/opentelemetry/metrics-ootb-k8s.rst
  gdi/opentelemetry/opentelemetry.rst
  logs/scp.rst
  synthetics/test-config/private-locations.rst
Labels: sync

#1023 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-with-the-uf.rst
  gdi/opentelemetry/configure-the-collector.rst
  gdi/opentelemetry/kubernetes-config-logs.rst
  gdi/opentelemetry/opentelemetry.rst
Labels: sync

#1024 Pulling refs/heads/main into main
  gdi/opentelemetry/components/host-metrics-receiver.rst
Labels: sync

#1025 Pulling refs/heads/main into main
  gdi/opentelemetry/components/kubernetes-cluster-receiver.rst
Labels: sync

#1027 Pulling refs/heads/main into main
  _static/jsonpull-splunk.js
  gdi/get-data-in/connect/aws/aws-connect-ms.rst
  gdi/get-data-in/connect/aws/aws-connect-polling.rst
  gdi/get-data-in/connect/aws/aws-console-ms.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
Labels: sync

#1028 Pulling refs/heads/main into main
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/opentelemetry.rst
  index.rst
Labels: sync

#1029 Pulling refs/heads/main into main
  gdi/opentelemetry/configure-the-collector-ootb.rst
  gdi/opentelemetry/install-linux-manual.rst
  splunkplatform/unified-id/unified-identity.rst
Labels: sync

#1030 Update advanced-java-otel-configuration.rst
  gdi/get-data-in/application/java/configuration/advanced-java-otel-configuration.rst
Labels: external, stop-alert

#1032 remove hard coded username from code example
  gdi/monitors-databases/microsoft-sql-server.rst
Labels: external, stop-alert

#1033 Update instrument-php-application.rst
  gdi/get-data-in/application/php/instrumentation/instrument-php-application.rst
Labels: external

#1035 Browser RUM configuration: fix typo
  gdi/get-data-in/rum/browser/configure-rum-browser-instrumentation.rst
Labels: external, stop-alert
