Repository splunk/public-o11y-docs, pull requests merged in 2023-12, with the labels that each got.

#1078 Remove collector uninstall via WMI
  gdi/opentelemetry/uninstall-the-collector.rst
Labels: external, stop-alert

#1079 Pulling refs/heads/main into main
  synthetics/test-config/public-locations.rst
Labels: sync

#1080 Pulling refs/heads/main into main
  _images/get-started/trial-exp.png
  _images/get-started/trial1.png
  _includes/admin/synth-roles-caps.rst
  _includes/admin/synth-roles-caps1.rst
  alerts-detectors-notifications/autodetect/autodetect-list.rst
  gdi/opentelemetry/components/mongodb-atlas-receiver.rst
  gdi/other-ingestion-methods/upstream-collector.rst
  get-started/o11y-trial.rst
  index.rst
  logs/scp.rst
Labels: sync

#1082 Pulling refs/heads/main into main
  get-started/scenario-landing.rst
  splunkplatform/scenarios/integration-scenario-landing.rst
Labels: sync

#1083 Pulling refs/heads/main into main
  gdi/opentelemetry/smart-agent-migration-process.rst
  gdi/opentelemetry/translation-tool.rst
Labels: sync

#1084 Pulling refs/heads/main into main
  apm/profiling/get-data-in-profiling.rst
  apm/profiling/intro-profiling.rst
  gdi/get-data-in/application/java/configuration/advanced-java-otel-configuration.rst
  gdi/get-data-in/application/java/instrumentation/instrument-java-application.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-nodejs-linux.rst
Labels: sync

#1085 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-console-ms.rst
  gdi/get-data-in/serverless/azure/instrument-azure-functions.rst
Labels: sync

#1087 Pulling refs/heads/main into main
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-k8s.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-nodejs-k8s.rst
  gdi/opentelemetry/install-k8s-addon-eks.rst
  gdi/opentelemetry/install-k8s.rst
  gdi/opentelemetry/install-the-collector.rst
Labels: sync

#1088 Add msi_public_properties param to Windows install
  gdi/opentelemetry/install-windows.rst
Labels: external, stop-alert

#1089 Pulling refs/heads/main into main
  gdi/get-data-in/serverless/aws/dotnet-lambdas.rst
Labels: sync

#1073 Observability MTPE to JA - 5 files
  locales/ja_JA/LC_MESSAGES/_includes.mo
  locales/ja_JA/LC_MESSAGES/_includes.po
  locales/ja_JA/LC_MESSAGES/get-started.mo
  locales/ja_JA/LC_MESSAGES/get-started.po
  locales/ja_JA/LC_MESSAGES/index.mo
  locales/ja_JA/LC_MESSAGES/index.po
  locales/ja_JA/LC_MESSAGES/references.mo
  locales/ja_JA/LC_MESSAGES/references.po
  locales/ja_JA/LC_MESSAGES/splunkplatform.mo
  locales/ja_JA/LC_MESSAGES/splunkplatform.po
Labels: external, stop-alert

#1090 Pulling refs/heads/main into main
  _includes/application-receiver-table.rst
  gdi/monitors-databases/postgresql.rst
  gdi/monitors-hosts/collectd-df.rst
  gdi/monitors-hosts/disk.rst
  gdi/monitors-hosts/host-processload.rst
  gdi/monitors-hosts/interface.rst
  gdi/monitors-monitoring/signalfx-forwarder.rst
  gdi/monitors-prometheus/prometheus-generic.rst
  gdi/opentelemetry/components/attributes-processor.rst
  gdi/opentelemetry/components/filter-processor.rst
  gdi/opentelemetry/components/logging-exporter.rst
  gdi/opentelemetry/components/smartagent-receiver.rst
  gdi/opentelemetry/components/transform-processor.rst
  gdi/opentelemetry/configure-the-collector-ootb.rst
  gdi/opentelemetry/exposed-endpoints.rst
  gdi/opentelemetry/smart-agent-migration-monitors.rst
  gdi/opentelemetry/smart-agent-migration-process.rst
  gdi/smart-agent/smart-agent-resources.rst
Labels: sync

#1091 Pulling refs/heads/main into main
  gdi/get-data-in/application/python/instrumentation/instrument-python-frameworks.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/jmx-receiver.rst
Labels: sync

#1092 Pulling refs/heads/main into main
  gdi/opentelemetry/deployments/deployments-chef.rst
  gdi/opentelemetry/deployments/deployments-ecs-ec2.rst
  gdi/opentelemetry/deployments/deployments-fargate-java.rst
  gdi/opentelemetry/deployments/deployments-fargate.rst
  gdi/opentelemetry/deployments/deployments-linux-ansible.rst
  gdi/opentelemetry/deployments/deployments-linux-puppet.rst
  gdi/opentelemetry/deployments/deployments-nomad.rst
  gdi/opentelemetry/deployments/deployments-pivotal-cloudfoundry.rst
  gdi/opentelemetry/deployments/deployments-salt.rst
  gdi/opentelemetry/deployments/deployments-windows-ansible.rst
  gdi/opentelemetry/deployments/deployments-windows-puppet.rst
  gdi/opentelemetry/deployments/otel-deployments.rst
Labels: sync

#1093 Update install-k8s-addon-eks.rst
  gdi/opentelemetry/install-k8s-addon-eks.rst
Labels: external, stop-alert

#1094 Pulling refs/heads/main into main
  _includes/requirements/ruby.rst
  gdi/monitors-databases/sap-hana.rst
Labels: sync

#1095 Pulling refs/heads/main into main
  gdi/get-data-in/application/python/instrumentation/connect-traces-logs.rst
Labels: sync

#1097 Patch 3
  gdi/opentelemetry/install-k8s-addon-eks.rst
  gdi/opentelemetry/install-the-collector.rst
Labels: gdi, collector, external

#1098 Pulling refs/heads/main into main
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/otlp-exporter.rst
  gdi/opentelemetry/components/otlp-receiver.rst
  gdi/opentelemetry/configure-the-collector-ootb.rst
Labels: sync

#1099 Pulling refs/heads/main into main
  gdi/opentelemetry/components/simple-prometheus-receiver.rst
Labels: sync

#1100 Update advanced-go-otel-configuration.rst
  gdi/get-data-in/application/go/configuration/advanced-go-otel-configuration.rst
Labels: external, stop-alert

#1102 Pulling refs/heads/main into main
  infrastructure/monitor/aws-infra-costs.rst
  infrastructure/monitor/aws-infra-import.rst
  infrastructure/monitor/aws-infra-monitor.rst
  infrastructure/monitor/aws.rst
Labels: sync

#1103 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-logs.rst
  gdi/get-data-in/connect/azure/azure-logs-ingestion.rst
  gdi/get-data-in/connect/gcp/gcp-logs.rst
Labels: sync

#1104 Pulling refs/heads/main into main
  gdi/monitors-databases/apache-spark.rst
Labels: sync

#1106 Pulling refs/heads/main into main
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/batch-processor.rst
  gdi/opentelemetry/components/fluentd-receiver.rst
  gdi/opentelemetry/components/health-check-extension.rst
  gdi/opentelemetry/components/host-metrics-receiver.rst
  gdi/opentelemetry/components/jaeger-receiver.rst
  gdi/opentelemetry/components/memory-ballast-extension.rst
  gdi/opentelemetry/components/memory-limiter-processor.rst
  gdi/opentelemetry/components/otlp-exporter.rst
  gdi/opentelemetry/components/otlp-receiver.rst
  gdi/opentelemetry/components/prometheus-receiver.rst
  gdi/opentelemetry/components/resourcedetection-processor.rst
  gdi/opentelemetry/components/signalfx-exporter.rst
  gdi/opentelemetry/components/signalfx-receiver.rst
  gdi/opentelemetry/components/splunk-apm-exporter.rst
  gdi/opentelemetry/components/splunk-hec-exporter.rst
  gdi/opentelemetry/components/zipkin-receiver.rst
  gdi/opentelemetry/components/zpages-extension.rst
  gdi/opentelemetry/configure-the-collector-ootb.rst
Labels: sync

#1105 MTPE Japanese Observability guide - 3 more files post-edited
  locales/ja_JA/LC_MESSAGES/analytics.mo
  locales/ja_JA/LC_MESSAGES/analytics.po
  locales/ja_JA/LC_MESSAGES/incident-intelligence.mo
  locales/ja_JA/LC_MESSAGES/incident-intelligence.po
  locales/ja_JA/LC_MESSAGES/metrics-and-metadata.mo
  locales/ja_JA/LC_MESSAGES/metrics-and-metadata.po
Labels: external, stop-alert

#1107 Pulling refs/heads/main into main
  gdi/opentelemetry/components/batch-processor.rst
  gdi/opentelemetry/components/filelog-receiver.rst
  gdi/opentelemetry/components/fluentd-receiver.rst
  gdi/opentelemetry/components/groupbyattrs-processor.rst
  gdi/opentelemetry/components/health-check-extension.rst
  gdi/opentelemetry/components/jmx-receiver.rst
  gdi/opentelemetry/components/kubelet-stats-receiver.rst
  gdi/opentelemetry/components/kubernetes-attributes-processor.rst
  gdi/opentelemetry/components/memory-ballast-extension.rst
  gdi/opentelemetry/components/otlp-exporter.rst
  gdi/opentelemetry/components/otlphttp-exporter.rst
  gdi/opentelemetry/components/prometheus-receiver.rst
  gdi/opentelemetry/components/resourcedetection-processor.rst
  gdi/opentelemetry/components/signalfx-receiver.rst
  gdi/opentelemetry/components/splunk-apm-exporter.rst
  gdi/opentelemetry/components/splunk-hec-exporter.rst
  gdi/opentelemetry/components/splunk-hec-receiver.rst
  gdi/opentelemetry/components/syslog-receiver.rst
  gdi/opentelemetry/components/tcp-receiver.rst
  gdi/opentelemetry/components/transform-processor.rst
  gdi/opentelemetry/components/udp-receiver.rst
  gdi/opentelemetry/components/zipkin-receiver.rst
  gdi/opentelemetry/components/zpages-extension.rst
Labels: sync

#1108 Pulling refs/heads/main into main
  infrastructure/monitor/aws-infra-import.rst
  infrastructure/monitor/aws.rst
Labels: sync

#1110 Pulling refs/heads/main into main
  _includes/gdi/aws-unsupported-chars.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  infrastructure/monitor/aws-infra-import.rst
Labels: sync
