Repository splunk/public-o11y-docs, pull requests merged in 2024-11, with the labels that each got.

#1582 Pulling refs/heads/main into main
  _includes/activate-deactivate-native-metrics.rst
  _static/signalfx-alabaster.css
  admin/subscription-usage/monitor-imm-billing-usage.rst
  apm/apm-spans-traces/apm-errors.rst
Labels: sync

#1584 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-addon/collector-addon-configure-instance.rst
  gdi/opentelemetry/collector-addon/collector-addon-install.rst
  gdi/opentelemetry/collector-addon/collector-addon-intro.rst
  gdi/opentelemetry/collector-addon/collector-addon-upgrade.rst
Labels: sync

#1585 Pulling refs/heads/main into main
  apm/apm-spans-traces/span-formats.rst
  gdi/monitors-databases/postgresql.rst
  gdi/monitors-hosts/filesystems.rst
  gdi/monitors-network/net-io.rst
  gdi/smart-agent/smart-agent-commands.rst
  gdi/smart-agent/smart-agent-intro.rst
  gdi/smart-agent/smart-agent-resources.rst
  index.rst
  infrastructure/monitor/azure.rst
Labels: sync

#1587 Added password requirements
  admin/user-management/users/personal-info.rst
Labels: external, stop-alert

#1586 Pulling refs/heads/main into main
  Dockerfile
  admin/authentication/authentication-tokens/org-tokens.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-advanced.rst
  gdi/opentelemetry/components/redis-receiver.rst
  gdi/opentelemetry/components/vcenter-receiver.rst
  gdi/opentelemetry/discovery-mode.rst
  synthetics/test-config/private-locations.rst
Labels: sync

#1588 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-addon/collector-addon-intro.rst
  gdi/opentelemetry/collector-addon/collector-addon-release-notes.rst
Labels: sync

#1589 Pulling refs/heads/main into main
  gdi/monitors-orchestration/kubernetes-cluster.rst
  gdi/opentelemetry/smart-agent/legacy-otel-mappings.rst
  gdi/opentelemetry/smart-agent/smart-agent-migration-monitors.rst
  gdi/opentelemetry/smart-agent/smart-agent-migration-process.rst
  gdi/opentelemetry/smart-agent/smart-agent-migration-to-otel-collector.rst
Labels: sync

#1590 Update aws-ts-metric-streams.rst
  gdi/get-data-in/connect/aws/aws-ts-metric-streams.rst
Labels: external, stop-alert

#1593 Update azure.rst
  gdi/get-data-in/connect/azure/azure.rst
Labels: external

#1591 Pulling refs/heads/main into main
  _images/data-visualization/charts/change-histogram-function.png
Labels: sync

#1594 Pulling refs/heads/main into main
  apm/apm-spans-traces/traces-spans.rst
  apm/key-concepts.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  gdi/opentelemetry/components/kubernetes-objects-receiver.rst
  sp-oncall/notifications/notification-types.rst
Labels: sync

#1598 Update aws-prereqs.rst
  gdi/get-data-in/connect/aws/aws-prereqs.rst
Labels: external, stop-alert

#1599 Adjust docs after splunk-otel-dotnet 1.8.0
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
Labels: gdi, instrumentation, external, stop-alert

#1601 Pulling refs/heads/main into main
  _images/images-metrics/usage-analytics-example-profile.png
  _images/images-metrics/usage-analytics-home-page.png
  _images/synthetics/Synth-built-in-dashboards.png
  _images/synthetics/ootb-dashboard-modal.png
  _includes/metric-categories.rst
  _includes/metric-classes.rst
  _includes/synthetics/chrome-flags.rst
  _includes/zero-code-info.rst
  alerts-detectors-notifications/alerts-and-detectors/create-detectors-for-alerts.rst
  apm/span-tags/tag-spotlight.rst
  data-visualization/charts/chart-builder.rst
  gdi/get-data-in/application/application.rst
  gdi/get-data-in/application/go/instrumentation/instrument-go-application.rst
  gdi/get-data-in/application/java/instrumentation/instrument-java-application.rst
  gdi/get-data-in/application/nodejs/instrumentation/instrument-nodejs-application.rst
  gdi/get-data-in/application/otel-dotnet/get-started.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/dotnet-pre-checks.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/manual-dotnet-instrumentation.rst
  gdi/get-data-in/application/otel-dotnet/sfx/sfx-instrumentation.rst
  gdi/get-data-in/application/php/get-started.rst
  gdi/get-data-in/application/php/instrument-php-application.rst
  gdi/get-data-in/application/php/sfx/sfx-instrumentation.rst
  gdi/get-data-in/application/python/instrumentation/instrument-python-application.rst
  gdi/get-data-in/application/python/instrumentation/instrument-python-frameworks.rst
  gdi/get-data-in/application/ruby/instrument-ruby.rst
  gdi/get-data-in/application/zero-code-overview.rst
  gdi/get-data-in/connect/aws/aws-connect-polling.rst
  gdi/get-data-in/connect/aws/aws-recommended-stats.rst
  gdi/get-data-in/connect/gcp/gcp-connect.rst
  gdi/get-data-in/connect/gcp/gcp-prereqs.rst
  gdi/get-data-in/connect/gcp/gcp.rst
  gdi/get-data-in/rum/browser/browser-rum-instrumentations.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-java-traces-tutorial/deploy-collector-k8s-java.rst
  gdi/opentelemetry/automatic-discovery/windows/windows-backend.rst
  gdi/opentelemetry/troubleshoot-logs.rst
  index.rst
  infrastructure/metrics-pipeline/metrics-pipeline-intro.rst
  infrastructure/metrics-pipeline/metrics-usage-report.rst
  metrics-and-metadata/metric-categories.rst
  metrics-and-metadata/metrics-landing.rst
  metrics-and-metadata/metrics-usage-analytics.rst
  metrics-and-metadata/search.rst
  references/glossary.rst
  splunkplatform/centralized-rbac.rst
  splunkplatform/unified-id/unified-identity.rst
  synthetics/api-test/api-test-results.rst
  synthetics/browser-test/browser-test-results.rst
  synthetics/browser-test/set-up-browser-test.rst
  synthetics/syn-ottb-dashboards.rst
  synthetics/test-kpis/test-kpis.rst
  synthetics/uptime-test/uptime-test-results.rst
Labels: sync

#1602 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-connect-polling.rst
Labels: sync

#1578 Add retention time period for session replay
  admin/references/data-retention.rst
Labels: external, stop-alert

#1604 Fix typo Update unified-identity.rst
  splunkplatform/unified-id/unified-identity.rst
Labels: external, stop-alert

#1606 Update deprecation-of-splunk-on-call-phone-notifications-to-china.rst
  sp-oncall/admin/get-started/deprecation-of-splunk-on-call-phone-notifications-to-china.rst
Labels: external, stop-alert

#1607 Pulling refs/heads/main into main
  _images/gdi/aws-ts-awsmanaged1.png
  _images/gdi/aws-ts-awsmanaged2.png
  _images/gdi/aws-ts-awsmanaged3.png
  _images/gdi/aws-ts-awsmanaged4.png
  gdi/get-data-in/connect/aws/aws-troubleshooting.rst
  gdi/get-data-in/connect/aws/aws-ts-metric-streams.rst
  gdi/get-data-in/connect/aws/aws-ts-ms-aws.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-logs.rst
  gdi/opentelemetry/collector-linux/linux-config-logs.rst
  gdi/opentelemetry/collector-windows/collector-windows-intro.rst
  gdi/opentelemetry/collector-windows/install-windows.rst
  gdi/opentelemetry/collector-windows/windows-config-logs.rst
  gdi/opentelemetry/troubleshoot-logs.rst
  gdi/requirements.rst
Labels: sync

#1608 Pulling refs/heads/main into main
  admin/subscription-usage/synthetics-usage.rst
  gdi/get-data-in/application/python/splunk-python-otel-distribution.rst
  logs/scp.rst
  splunkplatform/centralized-rbac.rst
Labels: sync

#1610 Update loadbalancing-exporter.rst
  gdi/opentelemetry/components/loadbalancing-exporter.rst
Labels: external, stop-alert

#1611 Pulling refs/heads/main into main
  admin/notif-services/microsoftteams.rst
Labels: sync

#1613 Pulling refs/heads/main into main
  gdi/opentelemetry/components/windowsperfcounters-receiver.rst
  metrics-and-metadata/metric-categories.rst
  metrics-and-metadata/metrics-usage-analytics.rst
Labels: sync

#1615 Pulling refs/heads/main into main
  gdi/opentelemetry/splunk-collector-troubleshooting.rst
  gdi/opentelemetry/troubleshoot-logs.rst
  gdi/opentelemetry/troubleshooting.rst
Labels: sync

#1616 Pulling refs/heads/main into main
  _includes/gdi/application-receiver-table.rst
  admin/notif-services/splunkplatform.rst
  gdi/integrations-list.rst
  gdi/monitors-prometheus/prometheus-generic.rst
  synthetics/test-config/global-variables.rst
Labels: sync

#1617 Pulling refs/heads/main into main
  gdi/integrations-list.rst
  gdi/monitoring.rst
  gdi/monitors-databases/exec-input.rst
  gdi/opentelemetry/otel-other/otel-other-landing.rst
  gdi/opentelemetry/otel-other/prometheus-generic.rst
  gdi/opentelemetry/otel-other/telegraf.rst
  gdi/prometheus.rst
Labels: sync

#1618 Pulling refs/heads/main into main
  _includes/gdi/auto-discovery-intro.rst
  gdi/opentelemetry/automatic-discovery/discovery-kubernetes.rst
  gdi/opentelemetry/automatic-discovery/discovery-linux.rst
  gdi/opentelemetry/automatic-discovery/discovery-windows.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-advanced-config.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-backend.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-java-traces-tutorial/about-k8s-java-traces-tutorial.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-java-traces-tutorial/k8s-java-view-apm.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-third-party.rst
  gdi/opentelemetry/automatic-discovery/linux/linux-advanced-config.rst
  gdi/opentelemetry/automatic-discovery/linux/linux-backend.rst
  gdi/opentelemetry/automatic-discovery/linux/linux-third-party.rst
  gdi/opentelemetry/automatic-discovery/windows/windows-backend.rst
  gdi/opentelemetry/deployments/deployments-ecs-ec2.rst
  gdi/opentelemetry/discovery-mode.rst
  gdi/opentelemetry/opentelemetry.rst
Labels: sync

#1619 Pulling refs/heads/main into main
  gdi/opentelemetry/automatic-discovery/k8s/k8s-java-traces-tutorial/about-k8s-java-traces-tutorial.rst
  gdi/opentelemetry/collector-kubernetes/install-k8s.rst
  gdi/opentelemetry/collector-linux/deployments-linux-ansible.rst
  gdi/opentelemetry/collector-linux/deployments-linux-salt.rst
  gdi/opentelemetry/collector-linux/install-linux-manual.rst
  gdi/opentelemetry/collector-linux/install-linux.rst
Labels: sync

#1620 Pulling refs/heads/main into main
  _includes/gdi/auto-discovery-intro.rst
  data-visualization/dashboards/dashboard-basics.rst
  gdi/opentelemetry/automatic-discovery/discovery-linux.rst
  gdi/opentelemetry/automatic-discovery/linux/linux-advanced-config.rst
  gdi/opentelemetry/collector-kubernetes/collector-kubernetes-intro.rst
  gdi/opentelemetry/collector-linux/collector-linux-intro.rst
  gdi/opentelemetry/collector-linux/install-linux.rst
  gdi/opentelemetry/collector-linux/linux-config.rst
  gdi/opentelemetry/collector-windows/collector-windows-intro.rst
  gdi/opentelemetry/discovery-mode.rst
Labels: sync
