Repository splunk/public-o11y-docs, pull requests merged in 2024-10, with the labels that each got.

#1554 Pulling refs/heads/main into main
  gdi/get-data-in/connect/gcp/gcp-connect.rst
  gdi/get-data-in/connect/gcp/gcp-prereqs.rst
  gdi/get-data-in/connect/gcp/gcp.rst
Labels: sync

#1555 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-advanced.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-helm-architecture.rst
Labels: sync

#1556 Update AWS Lambda instructions
  gdi/get-data-in/serverless/aws/otel-lambda-layer/instrumentation/dotnet-lambdas.rst
Labels: external, stop-alert

#1557 Pulling refs/heads/main into main
  _includes/gdi/otel-receivers-table.rst
  gdi/monitors-databases/apache-spark.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-receivers.rst
  gdi/opentelemetry/components/apache-spark-receiver.rst
Labels: sync

#1553 Fixed the highlighted line for the instrument change
  gdi/get-data-in/rum/browser/install-rum-browser.rst
Labels: external, stop-alert

#1559 Update mssql-server-receiver.rst
  gdi/opentelemetry/components/mssql-server-receiver.rst
Labels: external, stop-alert

#1561 Pulling refs/heads/main into main
  admin/notif-services/microsoftteams.rst
  admin/notif-services/opsgenie.rst
  admin/notif-services/slack.rst
  admin/notif-services/splunkoncall.rst
  gdi/opentelemetry/deployments/deployments-pivotal-cloudfoundry.rst
Labels: sync

#1562 Pulling refs/heads/main into main
  admin/notif-services/splunkplatform.rst
  admin/notif-services/webhook.rst
  gdi/get-data-in/application/cpp/get-started-cpp.rst
  gdi/get-data-in/application/go/get-started.rst
  gdi/get-data-in/application/java/get-started.rst
  gdi/get-data-in/application/nodejs/get-started.rst
  gdi/get-data-in/application/php/get-started.rst
  gdi/get-data-in/application/python/get-started.rst
  gdi/get-data-in/application/ruby/get-started-ruby.rst
  gdi/monitors-cloud/heroku.rst
  gdi/monitors-cloud/kong.rst
  gdi/monitors-cloudfoundry/cloudfoundry-firehose-nozzle.rst
  gdi/monitors-databases/microsoft-sql-server.rst
  gdi/monitors-databases/mongodb.rst
  gdi/monitors-databases/mysql.rst
  gdi/monitors-databases/postgresql.rst
  gdi/monitors-databases/redis.rst
  gdi/monitors-databases/sql.rst
  gdi/monitors-hosts/apache-httpserver.rst
  gdi/monitors-hosts/apache-tomcat.rst
  gdi/monitors-hosts/jenkins.rst
  gdi/monitors-hosts/kafka-consumer.rst
  gdi/monitors-hosts/kafka-producer.rst
  gdi/monitors-hosts/nginx.rst
  gdi/monitors-languages/expvar.rst
  gdi/monitors-messaging/rabbitmq.rst
  gdi/monitors-prometheus/prometheus-generic.rst
Labels: sync

#1563 Pulling refs/heads/main into main
  _includes/gdi/available-aws.rst
  admin/references/data-retention.rst
  gdi/get-data-in/connect/aws/aws-prereqs.rst
  infrastructure/metrics-pipeline/metrics-pipeline-intro.rst
Labels: sync

#1564 Pulling refs/heads/main into main
  gdi/get-data-in/application/span-attributes.rst
  gdi/monitors-cloud/kong.rst
  gdi/monitors-databases/mongodb.rst
  gdi/monitors-hosts/apache-tomcat.rst
  gdi/monitors-hosts/jenkins.rst
  gdi/monitors-hosts/kafka-consumer.rst
  gdi/monitors-hosts/kafka-producer.rst
  gdi/monitors-languages/expvar.rst
  gdi/monitors-network/statsd.rst
  gdi/opentelemetry/common-config/collector-common-config-auth.rst
  gdi/opentelemetry/common-config/collector-common-config-grcp.rst
  gdi/opentelemetry/tags.rst
  logs/LOconnect-troubleshoot.rst
Labels: sync

#1565 Pulling refs/heads/main into main
  _includes/gdi/available-aws.rst
  admin/references/data-retention.rst
  admin/subscription-usage/subscription-usage-overview.rst
  apm/db-query-perf/db-perf-troubleshooting.rst
  apm/profiling/get-data-in-profiling.rst
  data-visualization/dashboards/view-dashboards.rst
  gdi/get-data-in/connect/aws/aws-cloudformation.rst
  gdi/get-data-in/connect/aws/aws-logs.rst
  gdi/get-data-in/connect/aws/aws-post-install.rst
  gdi/get-data-in/connect/azure/azure-logs-ingestion.rst
  gdi/get-data-in/connect/gcp/gcp-logs.rst
  gdi/get-data-in/gdi-guide/apm/instrument-back-end.rst
  gdi/get-data-in/gdi-guide/infrastructure/send-server-cluster-data.rst
  gdi/opentelemetry/automatic-discovery/linux/linux-backend.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-logs.rst
  gdi/opentelemetry/collector-linux/linux-config-logs.rst
  gdi/opentelemetry/collector-windows/install-windows-msi.rst
  gdi/opentelemetry/collector-windows/install-windows.rst
  gdi/opentelemetry/components/fluentd-receiver.rst
  gdi/opentelemetry/components/splunk-hec-exporter.rst
  gdi/opentelemetry/install-the-collector.rst
  gdi/opentelemetry/opentelemetry.rst
  gdi/opentelemetry/smart-agent/smart-agent-migration-process.rst
  gdi/opentelemetry/splunk-collector-troubleshooting.rst
  get-started/o11y.rst
  logs/keyword.rst
Labels: sync

#1566 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-addon/collector-addon-configure.rst
  gdi/opentelemetry/collector-addon/collector-addon-install.rst
  gdi/opentelemetry/collector-addon/collector-addon-intro.rst
  gdi/opentelemetry/collector-addon/collector-addon-troubleshooting.rst
  gdi/opentelemetry/collector-linux/collector-linux-intro.rst
  gdi/opentelemetry/opentelemetry.rst
Labels: sync

#1567 Pulling refs/heads/main into main
  admin/references/organizations.rst
Labels: sync

#1568 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-how-to.rst
  gdi/opentelemetry/components/attributes-processor.rst
  gdi/opentelemetry/components/filter-processor.rst
  infrastructure/metrics-pipeline/metrics-usage-report.rst
Labels: sync

#1569 Pulling refs/heads/main into main
  gdi/monitors-gitlab/gitlab.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-advanced-config.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-backend.rst
Labels: sync

#1570 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-kubernetes/install-k8s.rst
Labels: sync

#1571 Pulling refs/heads/main into main
  _includes/collector-upgrade.rst
  gdi/opentelemetry/automatic-discovery/windows/windows-backend.rst
  gdi/opentelemetry/collector-windows/install-windows-msi.rst
Labels: sync

#1573 Pulling refs/heads/main into main
  _includes/logs/query-logs.rst
  gdi/monitors-languages/java-monitor.rst
  gdi/opentelemetry/collector-how-to.rst
  gdi/opentelemetry/collector-windows/install-windows-msi.rst
  infrastructure/retention.rst
  metrics-and-metadata/view-data-events.rst
  splunkplatform/unified-id/unified-identity.rst
  synthetics/test-config/private-locations.rst
Labels: sync

#1574 Update browser-test-metrics.rst
  synthetics/browser-test/browser-test-metrics.rst
Labels: external, stop-alert

#1576 Replace ecs-metadata with awsecscontainermetrics
  gdi/opentelemetry/deployments/deployments-ecs-ec2.rst
Labels: gdi, collector, external, stop-alert

#1577 Pulling refs/heads/main into main
  admin/authentication/authentication-tokens/org-tokens.rst
  admin/notif-services/servicenow.rst
  index.rst
  release-notes/2024-10-01-rn.rst
  release-notes/release-notes-overview.rst
  synthetics/api-test/api-test.rst
  synthetics/browser-test/browser-test-results.rst
  synthetics/browser-test/browser-test.rst
  synthetics/set-up-synthetics/set-up-synthetics.rst
  synthetics/syn-troubleshoot/syn-missing-alerts.rst
  synthetics/syn-troubleshoot/syn-troubleshoot.rst
  synthetics/test-config/synth-configure-app.rst
  synthetics/test-config/test-config.rst
  synthetics/uptime-test/uptime-test.rst
Labels: sync

#1579 Pulling refs/heads/main into main
  _includes/gdi/application-receiver-table-deprecated.rst
  _includes/gdi/application-receiver-table.rst
  _includes/gdi/otel-receivers-table.rst
  _includes/gdi/processor-architecture-native.rst
  _includes/gdi/processor-architecture-subprocess.rst
  gdi/databases.rst
  gdi/hosts-servers.rst
  gdi/integrations-list.rst
  gdi/monitors-databases/consul.rst
  gdi/monitors-databases/etcd.rst
  gdi/monitors-hosts/amazon-ecs-metadata.rst
  gdi/monitors-hosts/chrony.rst
  gdi/monitors-hosts/disk.rst
  gdi/monitors-hosts/health-checker.rst
  gdi/monitors-hosts/host-processload.rst
  gdi/monitors-hosts/win-services.rst
  gdi/monitors-languages/asp-dot-net.rst
  gdi/monitors-monitoring/win_perf_counters.rst
  gdi/monitors-network/statsd.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-advanced.rst
  gdi/opentelemetry/collector-kubernetes/metrics-ootb-k8s.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-receivers.rst
  gdi/opentelemetry/components/awsecscontainermetrics-receiver.rst
  gdi/opentelemetry/components/chrony-receiver.rst
Labels: sync

#1580 Pulling refs/heads/main into main
  admin/authentication/authentication-tokens/org-tokens.rst
  alerts-detectors-notifications/detectors-best-practices.rst
  index.rst
Labels: sync

#1575 Update servicenow-integration.rst
  sp-oncall/spoc-integrations/servicenow-integration.rst
Labels: external, stop-alert
