Repository splunk/public-o11y-docs, pull requests merged in 2024-07, with the labels that each got.

#1405 Fix kafka permissions in AWS CloudWatch integrations
  gdi/get-data-in/connect/aws/aws-prereqs.rst
Labels: external

#1408 Update discovery-mode with support for Kafka
  gdi/opentelemetry/discovery-mode.rst
Labels: external

#1404 Pulling refs/heads/main into main
  _images/apm/apm-filters/apm-filters-environment.png
  _images/apm/apm-filters/apm-filters-operations.png
  _images/apm/apm-filters/apm-filters-service.png
  _images/apm/apm-filters/apm-filters-tag.png
  _images/apm/apm-filters/apm-filters-time-range.png
  _images/apm/apm-filters/apm-filters-workflows.png
  _images/apm/spans-traces/filter-service-map.png
  admin/authentication/authentication-tokens/org-tokens.rst
  admin/subscription-usage/apm-billing-usage-index.rst
  alerts-detectors-notifications/slo/create-slo.rst
  apm/apm-spans-traces/service-map.rst
  apm/filter-apm-data.rst
  apm/profiling/using-the-flamegraph.rst
  gdi/get-data-in/application/java/migrate-metrics.rst
  gdi/get-data-in/application/java/troubleshooting/common-java-troubleshooting.rst
  gdi/get-data-in/application/otel-dotnet/troubleshooting/common-dotnet-troubleshooting.rst
  gdi/monitors-databases/mongodb.rst
  gdi/monitors-databases/redis.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-backend.rst
  gdi/opentelemetry/collector-builtin-dashboard.rst
  index.rst
Labels: sync

#1409 List both types of permissions for kafka
  gdi/get-data-in/connect/aws/aws-prereqs.rst
Labels: gdi, cloud, external, stop-alert

#1410 Pulling refs/heads/main into main
  _includes/gdi/otel-receivers-table.rst
  gdi/get-data-in/connect/aws/aws-prereqs.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-receivers.rst
  gdi/opentelemetry/components/prometheus-receiver.rst
  gdi/opentelemetry/components/rabbitmq-receiver.rst
  gdi/opentelemetry/components/receiver-creator-receiver.rst
Labels: sync

#1412 Pulling refs/heads/main into main
  gdi/opentelemetry/components/kafkametrics-receiver.rst
  gdi/opentelemetry/discovery-mode.rst
Labels: sync

#1413 Pulling refs/heads/main into main
  gdi/opentelemetry/components/kafkametrics-receiver.rst
  sp-oncall/alerts/alerts-main.rst
  sp-oncall/mobile/mobile-getting-started.rst
Labels: sync

#1414 Pulling refs/heads/main into main
  gdi/get-data-in/application/java/instrumentation/connect-traces-logs.rst
  gdi/monitors-databases/exec-input.rst
  gdi/monitors-network/snmp.rst
  gdi/monitors-network/statsd.rst
Labels: sync

#1406 Update instrument-python-application.rst
  gdi/get-data-in/application/python/instrumentation/instrument-python-application.rst
Labels: external, stop-alert

#1407 Update python-manual-instrumentation.rst
  gdi/get-data-in/application/python/instrumentation/python-manual-instrumentation.rst
Labels: external, stop-alert

#1415 Pulling refs/heads/main into main
  gdi/get-data-in/application/java/troubleshooting/common-java-troubleshooting.rst
Labels: sync

#1416 Pulling refs/heads/main into main
  _includes/gdi/collector-windows-next-steps.rst
  gdi/opentelemetry/collector-windows/collector-windows-intro.rst
  gdi/opentelemetry/collector-windows/install-windows-manual.rst
  gdi/opentelemetry/collector-windows/install-windows-msi.rst
  gdi/opentelemetry/collector-windows/install-windows-tools.rst
  gdi/opentelemetry/collector-windows/install-windows.rst
  gdi/opentelemetry/collector-windows/windows-config.rst
  gdi/opentelemetry/opentelemetry.rst
Labels: sync

#1419 Pulling refs/heads/main into main
  _includes/gdi/application-receiver-table.rst
  gdi/monitors-cloud/kong.rst
  synthetics/browser-test/browser-test-results.rst
Labels: sync

#1420 Pulling refs/heads/main into main
  _includes/logs/loc-availability.rst
  logs/intro-logconnect.rst
  logs/scp.rst
Labels: sync

#1421 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-linux/install-linux.rst
Labels: sync

#1422 Pulling refs/heads/main into main
  gdi/get-data-in/application/java/migrate-metrics.rst
  gdi/opentelemetry/components/splunk-hec-exporter.rst
Labels: sync

#1423 Pulling refs/heads/main into main
  gdi/get-data-in/application/java/instrumentation/connect-traces-logs.rst
  gdi/get-data-in/application/otel-dotnet/troubleshooting/common-dotnet-troubleshooting.rst
  gdi/get-data-in/rum/ios/manual-rum-ios-instrumentation.rst
Labels: sync

#1425 Pulling refs/heads/main into main
  gdi/opentelemetry/components/splunk-hec-exporter.rst
Labels: sync

#1427 Pulling refs/heads/main into main
  gdi/opentelemetry/deployments/otel-deployments.rst
Labels: sync

#1426 Update linux-third-party.rst (Discovery mode)
  gdi/opentelemetry/automatic-discovery/linux/linux-third-party.rst
Labels: gdi, collector, external, stop-alert

#1428 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-windows/install-windows-tools.rst
Labels: sync

#1429 Pulling refs/heads/main into main
  requirements.txt
Labels: sync

#1430 Pulling refs/heads/main into main
  metrics-and-metadata/data-tools-landing.rst
  metrics-and-metadata/metrics-landing.rst
Labels: sync

#1431 Pulling refs/heads/main into main
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/opentelemetry/components/kafka-receiver.rst
  gdi/opentelemetry/logs-collector-splunk-tutorial/about-logs-collector-splunk-tutorial.rst
  gdi/opentelemetry/logs-collector-splunk-tutorial/collector-splunk.rst
  gdi/opentelemetry/logs-collector-splunk-tutorial/deploy-verify-environment.rst
  gdi/opentelemetry/logs-collector-splunk-tutorial/docker-compose.rst
Labels: sync

#1433 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-kubernetes/metrics-ootb-k8s.rst
  gdi/opentelemetry/components/kubernetes-cluster-receiver.rst
Labels: sync

#1434 Update linux installer script options
  gdi/opentelemetry/collector-linux/install-linux.rst
Labels: external, stop-alert

#1435 Pulling refs/heads/main into main
  admin/references/data-retention.rst
Labels: sync

#1437 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/get-awstoc.rst
Labels: sync

#1438 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-cloudformation.rst
  gdi/get-data-in/connect/aws/aws-terraformconfig.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
Labels: sync

#1439 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/get-awstoc.rst
  gdi/get-data-in/serverless/aws/splunk-otel-lambda-layer.rst
  gdi/monitors-hosts/docker.rst
  gdi/opentelemetry/automatic-discovery/discovery-kubernetes.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-advanced-config.rst
Labels: sync

#1440 Pulling refs/heads/main into main
  _includes/gdi/available-gcp.rst
  gdi/get-data-in/connect/gcp/gcp-metrics.rst
  gdi/get-data-in/connect/gcp/gcp.rst
  gdi/integrations/cloud-gcp.rst
Labels: sync

#1387 Patch 2
  synthetics/test-config/SynPublicLocations.zip
  synthetics/test-config/au0-public-locations.csv
  synthetics/test-config/eu0-public-locations.csv
  synthetics/test-config/jp0-public-locations.csv
  synthetics/test-config/us0-public-locations.csv
  synthetics/test-config/us1-public-locations.csv
  synthetics/test-config/us2-public-locations.csv
Labels: external, stop-alert

#1442 Update filelog-receiver.rst
  gdi/opentelemetry/components/filelog-receiver.rst
Labels: external

#1441 Pulling refs/heads/main into main
  admin/references/system-limits/sys-limits-apm.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
Labels: sync

#1444 Update data-retention.rst
  admin/references/data-retention.rst
Labels: external, stop-alert

#1447 Pulling refs/heads/main into main
  _images/ai/ai1.png
  _images/ai/ai2.png
  _images/ai/ai3.png
  get-started/o11y-ai.rst
  index.rst
Labels: sync

#1448 Pulling refs/heads/main into main
  gdi/private-connectivity/aws-privatelink.rst
Labels: sync

#1449 Pulling refs/heads/main into main
  _images/gdi/dashboard-group-ec2.png
  _images/gdi/elb-navigator-heatmap.png
  _includes/gdi/otel-receivers-table.rst
  apm/apm-spans-traces/trace-analyzer.rst
  gdi/get-data-in/gdi-guide/additional-resources.rst
  gdi/get-data-in/gdi-guide/api-onboarding.rst
  gdi/get-data-in/gdi-guide/apm-onboarding.rst
  gdi/get-data-in/gdi-guide/apm/instrument-back-end.rst
  gdi/get-data-in/gdi-guide/apm/instrument-serverless-funcs.rst
  gdi/get-data-in/gdi-guide/apm/send-custom-data.rst
  gdi/get-data-in/gdi-guide/infrastructure-onboarding.rst
  gdi/get-data-in/gdi-guide/infrastructure/configure-third-party.rst
  gdi/get-data-in/gdi-guide/infrastructure/integrate-cloud-services.rst
  gdi/get-data-in/gdi-guide/infrastructure/send-server-cluster-data.rst
  gdi/get-data-in/gdi-guide/rum-onboarding.rst
  gdi/get-data-in/get-data-in.rst
  gdi/opentelemetry/collector-windows/install-windows-msi.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-receivers.rst
  gdi/opentelemetry/components/apache-receiver.rst
  get-started/o11y-ai.rst
  get-started/o11y.rst
  index.rst
  sp-oncall/notifications/call-notification-numbers.rst
  sp-oncall/spoc-integrations/splunk-integration-guide.rst
Labels: sync

#1450 Pulling refs/heads/main into main
  admin/references/data-retention.rst
  apm/apm-spans-traces/extended-trace-retention.rst
  gdi/get-data-in/rum/browser/troubleshooting.rst
Labels: sync

#1451 Pulling refs/heads/main into main
  metrics-and-metadata/link-metadata-to-content.rst
Labels: sync

#1452 Pulling refs/heads/main into main
  gdi/opentelemetry/components/apache-receiver.rst
Labels: sync

#1454 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-prereqs.rst
Labels: sync

#1455 Pulling refs/heads/main into main
  _includes/gdi/available-azure.rst
  gdi/get-data-in/connect/azure/azure-metrics.rst
  gdi/get-data-in/serverless/aws/otel-lambda-layer/instrumentation/dotnet-lambdas.rst
  gdi/integrations/cloud-azure.rst
  rum/rum-session-replay.rst
Labels: sync

#1457 Pulling refs/heads/main into main
  _includes/gdi/otel-receivers-table.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-receivers.rst
  gdi/opentelemetry/components/splunk-enterprise-receiver.rst
Labels: sync

#1458 Pulling refs/heads/main into main
  gdi/monitors-gitlab/gitlab.rst
  logs/set-up-logconnect.rst
Labels: sync

#1459 Pulling refs/heads/main into main
  gdi/monitors-databases/mongodb.rst
  gdi/monitors-monitoring/win_perf_counters.rst
  gdi/opentelemetry/components/filelog-receiver.rst
  gdi/opentelemetry/components/fluentd-receiver.rst
  gdi/opentelemetry/components/jmx-receiver.rst
  gdi/opentelemetry/components/mongodb-atlas-receiver.rst
  gdi/opentelemetry/components/mongodb-receiver.rst
  gdi/opentelemetry/components/windowsperfcounters-receiver.rst
  gdi/opentelemetry/components/zipkin-receiver.rst
Labels: sync

#1460 Pulling refs/heads/main into main
  gdi/monitors-prometheus/prometheus-generic.rst
  gdi/opentelemetry/components/mysql-receiver.rst
  gdi/opentelemetry/components/oracledb-receiver.rst
  gdi/opentelemetry/components/otlp-exporter.rst
  gdi/opentelemetry/components/postgresql-receiver.rst
  gdi/opentelemetry/components/prometheus-receiver.rst
  gdi/opentelemetry/components/receiver-creator-receiver.rst
  gdi/opentelemetry/components/simple-prometheus-receiver.rst
  gdi/opentelemetry/components/smartagent-receiver.rst
  gdi/opentelemetry/components/splunk-hec-receiver.rst
  gdi/opentelemetry/components/syslog-receiver.rst
  gdi/opentelemetry/components/udp-receiver.rst
Labels: sync

#1461 Pulling refs/heads/main into main
  analytics/signalflow-analytics-intro.rst
  gdi/get-data-in/gdi-guide/apm/send-custom-data.rst
  gdi/opentelemetry/components/windowsperfcounters-receiver.rst
Labels: sync

#1463 Pulling refs/heads/main into main
  gdi/monitors-cloud/heroku.rst
  gdi/opentelemetry/collector-linux/deployments-linux-ansible.rst
  gdi/opentelemetry/collector-linux/deployments-linux-chef.rst
  gdi/opentelemetry/collector-linux/deployments-linux-puppet.rst
  gdi/opentelemetry/collector-linux/deployments-linux-salt.rst
  gdi/opentelemetry/collector-linux/install-linux-tools.rst
  gdi/opentelemetry/collector-linux/install-linux.rst
  gdi/opentelemetry/collector-linux/linux-config-ootb.rst
  gdi/opentelemetry/collector-linux/linux-config.rst
Labels: sync

#1465 Manual navigation tracking for Android
  gdi/get-data-in/rum/android/manual-rum-android-instrumentation.rst
Labels: external, stop-alert

#1467 Fixing public key typo for docker image verification
  gdi/opentelemetry/install-the-collector.rst
Labels: external, stop-alert
