Repository splunk/public-o11y-docs, pull requests merged in 2024-12, with the labels that each got.

#1623 Improve GCP integration quota option description
  gdi/get-data-in/connect/gcp/gcp-connect.rst
Labels: gdi, cloud, external, stop-alert

#1622 Pulling refs/heads/main into main
  infrastructure/metrics-pipeline/mpm-rule-routing.rst
  synthetics/test-config/synth-alerts.rst
Labels: sync

#1624 Pulling refs/heads/main into main
  _images/get-started/o11y_onboardingGuideFlow_1-onboarding.svg
  _images/get-started/o11y_onboardingGuideFlow_2-initial.svg
  _images/get-started/o11y_onboardingGuideFlow_3-scaled.svg
  _images/get-started/o11y_onboardingGuideFlow_full-flow.svg
  _images/get-started/onboarding-guide-2point0-flowonly.svg
  _images/get-started/onboarding-guide-2point0-initial.svg
  _images/get-started/onboarding-guide-2point0-readiness.svg
  _images/get-started/onboarding-guide-2point0-scaled.svg
  gdi/monitors-databases/exec-input.rst
  gdi/monitors-databases/logparser.rst
  gdi/monitors-databases/sql.rst
  gdi/monitors-hosts/procstat.rst
  gdi/monitors-hosts/win-services.rst
  gdi/monitors-languages/asp-dot-net.rst
  gdi/monitors-languages/microsoft-dotnet.rst
  gdi/monitors-network/dns.rst
  gdi/monitors-network/snmp.rst
  gdi/opentelemetry/otel-other/telegraf.rst
  gdi/opentelemetry/smart-agent/smart-agent-migration-to-otel-collector.rst
  get-started/get-started-guide/get-started-guide.rst
  get-started/get-started-guide/initial-rollout.rst
  get-started/get-started-guide/onboarding-readiness.rst
  get-started/get-started-guide/scaled-rollout.rst
  scenarios-tutorials/scenario-collector.rst
  scenarios-tutorials/scenario-landing.rst
  scenarios-tutorials/scenario.rst
Labels: sync

#1626 Pulling refs/heads/main into main
  gdi/private-connectivity/aws-privatelink.rst
  metrics-and-metadata/metrics-usage-analytics.rst
  sp-oncall/spoc-integrations/arista-cloudvision-integration.rst
  sp-oncall/spoc-integrations/integrations-main.rst
Labels: sync

#1627 Pulling refs/heads/main into main
  _includes/gdi/available-azure.rst
  alerts-detectors-notifications/alerts-and-detectors/alert-condition-reference/hist-anomaly.rst
  gdi/get-data-in/connect/azure/azure-metrics.rst
  metrics-and-metadata/relatedcontent.rst
  rum/rum-rules.rst
  synthetics/test-config/synth-alerts.rst
Labels: sync

#1629 Update kubernetes-config-advanced.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-advanced.rst
Labels: external, stop-alert

#1630 Update host-metrics-receiver.rst
  gdi/opentelemetry/components/host-metrics-receiver.rst
Labels: external, stop-alert

#1636 Update collector-config-tutorial-edit.rst
  gdi/opentelemetry/collector-linux/collector-configuration-tutorial/collector-config-tutorial-edit.rst
Labels: external, stop-alert
