Repository splunk/public-o11y-docs, pull requests merged in 2024-02, with the labels that each got.

#1156 Typo
  infrastructure/metrics-pipeline/metrics-pipeline-intro.rst
Labels: imm, external, stop-alert

#1155 Pulling refs/heads/main into main
  apm/apm-scenarios/troubleshoot-tag-spotlight.rst
  apm/intro-to-apm.rst
  gdi/get-data-in/application/java/instrumentation/java-servers-instructions.rst
  gdi/get-data-in/serverless/azure/instrument-azure-functions.rst
  splunkplatform/practice-reliability/incident-response.rst
Labels: sync

#1158 Pulling refs/heads/main into main
  gdi/opentelemetry/components/windowsperfcounters-receiver.rst
Labels: sync

#1159 Pulling refs/heads/main into main
  _includes/collector-env-vars.rst
  gdi/opentelemetry/collector-windows/install-windows-manual.rst
  gdi/opentelemetry/collector-windows/install-windows.rst
  gdi/opentelemetry/collector-windows/windows-config-ootb.rst
  gdi/opentelemetry/collector-windows/windows-config.rst
  gdi/opentelemetry/environment-variables.rst
Labels: sync

#1160 Pulling refs/heads/main into main
  gdi/opentelemetry/deployments/deployments-chef.rst
  gdi/opentelemetry/deployments/deployments-windows-ansible.rst
  gdi/opentelemetry/deployments/deployments-windows-puppet.rst
Labels: sync

#1161 Pulling refs/heads/main into main
  _images/gdi/collector/collector-builtin-dashboard-01.jpg
  _images/gdi/collector/collector-builtin-dashboard-02.jpg
  _images/gdi/collector/collector-builtin-dashboard-03.jpg
  _images/gdi/collector/collector-builtin-dashboard-04.jpg
  apm/set-up-apm/customize-apm.rst
  gdi/opentelemetry/collector-builtin-dashboard.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-logs.rst
  gdi/opentelemetry/components/prometheus-receiver.rst
  gdi/opentelemetry/opentelemetry.rst
  gdi/opentelemetry/smart-agent/translation-tool.rst
Labels: sync

#1162 Pulling refs/heads/main into main
  gdi/opentelemetry/opentelemetry.rst
Labels: sync

#1163 Pulling refs/heads/main into main
  _includes/slo/slo-preview-header.rst
  alerts-detectors-notifications/slo/burn-rate-alerts.rst
  alerts-detectors-notifications/slo/create-slo.rst
  alerts-detectors-notifications/slo/slo-intro.rst
  alerts-detectors-notifications/slo/view-slo.rst
  index.rst
  slo/slo-preview-sitemap.rst
  slo/view-slo.rst
Labels: sync

#1165 Pulling refs/heads/main into main
  admin/authentication/authentication-tokens/manage-usage.rst
  admin/org-metrics.rst
  admin/subscription-usage/monitor-imm-billing-usage.rst
  synthetics/api-test/set-up-api-test.rst
  synthetics/browser-test/set-up-browser-test.rst
  synthetics/test-config/try-now.rst
Labels: sync

#1166 Pulling refs/heads/main into main
  gdi/get-data-in/application/nodejs/configuration/advanced-nodejs-otel-configuration.rst
  get-started/service-description.rst
Labels: sync

#1167 Pulling refs/heads/main into main
  _images/apm/spans-traces/log-trace-related.png
  _images/apm/spans-traces/span-search-expand-collapse.png
  _images/apm/spans-traces/span-search-filter.gif
  _images/apm/spans-traces/span-search-integrated-traces-splunk-show.png
  _images/apm/spans-traces/span-search-related-content.png
  _includes/gdi/troubleshoot-zeroconfig-k8s.rst
  _includes/gdi/zero-config-preview-header.rst
  apm/apm-spans-traces/span-search.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-k8s.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-nodejs-k8s.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-nodejs-linux.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-nodejs.rst
  gdi/opentelemetry/discovery-mode.rst
  gdi/opentelemetry/zero-config.rst
Labels: sync

#1168 Pulling refs/heads/main into main
  _includes/admin/roles-mpm1.rst
  _includes/admin/roles_alerts_detectors1.rst
  _includes/admin/roles_apm1.rst
  _includes/admin/roles_data_configuration1.rst
  _includes/admin/roles_help_support1.rst
  _includes/admin/roles_log_observer1.rst
  _includes/admin/roles_navigation1.rst
  _includes/admin/roles_navs_dashbds1.rst
  _includes/admin/rum-roles-caps1.rst
  _includes/admin/synth-roles-caps1.rst
  _templates/breadcrumbs.html
  admin/admin.rst
  admin/notif-services/amazoneventbridge.rst
  admin/notif-services/bigpanda.rst
  admin/subscription-usage/analyze-apm-billing-usage.rst
  admin/subscription-usage/apm-billing-usage-index.rst
  admin/subscription-usage/view-apm-billing-reports.rst
  admin/user-management/roles/roles-and-capabilities-about.rst
  admin/user-management/roles/roles-and-capabilities-table.rst
  admin/user-management/roles/users-assign-roles.rst
  admin/user-management/teams/associate-team.rst
  admin/user-management/user-management-intro.rst
  apm/apm-alert-visualize/apm-dashboards.rst
  apm/apm-data-links/apm-create-data-links.rst
  apm/apm-spans-traces/extended-trace-retention.rst
  apm/apm-spans-traces/inferred-services.rst
  apm/set-up-apm/sensitive-data-controls.rst
  apm/span-tags/add-context-trace-span.rst
  apm/span-tags/cmms.rst
  apm/span-tags/index-span-tags.rst
  apm/workflows/create-workflow-rule.rst
  apm/workflows/example-business-workflow.rst
  apm/workflows/workflow-alerts.rst
  apm/workflows/workflows.rst
  gdi/get-data-in/application/python/splunk-python-otel-distribution.rst
  gdi/get-data-in/connect/aws/aws-apiconfig.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/mysql-receiver.rst
  index.rst
  infrastructure/metrics-pipeline/data-dropping-impact.rst
  infrastructure/metrics-pipeline/related-metrics.rst
  infrastructure/metrics-pipeline/use-metrics-pipeline.rst
  logs/alias.rst
  logs/infinite.rst
  logs/metricization.rst
  logs/save-share.rst
  logs/scp.rst
  logs/set-up-logconnect.rst
  private-preview/rbac/roles-and-capabilities-about.rst
  private-preview/rbac/users-assign-roles.rst
Labels: sync

#1170 Pulling refs/heads/main into main
  _includes/admin/roles_apm.rst
  _includes/admin/roles_data_configuration.rst
  _includes/admin/roles_help_support.rst
  _includes/admin/roles_log_observer.rst
  _includes/admin/roles_navigation.rst
  admin/user-management/roles/roles-and-capabilities-about.rst
  admin/user-management/roles/users-assign-roles.rst
  gdi/monitors-databases/sql.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-dotnet.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/sqlquery-receiver.rst
  gdi/opentelemetry/components/tcp-receiver.rst
  gdi/opentelemetry/discovery-mode.rst
Labels: sync

#1173 Update rum-mobile-scenario.rst
  rum/rum-scenario-library/rum-mobile-scenario.rst
Labels: external

#1172 Pulling refs/heads/main into main
  _includes/admin/roles_alerts_detectors.rst
  _includes/admin/roles_apm.rst
  _includes/admin/roles_data_configuration.rst
  _includes/admin/roles_help_support.rst
  _includes/admin/roles_log_observer.rst
  _includes/admin/roles_mpm.rst
  _includes/admin/roles_navigation.rst
  _includes/admin/roles_navs_dashbds.rst
  _includes/admin/rum-roles-caps.rst
  _includes/admin/synth-roles-caps.rst
  admin/subscription-usage/monitor-imm-billing-usage.rst
  admin/user-management/teams/enhanced-team-security.rst
  alerts-detectors-notifications/slo/slo-intro.rst
  splunkplatform/practice-reliability/slis.rst
Labels: sync

#1174 Pulling refs/heads/main into main
  gdi/opentelemetry/components/signalfx-exporter.rst
  metrics-and-metadata/data-tools-landing.rst
  metrics-and-metadata/enablerelatedcontent.rst
  metrics-and-metadata/relatedcontent.rst
Labels: sync

#1175 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-kubernetes/collector-kubernetes-intro.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config.rst
  gdi/opentelemetry/discovery-mode.rst
Labels: sync

#1150 Patch 1
  synthetics/test-config/public-locations.rst
  synthetics/test-config/us2-public-locations.csv
Labels: external, stop-alert

#1176 Pulling refs/heads/main into main
  apm/db-query-perf/db-perf-troubleshooting.rst
  apm/db-query-perf/turn-on-db-perf.rst
  gdi/get-data-in/application/dotnet/get-started.rst
  gdi/get-data-in/application/otel-dotnet/configuration/advanced-dotnet-configuration.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
Labels: sync

#1177 Pulling refs/heads/main into main
  gdi/opentelemetry/components/signalfx-exporter.rst
Labels: sync

#1178 Pulling refs/heads/main into main
  gdi/get-data-in/rum/browser/configure-rum-browser-instrumentation.rst
Labels: sync

#1179 Update mysql.rst
  gdi/monitors-databases/mysql.rst
Labels: external, stop-alert

#1181 Pulling refs/heads/main into main
  gdi/opentelemetry/discovery-mode.rst
Labels: sync

#1182 Update collector-with-the-uf.rst
  gdi/opentelemetry/collector-with-the-uf.rst
Labels: external, stop-alert, opentelemetry

#1184 Pulling refs/heads/main into main
  _includes/configuration.rst
  gdi/index.rst
  gdi/monitors-common-config.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-dotnet-k8s.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-dotnet-windows.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-dotnet.rst
  gdi/opentelemetry/collector-linux/collector-linux-intro.rst
  gdi/opentelemetry/collector-linux/metrics-ootb-linux.rst
  gdi/opentelemetry/zero-config.rst
  splunkplatform/practice-reliability/splunkplatform-landing.rst
  synthetics/browser-test/browser-test-results.rst
  synthetics/browser-test/set-up-browser-test.rst
Labels: sync

#1186 Pulling refs/heads/main into main
  admin/user-management/user-management-intro.rst
  gdi/opentelemetry/install-the-collector.rst
Labels: sync

#1185 Add backslash escaping in the extract yaml example
  gdi/opentelemetry/components/attributes-processor.rst
Labels: external, stop-alert

#1187 Update logs attributes for Splunk OTel .NET
  gdi/get-data-in/application/otel-dotnet/instrumentation/connect-traces-logs.rst
Labels: external, stop-alert

#1188 Pulling refs/heads/main into main
  data-visualization/dashboards/dashboards.rst
  metrics-and-metadata/data-tools-landing.rst
  metrics-and-metadata/relatedcontent-collector-apm.rst
  metrics-and-metadata/relatedcontent.rst
Labels: sync

#1189 Pulling refs/heads/main into main
  admin/authentication/authentication-tokens/api-access-tokens.rst
Labels: sync

#1192 Pulling refs/heads/main into main
  gdi/get-data-in/application/otel-dotnet/instrumentation/connect-traces-logs.rst
  gdi/opentelemetry/metrics-internal-collector.rst
Labels: sync

#1193 Pulling refs/heads/main into main
  gdi/opentelemetry/components/signalfx-receiver.rst
Labels: sync

#1194 Pulling refs/heads/main into main
  _includes/application-receiver-table.rst
  apm/profiling/get-data-in-profiling.rst
  apm/profiling/profiling-troubleshooting.rst
  apm/set-up-apm/apm-gdi.rst
  gdi/get-data-in/application/application.rst
  gdi/get-data-in/application/otel-dotnet/get-started.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/connect-traces-logs.rst
  gdi/get-data-in/application/otel-dotnet/sfx/configuration/advanced-dotnet-configuration.rst
  gdi/get-data-in/application/otel-dotnet/sfx/configuration/dotnet-metrics-attributes.rst
  gdi/get-data-in/application/otel-dotnet/sfx/dotnet-requirements.rst
  gdi/get-data-in/application/otel-dotnet/sfx/instrumentation/connect-traces-logs.rst
  gdi/get-data-in/application/otel-dotnet/sfx/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/application/otel-dotnet/sfx/instrumentation/manual-dotnet-instrumentation.rst
  gdi/get-data-in/application/otel-dotnet/sfx/sfx-instrumentation.rst
  gdi/get-data-in/application/otel-dotnet/sfx/troubleshooting/common-dotnet-troubleshooting.rst
  gdi/get-data-in/application/otel-dotnet/troubleshooting/common-dotnet-troubleshooting.rst
  gdi/get-data-in/application/php/configuration/advanced-php-configuration.rst
  gdi/get-data-in/application/php/get-started.rst
  gdi/get-data-in/application/php/instrumentation/instrument-php-application.rst
  gdi/get-data-in/application/php/instrumentation/php-manual-instrumentation.rst
  gdi/get-data-in/application/php/php-requirements.rst
  gdi/get-data-in/get-data-in.rst
  index.rst
Labels: sync

#1196 Pulling refs/heads/main into main
  gdi/monitors-databases/mysql.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-dotnet-k8s.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-k8s.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-nodejs-k8s.rst
Labels: sync

#1198 rum.node.* metrics need custom URL grouping rules
  rum/rum-rules.rst
Labels: rum, external, stop-alert

#1199 page level metrics are captured only if custom URL grouping rules are…
  gdi/get-data-in/rum/browser/rum-browser-data-model.rst
Labels: rum, external, stop-alert

#1197 Pulling refs/heads/main into main
  _images/get-started/host-demo.png
  gdi/opentelemetry/collector-linux/linux-config-ootb.rst
  gdi/opentelemetry/collector-linux/linux-config.rst
  get-started/tutorials.rst
  get-started/tutorials/collector-configuration-tutorial/about-collector-config-tutorial.rst
  get-started/tutorials/collector-configuration-tutorial/collector-config-tutorial-edit.rst
  get-started/tutorials/collector-configuration-tutorial/collector-config-tutorial-start.rst
  get-started/tutorials/collector-configuration-tutorial/collector-config-tutorial-troubleshoot.rst
Labels: sync

#1200 Pulling refs/heads/main into main
  admin/references/data-retention.rst
  gdi/monitors-databases/logparser.rst
  gdi/opentelemetry/support-checklist.rst
Labels: sync

#1201 [otel-dotnet] Update `System.Diagnostics.DiagnosticSource` version in docs
  gdi/get-data-in/application/otel-dotnet/instrumentation/manual-dotnet-instrumentation.rst
Labels: gdi, apm, external, stop-alert

#1205 Pulling refs/heads/main into main
  _static/custom.css
  _templates/404.html
  _templates/layout.html
  _templates/search.html
  admin/subscription-usage/analyze-apm-billing-usage.rst
  admin/subscription-usage/apm-billing-usage-index.rst
  admin/subscription-usage/view-apm-billing-reports.rst
  gdi/opentelemetry/components/otlp-exporter.rst
  gdi/opentelemetry/components/otlphttp-exporter.rst
  gdi/other-ingestion-methods/grpc-data-ingest.rst
Labels: sync

#1207 Pulling refs/heads/main into main
  logs/scp.rst
  logs/set-up-logconnect.rst
Labels: sync

#1206 Update auto-instrumentation-dotnet-windows.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-dotnet-windows.rst
Labels: external, stop-alert

#1210 Update host-processlist.rst
  gdi/monitors-hosts/host-processlist.rst
Labels: gdi, feedback, external

#1211 Pulling refs/heads/main into main
  _images/apm/apm-use-cases/trace-duration-filter-sample.gif
  _images/apm/apm-use-cases/trace-duration-filter-to-selection.gif
  _images/apm/apm-use-cases/trace-duration-interpret-heatmap.png
  _images/apm/apm-use-cases/trace-duration-review-traces.gif
  _images/apm/apm-use-cases/trace-duration-time-select.gif
  _images/apm/trace-analyzer/TraceAnalyzerControls+duration.png
  _images/apm/trace-analyzer/TraceAnalyzerControls.png
  _images/apm/trace-analyzer/TraceAnalyzerLimit.png
  _images/apm/trace-analyzer/TraceDurationDragDropChart.gif
  _images/apm/trace-analyzer/heatmap.png
  _images/apm/trace-analyzer/trace-drag-drop-chart.gif
  _images/apm/trace-analyzer/trace-error-chart.gif
  admin/references/system-limits/sys-limits-apm.rst
  apm/apm-scenarios/apm-scenarios-intro.rst
  apm/apm-scenarios/troubleshoot-slow-traces.rst
  apm/apm-scenarios/troubleshoot-traces.rst
  apm/apm-spans-traces/trace-analyzer.rst
  get-started/scenario-landing.rst
Labels: sync

#1212 Pulling refs/heads/main into main
  _images/splunkplatform/pairingID.png
  _images/splunkplatform/unifiedID-pairingSuccess.png
  gdi/opentelemetry/collector-linux/install-linux-manual.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-exporters.rst
  gdi/opentelemetry/components/a-components-extensions.rst
  gdi/opentelemetry/components/a-components-processors.rst
  gdi/opentelemetry/components/a-components-receivers.rst
  gdi/opentelemetry/components/awss3-exporter.rst
  gdi/opentelemetry/components/azureeventhub-receiver.rst
  gdi/opentelemetry/components/carbon-receiver.rst
  gdi/opentelemetry/components/cloudfoundry-receiver.rst
  gdi/opentelemetry/components/collectd-receiver.rst
  gdi/opentelemetry/components/databricks-receiver.rst
  gdi/opentelemetry/components/discovery-receiver.rst
  gdi/opentelemetry/components/docker-observer-extension.rst
  gdi/opentelemetry/components/ecs-observer-extension.rst
  gdi/opentelemetry/components/file-exporter.rst
  gdi/opentelemetry/components/file-storage-extension.rst
  gdi/opentelemetry/components/host-observer-extension.rst
  gdi/opentelemetry/components/http-forwarder-extension.rst
  gdi/opentelemetry/components/journald-receiver.rst
  gdi/opentelemetry/components/kafka-exporter.rst
  gdi/opentelemetry/components/kafka-receiver.rst
  gdi/opentelemetry/components/kafkametrics-receiver.rst
  gdi/opentelemetry/components/kubernetes-events-receiver.rst
  gdi/opentelemetry/components/kubernetes-objects-receiver.rst
  gdi/opentelemetry/components/kubernetes-observer-extension.rst
  gdi/opentelemetry/components/metrics-transform-processor.rst
  gdi/opentelemetry/components/oracledb-receiver.rst
  gdi/opentelemetry/components/pprof-extension.rst
  gdi/opentelemetry/components/probabilistic-sampler-processor.rst
  gdi/opentelemetry/components/redis-receiver.rst
  gdi/opentelemetry/components/routing-processor.rst
  gdi/opentelemetry/components/sapm-receiver.rst
  gdi/opentelemetry/components/smartagent-extension.rst
  gdi/opentelemetry/components/statsd-receiver.rst
  gdi/opentelemetry/components/tail-sampling-processor.rst
  gdi/opentelemetry/components/windowseventlog-receiver.rst
  gdi/opentelemetry/discovery-mode.rst
  splunkplatform/unified-id/unified-identity.rst
Labels: sync

#1213 Pulling refs/heads/main into main
  gdi/opentelemetry/install-the-collector.rst
Labels: sync

#1214 Pulling refs/heads/main into main
  _images/apm/spans-traces/service-map-01.png
  _images/apm/spans-traces/service-map-02-breakdown.png
  _images/apm/spans-traces/service-map-breakdown-global-search-rename.png
  _images/apm/spans-traces/service-map-global-search-rename.png
  _images/apm/spans-traces/service-map-related-content-global-search-rename.gif
  _templates/banner.html
  admin/subscription-usage/rum-subscription-usage.rst
  apm/apm-data-links/apm-use-data-links.rst
  apm/apm-scenarios/monitor-services.rst
  apm/apm-scenarios/service-map.rst
  apm/apm-scenarios/services-impact-business-workflows.rst
  apm/apm-spans-traces/download-traces.rst
  apm/apm-spans-traces/service-map.rst
  apm/apm-spans-traces/trace-analyzer.rst
  apm/apm-spans-traces/trace-search.rst
  apm/apm-spans-traces/traces-spans.rst
  apm/apm-spans-traces/traces-special-cases.rst
  apm/intro-to-apm.rst
  apm/key-concepts.rst
  apm/set-up-apm/apm-orientation.rst
  apm/workflows/workflows.rst
  gdi/get-data-in/application/java/performance.rst
  gdi/get-data-in/application/nodejs/performance.rst
  gdi/get-data-in/application/otel-dotnet/performance.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-dotnet.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java.rst
  get-started/welcome.rst
  index.rst
Labels: sync
