Repository splunk/public-o11y-docs, pull requests merged in 2024-04, with the labels that each got.

#1269 Pulling refs/heads/main into main
  _includes/admin/roles_alerts_detectors.rst
  _includes/admin/roles_apm.rst
  _includes/admin/roles_data_configuration.rst
  _includes/admin/roles_help_support.rst
  _includes/admin/roles_log_observer.rst
  _includes/admin/roles_mpm.rst
  _includes/admin/roles_navigation.rst
  _includes/admin/roles_navs_dashbds.rst
  _includes/admin/rum-roles-caps.rst
  _includes/admin/synth-roles-caps.rst
  gdi/get-data-in/rum/android/install-rum-android.rst
  gdi/get-data-in/rum/android/manual-rum-android-instrumentation.rst
  gdi/get-data-in/rum/ios/install-rum-ios.rst
  gdi/get-data-in/rum/ios/manual-rum-ios-instrumentation.rst
  gdi/monitors-databases/microsoft-sql-server.rst
  gdi/opentelemetry/collector-linux/install-linux.rst
  rum/set-up-rum.rst
Labels: sync

#1270 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-connect-ms.rst
  gdi/get-data-in/connect/aws/aws-console-ms.rst
  gdi/get-data-in/connect/aws/aws-prereqs.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
Labels: sync

#1271 Pulling refs/heads/main into main
  _templates/layout.html
  admin/authentication/allow-services.rst
  gdi/opentelemetry/collector-windows/install-windows-manual.rst
  gdi/opentelemetry/collector-windows/install-windows.rst
  gdi/opentelemetry/collector-windows/windows-config.rst
  infrastructure/metrics-pipeline/metrics-pipeline-intro.rst
Labels: sync

#1272 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-windows/install-windows-manual.rst
  gdi/opentelemetry/collector-windows/install-windows.rst
Labels: sync

#1273 Pulling refs/heads/main into main
  logs/save-share.rst
Labels: sync

#1274 Pulling refs/heads/main into main
  _images/synthetics/custom-prop-syn.png
  _images/synthetics/syn-filter-test.png
  gdi/get-data-in/application/python/troubleshooting/common-python-troubleshooting.rst
  gdi/opentelemetry/splunk-collector-troubleshooting.rst
  gdi/opentelemetry/troubleshoot-logs.rst
  gdi/opentelemetry/troubleshooting.rst
  synthetics/api-test/set-up-api-test.rst
  synthetics/browser-test/set-up-browser-test.rst
  synthetics/test-config/test-config.rst
  synthetics/uptime-test/set-up-uptime-test.rst
Labels: sync

#1276 Update cloud-aws.rst
  gdi/integrations/cloud-aws.rst
Labels: external

#1275 Pulling refs/heads/main into main
  _includes/admin/roles_dashbds_only.rst
  admin/user-management/roles/roles-and-capabilities-table.rst
  gdi/get-data-in/rum/react/install-rum-react.rst
  gdi/opentelemetry/collector-linux/install-linux-manual.rst
  gdi/opentelemetry/components/http-forwarder-extension.rst
  gdi/opentelemetry/exposed-endpoints.rst
  infrastructure/intro-to-infrastructure.rst
  infrastructure/monitor/hosts.rst
  infrastructure/use-navigators.rst
Labels: sync

#1280 Pulling refs/heads/main into main
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-processors.rst
  gdi/opentelemetry/components/cumulative-to-delta-processor.rst
Labels: sync

#1283 splunk-otel-go requires Go 1.21
  _includes/requirements/go.rst
Labels: external, stop-alert

#1285 Remove unnecessary } in instrument-azure-functions.rst
  gdi/get-data-in/serverless/azure/instrument-azure-functions.rst
Labels: external, stop-alert

#1286 Pulling refs/heads/main into main
  gdi/get-data-in/application/go/instrumentation/instrument-go-application.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/loadbalancing-exporter.rst
Labels: sync

#1284 Update windows-config.rst
  gdi/opentelemetry/collector-windows/windows-config.rst
Labels: external, stop-alert

#1288 Update network-explorer-setup.rst
  infrastructure/network-explorer/network-explorer-setup.rst
Labels: external

#1289 Update network-explorer-setup.rst
  infrastructure/network-explorer/network-explorer-setup.rst
Labels: external

#1291 Pulling refs/heads/main into main
  gdi/integrations-list.rst
Labels: sync

#1287 Update scenario-monitoring.rst
  rum/rum-scenario-library/scenario-monitoring.rst
Labels: external, stop-alert

#1296 Update org-tokens.rst
  admin/authentication/authentication-tokens/org-tokens.rst
Labels: external

#1295 Pulling refs/heads/main into main
  _images/logs/ResourcesTab2.png
  gdi/get-data-in/application/otel-dotnet/instrumentation/azure-webapps.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/azure-webjobs.rst
  logs/scp.rst
  rum/error-aggregates.rst
Labels: sync

#1298 Pulling refs/heads/main into main
  gdi/opentelemetry/deployment-modes.rst
Labels: sync

#1299 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-logs.rst
Labels: sync

#1301 Pulling refs/heads/main into main
  gdi/opentelemetry/deployment-modes.rst
Labels: sync

#1304 Pulling refs/heads/main into main
  gdi/get-data-in/application/nodejs/instrumentation/instrument-nodejs-application.rst
  gdi/monitors-databases/microsoft-sql-server.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-logs.rst
  gdi/opentelemetry/components/kubernetes-cluster-receiver.rst
  gdi/opentelemetry/components/kubernetes-objects-receiver.rst
  gdi/orchestration.rst
Labels: sync

#1305 Pulling refs/heads/main into main
  _images/data-visualization/charts/change-histogram-function.png
  _images/data-visualization/charts/histogram-in-chart.png
  _images/understand/histogram.png
  _includes/gdi/histograms.rst
  admin/subscription-usage/dpm-usage.rst
  admin/subscription-usage/imm-billing.rst
  admin/subscription-usage/monitor-imm-billing-usage.rst
  data-visualization/charts/chart-builder.rst
  gdi/get-data-in/application/java/instrumentation/java-manual-instrumentation.rst
  gdi/opentelemetry/components/prometheus-receiver.rst
  gdi/opentelemetry/components/signalfx-exporter.rst
  gdi/other-ingestion-methods/send-custom-metrics.rst
  metrics-and-metadata/data-model.rst
  metrics-and-metadata/histograms-gdi.rst
  metrics-and-metadata/histograms.rst
  metrics-and-metadata/metric-types.rst
  metrics-and-metadata/metrics-landing.rst
  metrics-and-metadata/metrics.rst
Labels: sync

#1306 Pulling refs/heads/main into main
  admin/notif-services/webhook.rst
  infrastructure/monitor/aws-infra-metadata.rst
Labels: sync

#1282 Update relatedcontent-collector-apm.rst
  metrics-and-metadata/relatedcontent-collector-apm.rst
Labels: external, stop-alert

#1308 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-how-to.rst
Labels: sync

#1310 Pulling refs/heads/main into main
  apm/apm-spans-traces/service-view.rst
  gdi/get-data-in/connect/aws/aws-tutorial/about-aws-tutorial.rst
  gdi/get-data-in/connect/aws/aws-tutorial/tutorial-aws-start.rst
  gdi/get-data-in/connect/aws/aws-tutorial/tutorial-aws-use.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  gdi/get-data-in/connect/connect.rst
  gdi/get-data-in/rum/browser/configure-rum-browser-instrumentation.rst
  gdi/opentelemetry/automatic-discovery/discovery-kubernetes.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-java-traces-tutorial/about-k8s-java-traces-tutorial.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-java-traces-tutorial/config-k8s-for-java.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-java-traces-tutorial/deploy-collector-k8s-java.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-java-traces-tutorial/k8s-java-view-apm.rst
  gdi/opentelemetry/collector-kubernetes/collector-configuration-tutorial-k8s/about-collector-config-tutorial.rst
  gdi/opentelemetry/collector-kubernetes/collector-configuration-tutorial-k8s/collector-config-tutorial-edit.rst
  gdi/opentelemetry/collector-kubernetes/collector-configuration-tutorial-k8s/collector-config-tutorial-start.rst
  gdi/opentelemetry/collector-kubernetes/collector-kubernetes-intro.rst
  gdi/opentelemetry/collector-kubernetes/k8s-infrastructure-tutorial/about-k8s-tutorial.rst
  gdi/opentelemetry/collector-kubernetes/k8s-infrastructure-tutorial/get-started-k8s-imm.rst
  gdi/opentelemetry/collector-kubernetes/k8s-infrastructure-tutorial/k8s-activate-detector.rst
  gdi/opentelemetry/collector-kubernetes/k8s-infrastructure-tutorial/k8s-install-otel.rst
  gdi/opentelemetry/collector-kubernetes/k8s-infrastructure-tutorial/k8s-monitor-with-navigators.rst
  gdi/opentelemetry/collector-linux/collector-configuration-tutorial/about-collector-config-tutorial.rst
  gdi/opentelemetry/collector-linux/collector-configuration-tutorial/collector-config-tutorial-edit.rst
  gdi/opentelemetry/collector-linux/collector-configuration-tutorial/collector-config-tutorial-start.rst
  gdi/opentelemetry/collector-linux/collector-configuration-tutorial/collector-config-tutorial-troubleshoot.rst
  gdi/opentelemetry/collector-linux/collector-linux-intro.rst
  index.rst
  scenarios-tutorials/scenario-collector.rst
  scenarios-tutorials/scenario-cross.rst
  scenarios-tutorials/scenario-landing.rst
  scenarios-tutorials/scenario.rst
  scenarios-tutorials/tutorial-landing.rst
Labels: sync

#1311 Pulling refs/heads/main into main
  index.rst
  scenarios-tutorials/scenario-landing.rst
  scenarios-tutorials/tutorial-landing.rst
Labels: sync

#1312 Pulling refs/heads/main into main
  _includes/gdi/histograms.rst
  gdi/opentelemetry/components/signalfx-exporter.rst
  logs/scp.rst
  metrics-and-metadata/histograms-gdi.rst
Labels: sync

#1313 Pulling refs/heads/main into main
  _images/apm/spans-traces/span-search-repeated-spans.png
  apm/apm-spans-traces/span-search.rst
  apm/apm-spans-traces/traces-spans.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-advanced-config.rst
  gdi/opentelemetry/automatic-discovery/linux/linux-advanced-config.rst
Labels: sync
