Repository splunk/public-o11y-docs, pull requests merged in 2024-09, with the labels that each got.

#1512 Pulling refs/heads/main into main
  _includes/gdi/collector-settings-collectioninterval.rst
  _includes/gdi/collector-settings-initialdelay.rst
  _includes/gdi/otel-receivers-table.rst
  alerts-detectors-notifications/create-detectors-for-alerts.rst
  gdi/monitors-hosts/nginx.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-receivers.rst
  gdi/opentelemetry/components/apache-receiver.rst
  gdi/opentelemetry/components/mysql-receiver.rst
  gdi/opentelemetry/components/nginx-receiver.rst
  gdi/opentelemetry/data-processing.rst
  synthetics/browser-test/set-up-browser-test.rst
Labels: sync

#1514 Pulling refs/heads/main into main
  get-started/support.rst
  splunkplatform/unified-id/unified-identity.rst
Labels: sync

#1515 Update splunk-collector-troubleshooting.rst
  gdi/opentelemetry/splunk-collector-troubleshooting.rst
Labels: external

#1513 Update private-locations.rst
  synthetics/test-config/private-locations.rst
Labels: external, stop-alert

#1516 Pulling refs/heads/main into main
  _templates/404.html
  _templates/layout.html
  _templates/search.html
  apm/apm-spans-traces/apm-errors.rst
  gdi/get-data-in/connect/gcp/gcp.rst
  gdi/monitors-network/dns.rst
  get-started/support.rst
Labels: sync

#1517 Pulling refs/heads/main into main
  _includes/gdi/collector-common-options.rst
  alerts-detectors-notifications/alert-condition-reference/custom-threshold.rst
  alerts-detectors-notifications/create-detectors-for-alerts.rst
  data-visualization/charts/chart-analytics-reference.rst
  gdi/opentelemetry/collector-common-config.rst
  gdi/opentelemetry/collector-kubernetes/collector-kubernetes-intro.rst
  gdi/opentelemetry/common-config/collector-common-config-auth.rst
  gdi/opentelemetry/common-config/collector-common-config-grcp.rst
  gdi/opentelemetry/common-config/collector-common-config-net.rst
  gdi/opentelemetry/common-config/collector-common-config-tls.rst
  gdi/opentelemetry/components/kubelet-stats-receiver.rst
  gdi/opentelemetry/components/otlp-exporter.rst
  gdi/opentelemetry/components/otlp-receiver.rst
  gdi/opentelemetry/install-the-collector.rst
  sp-oncall/admin/get-started/custom-outbound-webhooks.rst
  sp-oncall/spoc-integrations/appdynamics-integration.rst
  sp-oncall/spoc-integrations/hipchat-integration.rst
  sp-oncall/spoc-integrations/new-twilio.rst
  sp-oncall/spoc-integrations/splunking-victorops-data.rst
  synthetics/test-config/private-locations.rst
Labels: sync

#1520 Pulling refs/heads/main into main
  gdi/monitors-databases/exec-input.rst
  gdi/monitors-databases/mysql.rst
  gdi/monitors-monitoring/nagios.rst
Labels: sync

#1522 Update aws-troubleshooting.rst
  gdi/get-data-in/connect/aws/aws-troubleshooting.rst
Labels: gdi, cloud, external

#1523 Pulling refs/heads/main into main
  _images/logs/WorkloadMgmt.png
  gdi/opentelemetry/components/host-metrics-receiver.rst
  logs/scp.rst
  logs/set-up-logconnect.rst
Labels: sync

#1524 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-linux/install-linux.rst
Labels: sync

#1526 Update kubernetes-config-advanced.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-advanced.rst
Labels: external, stop-alert

#1525 Pulling refs/heads/main into main
  _includes/metric-categories.rst
  gdi/get-data-in/connect/aws/aws-prereqs.rst
  gdi/get-data-in/connect/aws/aws-troubleshooting.rst
  synthetics/test-config/test-config.rst
Labels: sync

#1527 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-logs.rst
  gdi/opentelemetry/collector-linux/collector-linux-intro.rst
  gdi/opentelemetry/collector-linux/install-linux.rst
  gdi/opentelemetry/collector-linux/linux-config-logs.rst
Labels: sync

#1528 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-kubernetes/install-k8s.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-logs.rst
  logs/processors.rst
Labels: sync

#1521 Update Go distribution requirements
  _includes/requirements/go.rst
  gdi/get-data-in/application/go/splunk-go-otel-distribution.rst
Labels: external, stop-alert

#1530 Add extra AWS tags related permissions for AWS/NetworkFirewall
  gdi/get-data-in/connect/aws/aws-prereqs.rst
Labels: gdi, cloud, external

#1531 Pulling refs/heads/main into main
  _includes/gdi/available-aws.rst
  gdi/get-data-in/connect/aws/aws-connect-polling.rst
  gdi/get-data-in/connect/aws/aws-post-install.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  infrastructure/monitor/aws.rst
Labels: sync

#1532 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-linux/install-linux.rst
  metrics-and-metadata/relatedcontent.rst
Labels: sync

#1534 Pulling refs/heads/main into main
  gdi/monitors-prometheus/prometheus-node.rst
  gdi/opentelemetry/components/windowsperfcounters-receiver.rst
Labels: sync

#1535 Pulling refs/heads/main into main
  admin/notif-services/servicenow.rst
  gdi/opentelemetry/components/mssql-server-receiver.rst
Labels: sync

#1538 Update splunk-hec-exporter.rst
  gdi/opentelemetry/components/splunk-hec-exporter.rst
Labels: external, stop-alert

#1537 Pulling refs/heads/main into main
  _includes/troubleshooting-components.rst
  gdi/opentelemetry/components/otlp-exporter.rst
Labels: sync

#1539 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-linux/install-linux.rst
Labels: sync

#1542 Update kubernetes-support.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-support.rst
Labels: gdi, collector, external, stop-alert

#1543 Update slack-integration-guide.rst
  sp-oncall/spoc-integrations/slack-integration-guide.rst
Labels: external, stop-alert

#1544 fix typo in search.rst, prefeixes > prefixes
  metrics-and-metadata/search.rst
Labels: external

#1545 Update private-locations.rst for validating no_proxy settings
  synthetics/test-config/private-locations.rst
Labels: synthetics, external, stop-alert

#1541 Update notification-types.rst
  sp-oncall/notifications/notification-types.rst
Labels: admin, external, stop-alert

#1540 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-connect-polling.rst
  gdi/get-data-in/connect/aws/aws-recommended-stats.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
Labels: sync

#1547 Pulling refs/heads/main into main
  admin/references/system-limits/sys-limits-infra-details.rst
  admin/references/system-limits/sys-limits-infra.rst
  alerts-detectors-notifications/alert-condition-reference/heartbeat-check.rst
  gdi/opentelemetry/components/metrics-transform-processor.rst
Labels: sync

#1548 Pulling refs/heads/main into main
  gdi/opentelemetry/components/jmx-receiver.rst
Labels: sync

#1549 Update to remove extra content
  synthetics/test-config/private-locations.rst
Labels: external, stop-alert

#1550 Pulling refs/heads/main into main
  gdi/get-data-in/application/nodejs/instrumentation/manual-instrumentation.rst
  gdi/private-connectivity/aws-privatelink.rst
Labels: sync

#1552 SYN-4457: Update global variable documentation
  synthetics/test-config/global-variables.rst
Labels: external, stop-alert

#1551 Pulling refs/heads/main into main
  admin/subscription-usage/apm-billing-usage-index.rst
  gdi/get-data-in/connect/aws/aws-prereqs.rst
  gdi/get-data-in/connect/gcp/gcp.rst
  gdi/opentelemetry/components/jmx-receiver.rst
Labels: sync
