Repository splunk/public-o11y-docs, pull requests merged in 2024-05, with the labels that each got.

#1314 Pulling refs/heads/main into main
  _static/jsonpull-splunk.js
  gdi/get-data-in/application/otel-dotnet/configuration/advanced-dotnet-configuration.rst
  gdi/get-data-in/application/otel-dotnet/configuration/dotnet-metrics-attributes.rst
  gdi/get-data-in/application/otel-dotnet/dotnet-requirements.rst
  gdi/opentelemetry/components/mongodb-receiver.rst
  infrastructure/metrics-pipeline/metrics-pipeline-intro.rst
  infrastructure/metrics-pipeline/mpm-rule-agreggation.rst
  infrastructure/metrics-pipeline/mpm-rule-routing.rst
Labels: sync

#1315 Pulling refs/heads/main into main
  _includes/requirements/lambda.rst
Labels: sync

#1316 Pulling refs/heads/main into main
  gdi/get-data-in/application/go/instrumentation/instrument-go-application.rst
  gdi/get-data-in/application/otel-dotnet/configuration/advanced-dotnet-configuration.rst
  gdi/get-data-in/application/otel-dotnet/configuration/dotnet-metrics-attributes.rst
  gdi/get-data-in/application/otel-dotnet/dotnet-requirements.rst
  logs/scp.rst
Labels: sync

#1317 Pulling refs/heads/main into main
  _includes/gdi/otel-receivers-table.rst
  _static/jsonpull-splunk.js
  gdi/get-data-in/application/otel-dotnet/dotnet-requirements.rst
  gdi/get-data-in/application/php/instrument-php-application.rst
  gdi/get-data-in/application/php/php-otel-requirements.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-receivers.rst
  gdi/opentelemetry/components/mssql-server-receiver.rst
Labels: sync

#1318 Update ansible for otel .NET support
  gdi/opentelemetry/deployments/deployments-linux-ansible.rst
Labels: external

#1320 Pulling refs/heads/main into main
  _includes/admin/roles_alerts_detectors.rst
  _static/custom.css
  _static/jsonpull-splunk.js
  gdi/get-data-in/application/nodejs/configuration/advanced-nodejs-otel-configuration.rst
  gdi/get-data-in/application/nodejs/nodejs-otel-requirements.rst
  gdi/get-data-in/application/otel-dotnet/configuration/advanced-dotnet-configuration.rst
  gdi/get-data-in/application/otel-dotnet/dotnet-requirements.rst
  gdi/monitors-databases/apache-spark.rst
  gdi/monitors-databases/postgresql.rst
  gdi/monitors-hosts/elasticsearch.rst
  gdi/opentelemetry/automatic-discovery/linux/linux-backend.rst
  gdi/opentelemetry/collector-kubernetes/collector-configuration-tutorial-k8s/collector-config-tutorial-edit.rst
  gdi/opentelemetry/components/receiver-creator-receiver.rst
  infrastructure/monitor/aws-infra-metadata.rst
  logs/logs.rst
  logs/timeline.rst
  requirements.txt
  scenarios-tutorials/scenario-cross.rst
  scenarios-tutorials/scenario-landing.rst
  scenarios-tutorials/tutorial-landing.rst
  splunkplatform/unified-id/unified-identity.rst
  synthetics/test-config/SynPublicLocations.zip
  synthetics/test-config/public-locations.rst
Labels: sync

#1321 Move --npm-path option under installer script
  gdi/opentelemetry/automatic-discovery/linux/linux-backend.rst
Labels: external, stop-alert

#1322 Pulling refs/heads/main into main
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-processors.rst
  gdi/opentelemetry/components/redaction-processor.rst
Labels: sync

#1323 Update k8s-backend.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-backend.rst
Labels: external

#1324 Pulling refs/heads/main into main
  admin/org-metrics.rst
Labels: sync

#1327 Update lambda-ec2-collector-gateway.rst
  gdi/get-data-in/serverless/aws/otel-lambda-layer/instrumentation/lambda-ec2-collector-gateway.rst
Labels: external

#1328 Update configure-rum-android-instrumentation.rst
  gdi/get-data-in/rum/android/configure-rum-android-instrumentation.rst
Labels: external

#1329 Small section added for mongodb auto discovery
  gdi/opentelemetry/automatic-discovery/linux/linux-third-party.rst
Labels: external, stop-alert

#1330 Pulling refs/heads/main into main
  gdi/integrations/cloud-aws.rst
Labels: sync

#1331 Pulling refs/heads/main into main
  gdi/opentelemetry/automatic-discovery/linux/linux-third-party.rst
  gdi/opentelemetry/components/mongodb-receiver.rst
Labels: sync

#1319 Remove deprecated installer script options
  gdi/opentelemetry/collector-linux/install-linux.rst
Labels: external

#1326 Update puppet for .NET auto discovery
  gdi/opentelemetry/automatic-discovery/linux/linux-backend.rst
  gdi/opentelemetry/deployments/deployments-linux-puppet.rst
Labels: external, stop-alert

#1332 Pulling refs/heads/main into main
  _templates/layout.html
  admin/admin-onboarding/admin-onboarding-guide.rst
  admin/admin-onboarding/phase1/phase1-arch-gdi.rst
  admin/admin-onboarding/phase1/phase1-team-user-admin.rst
  admin/admin-onboarding/phase1/phase1.rst
  admin/admin-onboarding/phase2/phase2-apm.rst
  admin/admin-onboarding/phase2/phase2-im.rst
  admin/admin-onboarding/phase2/phase2-rollout-plan.rst
  admin/admin-onboarding/phase2/phase2.rst
  admin/admin-onboarding/phase3/phase3-apm.rst
  admin/admin-onboarding/phase3/phase3-im.rst
  admin/admin-onboarding/phase3/phase3.rst
  admin/authentication/authentication-tokens/org-tokens.rst
  admin/authentication/authentication-tokens/tokens.rst
  apm/apm-spans-traces/trace-analyzer.rst
  apm/set-up-apm/environments.rst
  gdi/opentelemetry/collector-windows/collector-windows-intro.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-connectors.rst
  gdi/opentelemetry/components/span-metrics-connector.rst
  gdi/opentelemetry/components/span-processor.rst
  gdi/opentelemetry/data-processing.rst
  get-started/welcome.rst
  index.rst
  infrastructure/metrics-pipeline/metrics-pipeline-intro.rst
  metrics-and-metadata/histograms.rst
  references/glossary.rst
  splunkplatform/practice-reliability/slis.rst
Labels: sync

#1334 Update Android docs about disabling some kinds of telemetry
  gdi/get-data-in/rum/android/configure-rum-android-instrumentation.rst
Labels: external, stop-alert

#1335 Pulling refs/heads/main into main
  _static/custom.css
  _templates/layout.html
  gdi/monitors-databases/microsoft-sql-server.rst
  gdi/monitors-hosts/vsphere.rst
  index.rst
Labels: sync

#1336 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-kubernetes/install-k8s.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-upgrade.rst
Labels: sync

#1337 Update Install Browser RUM > CSP example
  gdi/get-data-in/rum/browser/install-rum-browser.rst
Labels: external, stop-alert

#1338 Pulling refs/heads/main into main
  gdi/opentelemetry/automatic-discovery/k8s/k8s-advanced-config.rst
  gdi/opentelemetry/components/simple-prometheus-receiver.rst
  metrics-and-metadata/metrics-dimensions-mts.rst
Labels: sync

#1340 Pulling refs/heads/main into main
  admin/authentication/SSO/sso-ADSF.rst
  admin/authentication/SSO/sso-GeneralSAML.rst
  admin/authentication/SSO/sso-Google.rst
  admin/authentication/SSO/sso-Okta.rst
  admin/authentication/SSO/sso-OneLogin.rst
  admin/authentication/SSO/sso.rst
  admin/notif-services/amazoneventbridge.rst
  admin/notif-services/bigpanda.rst
  admin/notif-services/jira.rst
  admin/notif-services/microsoftteams.rst
  admin/notif-services/opsgenie.rst
  admin/notif-services/pagerduty.rst
  admin/notif-services/servicenow.rst
  admin/notif-services/slack.rst
  admin/notif-services/splunkoncall.rst
  admin/notif-services/webhook.rst
  admin/notif-services/xmatters.rst
  apm/set-up-apm/apm-gdi.rst
  gdi/get-data-in/application/go/instrumentation/instrument-go-application.rst
  gdi/get-data-in/application/java/instrumentation/instrument-java-application.rst
  gdi/get-data-in/application/nodejs/instrumentation/instrument-nodejs-application.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/application/php/instrument-php-application.rst
  gdi/get-data-in/application/php/sfx/instrumentation/instrument-php-application.rst
  gdi/get-data-in/application/python/instrumentation/instrument-python-application.rst
  gdi/get-data-in/application/ruby/distro/instrumentation/instrument-ruby-application.rst
  gdi/get-data-in/compute/k8s.rst
  gdi/get-data-in/compute/linux.rst
  gdi/get-data-in/compute/windows.rst
  gdi/get-data-in/connect/aws/aws-connect-ms.rst
  gdi/get-data-in/connect/aws/aws-connect-polling.rst
  gdi/get-data-in/connect/aws/aws-console-ms.rst
  gdi/get-data-in/connect/aws/aws-post-install.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  gdi/get-data-in/connect/azure/azure.rst
  gdi/get-data-in/connect/gcp/gcp.rst
  gdi/get-data-in/rum/android/get-android-data-in.rst
  gdi/get-data-in/rum/browser/get-browser-data-in.rst
  gdi/get-data-in/rum/ios/get-ios-data-in.rst
  gdi/get-data-in/rum/ios/install-rum-ios.rst
  gdi/get-data-in/rum/react/get-react-native-data-in.rst
  gdi/get-data-in/rum/react/install-rum-react.rst
  gdi/get-data-in/serverless/aws/otel-lambda-layer/instrument-lambda-functions.rst
  gdi/integrations/community-integrations.rst
  gdi/opentelemetry/deployments/deployments-ecs-ec2.rst
  gdi/opentelemetry/deployments/deployments-fargate.rst
  gdi/opentelemetry/opentelemetry.rst
  gdi/opentelemetry/smart-agent/smart-agent-migration-process.rst
  infrastructure/infrastructure.rst
  infrastructure/monitor/aws.rst
  logs/logs.rst
  splunkplatform/unified-id/unified-identity.rst
Labels: sync

#1333 Update salt for Node.js and .NET support
  gdi/opentelemetry/automatic-discovery/linux/linux-backend.rst
  gdi/opentelemetry/deployments/deployments-salt.rst
Labels: external

#1342 Add deb/rpm upgrade instructions for .NET
  gdi/opentelemetry/automatic-discovery/linux/linux-backend.rst
Labels: external

#1341 Fix JS syntax error in Configure RUM > Exporter settings
  gdi/get-data-in/rum/browser/configure-rum-browser-instrumentation.rst
Labels: external, stop-alert

#1343 Pulling refs/heads/main into main
  _includes/gdi/histograms.rst
  _includes/requirements/dotnet.rst
  gdi/get-data-in/application/otel-dotnet/sfx/dotnet-requirements.rst
  metrics-and-metadata/histograms-gdi.rst
Labels: sync

#1344 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-cloudformation.rst
  gdi/get-data-in/connect/aws/aws-connect-ms.rst
Labels: sync

#1347 Fix typo in o11y-architecture.rst
  get-started/o11y-architecture.rst
Labels: external, stop-alert

#1346 Pulling refs/heads/main into main
  gdi/monitors-databases/mongodb.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-backend.rst
  gdi/opentelemetry/automatic-discovery/linux/linux-backend.rst
Labels: sync

#1348 Pulling refs/heads/main into main
  index.rst
Labels: sync

#1350 Change gRCP -> gRPC
  gdi/opentelemetry/components/otlp-receiver.rst
Labels: external, stop-alert

#1349 Pulling refs/heads/main into main
  gdi/get-data-in/serverless/azure/instrument-azure-functions-dotnet.rst
  gdi/get-data-in/serverless/azure/instrument-azure-functions-nodejs.rst
  gdi/get-data-in/serverless/instrument-serverless-functions.rst
  gdi/opentelemetry/discovery-mode.rst
Labels: sync

#1351 Pulling refs/heads/main into main
  _static/jsonpull-splunk.js
  admin/authentication/authentication-tokens/org-tokens.rst
  gdi/get-data-in/application/otel-dotnet/sfx/troubleshooting/common-dotnet-troubleshooting.rst
  gdi/monitors-hosts/host-processlist.rst
Labels: sync

#1355 Pulling refs/heads/main into main
  _images/infrastructure/alert-to-nav.png
  gdi/get-data-in/connect/aws/aws-prereqs.rst
  index.rst
  infrastructure/filter-landing-page.rst
  infrastructure/use-navigators.rst
Labels: sync

#1357 Pulling refs/heads/main into main
  gdi/opentelemetry/smart-agent/smart-agent-migration-process.rst
  gdi/opentelemetry/smart-agent/smart-agent-migration-to-otel-collector.rst
  gdi/opentelemetry/smart-agent/translation-tool.rst
  gdi/smart-agent/smart-agent-intro.rst
Labels: sync

#1359 Pulling refs/heads/main into main
  Makefile
  infrastructure/filter-landing-page.rst
Labels: sync

#1361 Update host-metrics-receiver.rst
  gdi/opentelemetry/components/host-metrics-receiver.rst
Labels: external, stop-alert

#1360 Pulling refs/heads/main into main
  _includes/admin/synth-roles-caps.rst
  alerts-detectors-notifications/view-alerts.rst
  gdi/opentelemetry/collector-kubernetes/collector-kubernetes-intro.rst
  gdi/opentelemetry/collector-kubernetes/install-k8s-manifests.rst
  gdi/opentelemetry/collector-kubernetes/install-k8s.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-helm-architecture.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-helm-releases.rst
  synthetics/test-config/syn-downtimes.rst
  synthetics/test-config/test-config.rst
Labels: sync

#1363 Update create-workflow-rule.rst (grammar)
  apm/workflows/create-workflow-rule.rst
Labels: apm, external, stop-alert

#1362 Pulling refs/heads/main into main
  admin/authentication/SSO/sso-ADSF.rst
  gdi/get-data-in/connect/aws/aws-tutorial/about-aws-tutorial.rst
  gdi/get-data-in/connect/aws/aws-tutorial/tutorial-aws-start.rst
  gdi/get-data-in/connect/aws/aws-tutorial/tutorial-aws-use.rst
  gdi/opentelemetry/collector-kubernetes/k8s-infrastructure-tutorial/about-k8s-tutorial.rst
  gdi/opentelemetry/collector-kubernetes/k8s-infrastructure-tutorial/get-started-k8s-imm.rst
  gdi/opentelemetry/collector-kubernetes/k8s-infrastructure-tutorial/k8s-activate-detector.rst
  gdi/opentelemetry/collector-kubernetes/k8s-infrastructure-tutorial/k8s-install-otel.rst
  gdi/opentelemetry/collector-kubernetes/k8s-infrastructure-tutorial/k8s-monitor-with-navigators.rst
  rum/set-up-rum.rst
  synthetics/test-config/syn-downtimes.rst
Labels: sync

#1364 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-linux/install-linux.rst
Labels: sync

#1339 add link to APM info
  synthetics/browser-test/browser-test-results.rst
Labels: external, stop-alert

#1365 Update scenario-collector.rst
  scenarios-tutorials/scenario-collector.rst
Labels: collector, external, stop-alert

#1369 Update troubleshoot-business-workflows.rst
  apm/apm-scenarios/troubleshoot-business-workflows.rst
Labels: external, stop-alert

#1368 Update services-impact-business-workflows.rst
  apm/apm-scenarios/services-impact-business-workflows.rst
Labels: external, stop-alert

#1367 Update troubleshoot-noisy-detectors.rst
  alerts-detectors-notifications/scenarios-detectors-alerts/troubleshoot-noisy-detectors.rst
Labels: imm, external, stop-alert

#1366 Update monitor-autodetect.rst
  alerts-detectors-notifications/scenarios-detectors-alerts/monitor-autodetect.rst
Labels: cross-product, external, stop-alert

#1370 Pulling refs/heads/main into main
  _includes/gdi/otel-receivers-table.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-receivers.rst
  gdi/opentelemetry/components/http-check-receiver.rst
  gdi/opentelemetry/components/jaeger-receiver.rst
Labels: sync

#1371 Pulling refs/heads/main into main
  apm/span-tags/cmms.rst
Labels: sync

#1372 Pulling refs/heads/main into main
  gdi/monitors-databases/exec-input.rst
  gdi/monitors-network/snmp.rst
  gdi/monitors-network/statsd.rst
Labels: sync

#1373 Pulling refs/heads/main into main
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-extensions.rst
  gdi/opentelemetry/components/oauth2client-extension.rst
Labels: sync
