Repository splunk/public-o11y-docs, pull requests merged in 2024-01, with the labels that each got.

#1111 Pulling refs/heads/main into main
  gdi/private-connectivity/aws-privatelink.rst
Labels: sync

#1112 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-prereqs.rst
Labels: sync

#1113 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/get-awstoc.rst
Labels: sync

#1114 Pulling refs/heads/main into main
  gdi/get-data-in/connect/azure/azure-logs-ingestion.rst
  gdi/get-data-in/connect/gcp/gcp-logs.rst
  infrastructure/metrics-pipeline/related-metrics.rst
Labels: sync

#1115 Pulling refs/heads/main into main
  _includes/collector-works.rst
  admin/authentication/SSO/sso.rst
  gdi/opentelemetry/collector-kubernetes/collector-kubernetes-intro.rst
  gdi/opentelemetry/collector-kubernetes/install-k8s-addon-eks.rst
  gdi/opentelemetry/collector-kubernetes/install-k8s.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-advanced.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-logs.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config.rst
  gdi/opentelemetry/collector-kubernetes/metrics-ootb-k8s.rst
  gdi/opentelemetry/collector-linux/collector-linux-intro.rst
  gdi/opentelemetry/collector-linux/install-linux-manual.rst
  gdi/opentelemetry/collector-linux/install-linux.rst
  gdi/opentelemetry/collector-linux/linux-config-ootb.rst
  gdi/opentelemetry/collector-linux/linux-config.rst
  gdi/opentelemetry/collector-windows/collector-windows-intro.rst
  gdi/opentelemetry/collector-windows/install-windows-manual.rst
  gdi/opentelemetry/collector-windows/install-windows.rst
  gdi/opentelemetry/collector-windows/windows-config-ootb.rst
  gdi/opentelemetry/collector-windows/windows-config.rst
  gdi/opentelemetry/configure-the-collector.rst
  gdi/opentelemetry/install-the-collector.rst
  gdi/opentelemetry/opentelemetry.rst
Labels: sync

#1116 Pulling refs/heads/main into main
  gdi/opentelemetry/opentelemetry.rst
  gdi/opentelemetry/smart-agent/legacy-otel-mappings.rst
  gdi/opentelemetry/smart-agent/smart-agent-migration-monitors.rst
  gdi/opentelemetry/smart-agent/smart-agent-migration-process.rst
  gdi/opentelemetry/smart-agent/smart-agent-migration-to-otel-collector.rst
  gdi/opentelemetry/smart-agent/translation-tool.rst
Labels: sync

#1117 Pulling refs/heads/main into main
  logs/forward-logs.rst
Labels: sync

#1118 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-kubernetes/collector-kubernetes-intro.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-uninstall.rst
  gdi/opentelemetry/collector-linux/collector-linux-intro.rst
  gdi/opentelemetry/collector-linux/linux-uninstall.rst
  gdi/opentelemetry/collector-windows/collector-windows-intro.rst
  gdi/opentelemetry/collector-windows/windows-uninstall.rst
  gdi/opentelemetry/install-the-collector.rst
Labels: sync

#1119 Pulling refs/heads/main into main
  _includes/collector-upgrade.rst
  gdi/opentelemetry/collector-kubernetes/collector-kubernetes-intro.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-uninstall.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-upgrade.rst
  gdi/opentelemetry/collector-linux/collector-linux-intro.rst
  gdi/opentelemetry/collector-linux/linux-upgrade.rst
  gdi/opentelemetry/collector-windows/collector-windows-intro.rst
  gdi/opentelemetry/collector-windows/windows-upgrade.rst
  gdi/opentelemetry/install-the-collector.rst
  gdi/opentelemetry/otel-upgrade.rst
Labels: sync

#1120 Pulling refs/heads/main into main
  .github/workflows/vale-linter.yml
  _includes/collector-config-ootb.rst
  _includes/configuration.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-advanced.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config.rst
  gdi/opentelemetry/collector-kubernetes/metrics-ootb-k8s.rst
  gdi/opentelemetry/collector-linux/install-linux-manual.rst
  gdi/opentelemetry/collector-linux/linux-config-ootb.rst
  gdi/opentelemetry/collector-linux/linux-config.rst
  gdi/opentelemetry/collector-windows/install-windows-manual.rst
  gdi/opentelemetry/collector-windows/windows-config-ootb.rst
  gdi/opentelemetry/components/batch-processor.rst
  gdi/opentelemetry/components/fluentd-receiver.rst
  gdi/opentelemetry/components/health-check-extension.rst
  gdi/opentelemetry/components/host-metrics-receiver.rst
  gdi/opentelemetry/components/jaeger-receiver.rst
  gdi/opentelemetry/components/memory-ballast-extension.rst
  gdi/opentelemetry/components/memory-limiter-processor.rst
  gdi/opentelemetry/components/otlp-exporter.rst
  gdi/opentelemetry/components/otlp-receiver.rst
  gdi/opentelemetry/components/prometheus-receiver.rst
  gdi/opentelemetry/components/resourcedetection-processor.rst
  gdi/opentelemetry/components/signalfx-exporter.rst
  gdi/opentelemetry/components/signalfx-receiver.rst
  gdi/opentelemetry/components/splunk-apm-exporter.rst
  gdi/opentelemetry/components/splunk-hec-exporter.rst
  gdi/opentelemetry/components/zipkin-receiver.rst
  gdi/opentelemetry/components/zpages-extension.rst
  gdi/opentelemetry/data-processing.rst
  get-started/o11y-trial.rst
Labels: sync

#1121 Pulling refs/heads/main into main
  _images/get-started/k8s-java-traces-tutorial/spring-petclinic-apm.png
  _images/get-started/k8s-java-traces-tutorial/spring-petclinic-search.png
  get-started/tutorials.rst
  get-started/tutorials/k8s-java-traces-tutorial/about-k8s-java-traces-tutorial.rst
  get-started/tutorials/k8s-java-traces-tutorial/config-k8s-for-java.rst
  get-started/tutorials/k8s-java-traces-tutorial/deploy-collector-k8s-java.rst
  get-started/tutorials/k8s-java-traces-tutorial/k8s-java-view-apm.rst
Labels: sync

#1122 Pulling refs/heads/main into main
  _includes/requirements/istio.rst
  gdi/get-data-in/application/java/instrumentation/instrument-java-application.rst
  gdi/get-data-in/application/nodejs/instrumentation/instrument-nodejs-application.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-dotnet.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-k8s.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-operator.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-nodejs-k8s.rst
  gdi/opentelemetry/discovery-mode.rst
  get-started/scenario-landing.rst
Labels: sync

#1126 Add the clusterName option to documentation with description and usage examples.
  gdi/opentelemetry/collector-kubernetes/kubernetes-config.rst
Labels: external, stop-alert

#1125 Pulling refs/heads/main into main
  _includes/application-receiver-table.rst
  _includes/gdi/processor-architecture-subprocess.rst
  gdi/monitors-gitlab/gitlab.rst
  gdi/monitors-orchestration/mesos-marathon.rst
  gdi/orchestration.rst
Labels: sync

#1127 Pulling refs/heads/main into main
  gdi/monitors-gitlab/gitlab.rst
Labels: sync

#1128 Remove incorrect browser test metric (DNS time)
  synthetics/browser-test/browser-test-metrics.rst
Labels: external, stop-alert

#1130 Update sizing.rst
  gdi/opentelemetry/sizing.rst
Labels: collector, external, stop-alert

#1129 Pulling refs/heads/main into main
  admin/subscription-usage/parent-child-orgs.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-linux.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-nodejs-k8s.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-nodejs-linux.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-nodejs.rst
  gdi/opentelemetry/deployments/deployments-chef.rst
  infrastructure/metrics-pipeline/aggregate-drop-use-case.rst
  infrastructure/metrics-pipeline/data-dropping-impact.rst
  infrastructure/metrics-pipeline/metrics-pipeline-intro.rst
  infrastructure/metrics-pipeline/metrics-pipeline.rst
  infrastructure/metrics-pipeline/use-metrics-pipeline.rst
  infrastructure/mpm-arm/aggregate-drop-use-case.rst
  infrastructure/mpm-arm/data-dropping-impact.rst
  infrastructure/mpm-arm/delete-metric-ruleset.rst
  infrastructure/mpm-arm/metrics-pipeline-intro.rst
  infrastructure/mpm-arm/metrics-pipeline.rst
  infrastructure/mpm-arm/pipeline-management-use-cases.rst
  infrastructure/mpm-arm/use-MTS-aggregation-pipeline.rst
  infrastructure/mpm-arm/use-MTS-data-routing-pipeline.rst
  infrastructure/mpm-arm/use-metrics-pipeline.rst
  infrastructure/mpm-arm/view-metrics-usage-list.rst
Labels: sync

#1131 Pulling refs/heads/main into main
  gdi/monitors-databases/postgresql.rst
  gdi/monitors-hosts/collectd-df.rst
  gdi/monitors-hosts/disk.rst
  gdi/monitors-hosts/host-processload.rst
  gdi/monitors-hosts/interface.rst
Labels: sync

#1132 Pulling refs/heads/main into main
  gdi/get-data-in/compute/compute.rst
  gdi/get-data-in/compute/k8s.rst
  gdi/get-data-in/compute/linux.rst
  gdi/get-data-in/compute/windows.rst
Labels: sync

#1134 Pulling refs/heads/main into main
  gdi/get-data-in/application/java/otel-20-note.rst
Labels: sync

#1136 Pulling refs/heads/main into main
  gdi/get-data-in/application/application.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-logs.rst
  infrastructure/virtual-metrics.rst
Labels: sync

#1137 Pulling refs/heads/main into main
  _images/gdi/documentLoad.png
  admin/notif-services/jira.rst
  apm/workflows/create-workflow-rule.rst
  gdi/get-data-in/rum/browser/browser-rum-instrumentations.rst
  get-started/tutorials/k8s-infrastructure-tutorial/k8s-activate-detector.rst
  get-started/tutorials/k8s-infrastructure-tutorial/k8s-monitor-with-navigators.rst
  index.rst
  infrastructure/intro-to-infrastructure.rst
  infrastructure/quickstart-imm.rst
Labels: sync

#1138 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-kubernetes/install-k8s-addon-eks.rst
Labels: sync

#1139 Pulling refs/heads/main into main
  _images/gdi/k8s-daemonset.png
  gdi/get-data-in/application/otel-dotnet/configuration/advanced-dotnet-configuration.rst
  gdi/get-data-in/application/otel-dotnet/configuration/dotnet-metrics-attributes.rst
  gdi/get-data-in/application/otel-dotnet/dotnet-requirements.rst
  gdi/monitors-cache/memory.rst
  gdi/opentelemetry/deployment-modes.rst
Labels: sync

#1140 Pulling refs/heads/main into main
  _includes/requirements/dotnet.rst
  apm/profiling/get-data-in-profiling.rst
  apm/profiling/intro-profiling.rst
  apm/profiling/profiling-memory-metrics.rst
  apm/profiling/profiling-troubleshooting.rst
  gdi/get-data-in/application/otel-dotnet/configuration/advanced-dotnet-configuration.rst
  gdi/get-data-in/application/otel-dotnet/configuration/dotnet-metrics-attributes.rst
  gdi/get-data-in/application/otel-dotnet/get-started.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/application/otel-dotnet/troubleshooting/common-dotnet-troubleshooting.rst
  gdi/get-data-in/application/otel-dotnet/troubleshooting/migrate-signalfx-dotnet-to-dotnet-otel.rst
  gdi/opentelemetry/exposed-endpoints.rst
Labels: sync

#1141 Pulling refs/heads/main into main
  _images/splunkplatform/no-access-error.png
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-linux.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-nodejs-linux.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config.rst
  gdi/opentelemetry/deployments/deployments-linux-puppet.rst
  splunkplatform/unified-id/unified-identity.rst
Labels: sync

#1142 Pulling refs/heads/main into main
  _includes/gdi/apm-api-define-host.rst
  gdi/get-data-in/application/dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/application/go/instrumentation/instrument-go-application.rst
  gdi/get-data-in/application/java/instrumentation/instrument-java-application.rst
  gdi/get-data-in/application/nodejs/instrumentation/instrument-nodejs-application.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/application/php/instrumentation/instrument-php-application.rst
  gdi/get-data-in/application/python/instrumentation/instrument-python-application.rst
  gdi/get-data-in/application/ruby/instrumentation/instrument-ruby-application.rst
Labels: sync

#1144 Pulling refs/heads/main into main
  gdi/monitors-hosts/host-processlist.rst
  infrastructure/monitor/hosts.rst
Labels: sync

#1145 Pulling refs/heads/main into main
  gdi/monitors-databases/cassandra.rst
  gdi/monitors-databases/hadoopjmx.rst
  gdi/monitors-hosts/apache-tomcat.rst
  gdi/monitors-hosts/kafka-consumer.rst
  gdi/monitors-hosts/kafka-producer.rst
  gdi/monitors-languages/genericjmx.rst
  gdi/monitors-messaging/apache-activemq.rst
  gdi/monitors-messaging/apache-kafka.rst
Labels: sync

#1146 Pulling refs/heads/main into main
  _images/gdi/windows-monitor.png
  admin/subscription-usage/subscription-usage-overview.rst
  apm/db-query-perf/turn-on-db-perf.rst
  gdi/get-data-in/application/python/configuration/advanced-python-otel-configuration.rst
  gdi/monitors-hosts/filesystems.rst
  gdi/monitors-languages/genericjmx.rst
  gdi/opentelemetry/collector-kubernetes/collector-kubernetes-intro.rst
  gdi/opentelemetry/collector-windows/collector-windows-intro.rst
  gdi/opentelemetry/collector-windows/install-windows.rst
  gdi/opentelemetry/collector-windows/windows-config.rst
  gdi/opentelemetry/components/windowsperfcounters-receiver.rst
Labels: sync

#1147 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-console-ms.rst
Labels: sync

#1149 Pulling refs/heads/main into main
  admin/authentication/authentication-tokens/org-tokens.rst
  gdi/opentelemetry/collector-kubernetes/install-k8s.rst
  gdi/opentelemetry/collector-windows/install-windows-manual.rst
  gdi/opentelemetry/opentelemetry.rst
Labels: sync

#1148 Japanese MT post-editing 5 updated files
  locales/ja_JA/LC_MESSAGES/admin.mo
  locales/ja_JA/LC_MESSAGES/admin.po
  locales/ja_JA/LC_MESSAGES/alerts-detectors-notifications.mo
  locales/ja_JA/LC_MESSAGES/alerts-detectors-notifications.po
  locales/ja_JA/LC_MESSAGES/infrastructure.mo
  locales/ja_JA/LC_MESSAGES/infrastructure.po
  locales/ja_JA/LC_MESSAGES/logs.mo
  locales/ja_JA/LC_MESSAGES/logs.po
  locales/ja_JA/LC_MESSAGES/synthetics.mo
  locales/ja_JA/LC_MESSAGES/synthetics.po
Labels: external, stop-alert

#1151 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-windows/install-windows.rst
Labels: sync

#1152 Pulling refs/heads/main into main
  apm/apm-spans-traces/trace-analyzer.rst
Labels: sync

#1153 Pulling refs/heads/main into main
  gdi/monitors-languages/asp-dot-net.rst
  gdi/monitors-languages/microsoft-dotnet.rst
Labels: sync

#1154 Pulling refs/heads/main into main
  gdi/monitors-cloud/kong.rst
  infrastructure/metrics-pipeline/metrics-pipeline-intro.rst
Labels: sync
