Repository splunk/public-o11y-docs, pull requests merged in 2024-06, with the labels that each got.

#1377 Update apm-orientation.rst
  apm/set-up-apm/apm-orientation.rst
Labels: external

#1376 Update apm-gdi.rst
  apm/set-up-apm/apm-gdi.rst
Labels: external

#1375 Update historical-data.rst
  apm/apm-scenarios/historical-data.rst
Labels: external

#1374 Pulling refs/heads/main into main
  _images/get-started/performance-summary.png
  _images/get-started/session-details.png
  _images/infrastructure/k8s-failed-pods.png
  infrastructure/monitor/scenario-k8s-nav.rst
  synthetics/browser-test/set-up-browser-test.rst
Labels: sync

#1378 Pulling refs/heads/main into main
  admin/subscription-usage/analyze-apm-billing-usage.rst
  admin/subscription-usage/apm-billing-usage-index.rst
  admin/subscription-usage/rum-subscription-usage.rst
  admin/subscription-usage/synthetics-usage.rst
  admin/subscription-usage/view-apm-billing-reports.rst
  alerts-detectors-notifications/create-detectors-for-alerts.rst
  alerts-detectors-notifications/slo/view-slo.rst
  apm/apm-alert-visualize/alert-visualize.rst
  apm/span-tags/cmms.rst
  apm/span-tags/metricsets.rst
  docker-compose.yml
  gdi/opentelemetry/automatic-discovery/k8s/k8s-java-traces-tutorial/deploy-collector-k8s-java.rst
  gdi/opentelemetry/collector-kubernetes/collector-kubernetes-intro.rst
  synthetics/api-test/set-up-api-test.rst
  synthetics/browser-test/set-up-browser-test.rst
  synthetics/uptime-test/set-up-uptime-test.rst
Labels: sync

#1379 Pulling refs/heads/main into main
  metrics-and-metadata/metric-names.rst
  metrics-and-metadata/metrics-dimensions-mts.rst
Labels: sync

#1380 Pulling refs/heads/main into main
  gdi/get-data-in/application/java/instrumentation/java-servers-instructions.rst
Labels: sync

#1381 Pulling refs/heads/main into main
  gdi/private-connectivity/aws-privatelink.rst
Labels: sync

#1382 Pulling refs/heads/main into main
  admin/admin.rst
  admin/notif-services/slack.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/probabilistic-sampler-processor.rst
  index.rst
Labels: sync

#1383 Pulling refs/heads/main into main
  _templates/404.html
  _templates/layout.html
  _templates/search.html
  apm/apm-spans-traces/service-view.rst
Labels: sync

#1385 Update metrics-ootb-k8s.rst
  gdi/opentelemetry/collector-kubernetes/metrics-ootb-k8s.rst
Labels: collector, external, stop-alert

#1384 Pulling refs/heads/main into main
  _templates/404.html
  _templates/layout.html
  _templates/search.html
  admin/user-management/roles/roles-and-capabilities-about.rst
  admin/user-management/roles/roles-and-capabilities-table.rst
  data-visualization/charts/chart-builder.rst
  gdi/get-data-in/serverless/aws/otel-lambda-layer/advanced-configuration.rst
  gdi/get-data-in/serverless/aws/otel-lambda-layer/troubleshooting-lambda-layer.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-helm-releases.rst
  logs/scp.rst
Labels: sync

#1386 Pulling refs/heads/main into main
  gdi/monitors-cloud/kong.rst
Labels: sync

#1389 Pulling refs/heads/main into main
  _includes/requirements/collector-linux.rst
  gdi/opentelemetry/components/postgresql-receiver.rst
Labels: sync

#1390 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-apiconfig.rst
  gdi/get-data-in/connect/aws/aws-cloudformation.rst
  gdi/get-data-in/connect/aws/aws-connect-ms.rst
  gdi/get-data-in/connect/aws/aws-connect-polling.rst
  gdi/get-data-in/connect/aws/aws-console-ms.rst
  gdi/get-data-in/connect/aws/aws-post-install.rst
  gdi/get-data-in/connect/aws/aws-prereqs.rst
  gdi/get-data-in/connect/aws/aws-terraformconfig.rst
  gdi/get-data-in/connect/aws/aws-troubleshooting.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  gdi/get-data-in/get-data-in.rst
  index.rst
Labels: sync

#1391 Pulling refs/heads/main into main
  apm/span-tags/cmms.rst
  apm/span-tags/index-span-tags.rst
  apm/span-tags/metricsets.rst
  apm/span-tags/troubleshoot-mms.rst
  gdi/get-data-in/connect/aws/aws-apiconfig.rst
  gdi/get-data-in/connect/aws/aws-prereqs.rst
Labels: sync

#1392 Pulling refs/heads/main into main
  gdi/get-data-in/connect/azure/azure-connect.rst
  gdi/get-data-in/connect/azure/azure-metrics.rst
  gdi/get-data-in/connect/azure/azure-prereqs.rst
  gdi/get-data-in/connect/azure/azure.rst
Labels: sync

#1393 Pulling refs/heads/main into main
  gdi/get-data-in/application/otel-dotnet/sfx/dotnet-requirements.rst
Labels: sync

#1396 Multiple apps in the same IIS App Pool can't use appSettings for configuration
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
Labels: external, stop-alert

#1398 Update discovery-mode.rst
  gdi/opentelemetry/discovery-mode.rst
Labels: external, stop-alert

#1401 Pulling refs/heads/main into main
  requirements.txt
Labels: sync

#1400 Update admin-onboarding-guide.rst
  admin/admin-onboarding/admin-onboarding-guide.rst
Labels: external, stop-alert

#1397 Update mongodb-receiver.rst
  gdi/opentelemetry/components/mongodb-receiver.rst
Labels: external

#1399 Add Cloud Control permissions to always recommended permissions
  gdi/get-data-in/connect/aws/aws-prereqs.rst
Labels: external, stop-alert

#1403 Pulling refs/heads/main into main
  _images/admin/apm-entitlements-dashboard.png
  _images/admin/apm-subscription-usage-page.png
  _images/admin/apm-throttling-dashboard.png
  _images/admin/host-usage-diagnostics.gif
  _images/gdi/logs-collector-splunk-tutorial/splunk-web-ui-index1.png
  _images/gdi/logs-collector-splunk-tutorial/splunk-web-ui-index2.png
  admin/subscription-usage/analyze-apm-billing-usage.rst
  admin/subscription-usage/apm-billing-usage-index.rst
  admin/subscription-usage/dpm-usage.rst
  admin/subscription-usage/monitor-imm-billing-usage.rst
  admin/subscription-usage/subscription-usage-overview.rst
  admin/subscription-usage/view-apm-billing-reports.rst
  apm/db-query-perf/db-perf-reference.rst
  gdi/get-data-in/application/istio/istio.rst
  gdi/opentelemetry/install-the-collector.rst
  gdi/opentelemetry/logs-collector-splunk-tutorial/about-logs-collector-splunk-tutorial.rst
  gdi/opentelemetry/logs-collector-splunk-tutorial/collector-splunk.rst
  gdi/opentelemetry/logs-collector-splunk-tutorial/deploy-verify-environment.rst
  gdi/opentelemetry/logs-collector-splunk-tutorial/docker-compose.rst
  scenarios-tutorials/tutorial-landing.rst
Labels: sync
