Repository splunk/public-o11y-docs, pull requests merged in 2024-03, with the labels that each got.

#1215 Update upstream-collector.rst
  gdi/other-ingestion-methods/upstream-collector.rst
Labels: external, stop-alert

#1216 Pulling refs/heads/main into main
  gdi/monitors-databases/microsoft-sql-server.rst
  splunkplatform/unified-id/unified-identity.rst
Labels: sync

#1217 Pulling refs/heads/main into main
  _includes/requirements/lambda.rst
  gdi/get-data-in/serverless/aws/otel-lambda-layer/instrument-lambda-functions.rst
Labels: sync

#1218 Pulling refs/heads/main into main
  gdi/opentelemetry/components/awss3-exporter.rst
  gdi/opentelemetry/components/azureeventhub-receiver.rst
  gdi/opentelemetry/components/carbon-receiver.rst
  gdi/opentelemetry/components/cloudfoundry-receiver.rst
  gdi/opentelemetry/components/collectd-receiver.rst
  gdi/opentelemetry/components/discovery-receiver.rst
  gdi/opentelemetry/components/docker-observer-extension.rst
  gdi/opentelemetry/components/ecs-observer-extension.rst
  gdi/opentelemetry/components/file-exporter.rst
  gdi/opentelemetry/components/file-storage-extension.rst
  gdi/opentelemetry/components/host-observer-extension.rst
  gdi/opentelemetry/components/http-forwarder-extension.rst
  gdi/opentelemetry/components/journald-receiver.rst
  gdi/opentelemetry/components/kafka-exporter.rst
  gdi/opentelemetry/components/kafka-receiver.rst
  gdi/opentelemetry/components/kafkametrics-receiver.rst
  gdi/opentelemetry/components/kubernetes-events-receiver.rst
  gdi/opentelemetry/components/kubernetes-objects-receiver.rst
  gdi/opentelemetry/components/kubernetes-observer-extension.rst
  gdi/opentelemetry/components/metrics-transform-processor.rst
  gdi/opentelemetry/components/pprof-extension.rst
  gdi/opentelemetry/components/probabilistic-sampler-processor.rst
  gdi/opentelemetry/components/routing-processor.rst
  gdi/opentelemetry/components/sapm-receiver.rst
  gdi/opentelemetry/components/smartagent-extension.rst
  gdi/opentelemetry/components/statsd-receiver.rst
  gdi/opentelemetry/components/tail-sampling-processor.rst
  gdi/opentelemetry/components/windowseventlog-receiver.rst
  rum/rum-terminology-concepts.rst
Labels: sync

#1220 Pulling refs/heads/main into main
  _templates/404.html
  _templates/banner.html
  _templates/layout.html
  _templates/search.html
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-exporters.rst
  gdi/opentelemetry/components/a-components-extensions.rst
  gdi/opentelemetry/components/a-components-receivers.rst
  gdi/opentelemetry/components/ecstask-observer-extension.rst
  gdi/opentelemetry/components/loadbalancing-exporter.rst
  gdi/opentelemetry/components/mongodb-receiver.rst
  gdi/opentelemetry/components/pulsar-exporter.rst
  gdi/opentelemetry/components/sshcheck-receiver.rst
  gdi/opentelemetry/components/vcenter-receiver.rst
  gdi/opentelemetry/components/wavefront-receiver.rst
Labels: sync

#1221 Pulling refs/heads/main into main
  _includes/realm-note.rst
  admin/authentication/allow-services.rst
Labels: sync

#1222 Pulling refs/heads/main into main
  _templates/banner.html
  apm/set-up-apm/apm-gdi.rst
  gdi/get-data-in/application/application.rst
  gdi/get-data-in/application/erlang/get-started.rst
  gdi/get-data-in/application/erlang/instrument-erlang.rst
  gdi/get-data-in/application/erlang/requirements.rst
  gdi/get-data-in/application/other-languages.rst
  gdi/get-data-in/application/rust/get-started.rst
  gdi/get-data-in/application/rust/instrument-rust.rst
  gdi/get-data-in/application/rust/requirements.rst
  gdi/get-data-in/connect/aws/aws-logs.rst
  gdi/get-data-in/connect/aws/aws-troubleshooting.rst
  gdi/get-data-in/connect/aws/aws-ts-logs.rst
  gdi/get-data-in/connect/aws/aws-ts-metric-streams.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  gdi/get-data-in/connect/azure/azure-logs-ingestion.rst
  gdi/get-data-in/connect/azure/azure.rst
  gdi/get-data-in/connect/gcp/gcp-logs.rst
  gdi/get-data-in/connect/gcp/gcp.rst
  logs/lo-transition.rst
Labels: sync

#1223 Pulling refs/heads/main into main
  admin/authentication/allow-services.rst
Labels: sync

#1226 Japanese MT - index.po updated
  locales/ja_JA/LC_MESSAGES/index.mo
  locales/ja_JA/LC_MESSAGES/index.po
Labels: external

#1225 Pulling refs/heads/main into main
  _includes/requirements/collector-linux.rst
  admin/notif-services/servicenow.rst
  apm/set-up-apm/apm-gdi.rst
  gdi/get-data-in/application/application.rst
  gdi/get-data-in/application/erlang/get-started.rst
  gdi/get-data-in/application/erlang/instrument-erlang.rst
  gdi/get-data-in/application/erlang/requirements.rst
  gdi/get-data-in/application/rust/get-started.rst
  gdi/get-data-in/application/rust/instrument-rust.rst
  gdi/get-data-in/application/rust/requirements.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-dotnet-windows.rst
  gdi/opentelemetry/collector-linux/install-linux.rst
  metrics-and-metadata/relatedcontent.rst
  rum/RUM-custom-events.rst
  rum/rum-dashboards/rum-custom-dashboards.rst
Labels: sync

#1227 Pulling refs/heads/main into main
  infrastructure/monitor/aws-infra-import.rst
Labels: sync

#1228 Pulling refs/heads/main into main
  gdi/opentelemetry/opentelemetry.rst
Labels: sync

#1229 Pulling refs/heads/main into main
  gdi/opentelemetry/opentelemetry.rst
Labels: sync

#1231 Update splunkoncall.rst added colon to :strong:
  admin/notif-services/splunkoncall.rst
Labels: external, stop-alert

#1232 Pulling refs/heads/main into main
  _images/apm/trace-analyzer/TraceAnalyzerControlsDuration.png
  apm/apm-spans-traces/trace-analyzer.rst
  gdi/opentelemetry/auto-instrumentation/advanced-config-auto-instrumentation.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-k8s.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-nodejs-k8s.rst
  gdi/opentelemetry/components/redis-receiver.rst
  gdi/opentelemetry/zero-config.rst
Labels: sync

#1233 Pulling refs/heads/main into main
  gdi/opentelemetry/components/smartagent-extension.rst
Labels: sync

#1230 Update splunkoncall.rst
  admin/notif-services/splunkoncall.rst
Labels: external, stop-alert

#1235 Pulling refs/heads/main into main
  apm/apm-data-links/apm-create-data-links.rst
  apm/apm-data-links/apm-use-data-links.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-dotnet-k8s.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-k8s.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-nodejs-k8s.rst
  gdi/opentelemetry/collector-kubernetes/collector-kubernetes-intro.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-support.rst
  gdi/opentelemetry/collector-kubernetes/troubleshoot-k8s-container.rst
  gdi/opentelemetry/collector-kubernetes/troubleshoot-k8s.rst
  gdi/opentelemetry/troubleshooting.rst
  get-started/tutorials/aws-tutorial/about-aws-tutorial.rst
  get-started/tutorials/k8s-infrastructure-tutorial/about-k8s-tutorial.rst
  get-started/tutorials/k8s-java-traces-tutorial/config-k8s-for-java.rst
  get-started/tutorials/k8s-java-traces-tutorial/deploy-collector-k8s-java.rst
  metrics-and-metadata/link-metadata-to-content.rst
Labels: sync

#1236 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-troubleshooting.rst
  infrastructure/monitor/aws-infra-metadata.rst
Labels: sync

#1237 Pulling refs/heads/main into main
  _includes/realm-note.rst
  gdi/get-data-in/application/php/instrument-php-application.rst
  get-started/tutorials/collector-configuration-tutorial/about-collector-config-tutorial.rst
  get-started/tutorials/collector-configuration-tutorial/collector-config-tutorial-edit.rst
  get-started/tutorials/collector-configuration-tutorial/collector-config-tutorial-start.rst
  get-started/tutorials/collector-configuration-tutorial/collector-config-tutorial-troubleshoot.rst
  synthetics/browser-test/browser-test-metrics.rst
  synthetics/uptime-test/set-up-uptime-test.rst
Labels: sync

#1238 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-prereqs.rst
  gdi/get-data-in/integrations.rst
Labels: sync

#1240 fixed typo (changed Azure to GCP)
  gdi/get-data-in/connect/gcp/gcp.rst
Labels: external

#1241 Pulling refs/heads/main into main
  _includes/requirements/java.rst
Labels: sync

#1242 Pulling refs/heads/main into main
  _images/get-started/k8s-demo.png
  _images/get-started/logs-cloud.png
  data-visualization/charts/data-resolution-and-rollups.rst
  gdi/get-data-in/application/cpp/get-started-cpp.rst
  gdi/get-data-in/application/cpp/migrate-from-splunk-cpp.rst
  gdi/get-data-in/application/ruby/distro/get-started.rst
  gdi/get-data-in/application/ruby/get-started-ruby.rst
  gdi/get-data-in/application/ruby/migrate-from-splunk-ruby.rst
  gdi/monitors-hosts/elasticsearch.rst
  gdi/opentelemetry/components/splunk-hec-exporter.rst
  get-started/tutorials.rst
  get-started/tutorials/collector-configuration-tutorial-k8s/about-collector-config-tutorial.rst
  get-started/tutorials/collector-configuration-tutorial-k8s/collector-config-tutorial-edit.rst
  get-started/tutorials/collector-configuration-tutorial-k8s/collector-config-tutorial-start.rst
Labels: sync

#1243 Pulling refs/heads/main into main
  references/glossary.rst
Labels: sync

#1244 Pulling refs/heads/main into main
  gdi/get-data-in/integrations.rst
  get-started/tutorials/collector-configuration-tutorial-k8s/collector-config-tutorial-edit.rst
Labels: sync

#1245 Pulling refs/heads/main into main
  _includes/requirements/collector-linux.rst
  gdi/get-data-in/application/cpp/instrument-cpp.rst
  gdi/opentelemetry/components/attributes-processor.rst
  gdi/opentelemetry/components/span-processor.rst
Labels: sync

#1246 Pulling refs/heads/main into main
  _static/custom.css
  _static/signalfx-includes.css
  _static/splunk-logo-dark.svg
  _static/splunk-logo-white.svg
  _templates/banner.html
Labels: sync

#1247 Pulling refs/heads/main into main
  gdi/get-data-in/application/otel-dotnet/get-started.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/azure-webapps.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
Labels: sync

#1248 Pulling refs/heads/main into main
  gdi/get-data-in/application/otel-dotnet/instrumentation/azure-webapps.rst
  gdi/opentelemetry/auto-instrumentation/auto-instrumentation-java-k8s.rst
  gdi/opentelemetry/collector-kubernetes/install-k8s.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config.rst
  gdi/opentelemetry/components/mysql-receiver.rst
Labels: sync

#1249 Pulling refs/heads/main into main
  _images/apm/profiling/frame-table.png
  _images/apm/profiling/group-frames.gif
  _images/apm/profiling/memory-profiling-metrics.png
  _images/apm/profiling/memory-profiling-metrics_1.png
  _images/apm/profiling/prof-flame-graph.png
  _images/apm/profiling/profiling-bars.png
  _images/apm/profiling/profiling-bars3.png
  _images/apm/profiling/profiling-class-file-line.png
  _images/apm/profiling/profiling-filters.png
  _images/apm/profiling/profiling-stack-frames.png
  _images/apm/profiling/profiling-thread-info.png
  apm/profiling/profiling-memory-metrics.rst
  apm/profiling/using-the-flamegraph.rst
  gdi/opentelemetry/auto-instrumentation/dotnet/auto-instrumentation-dotnet-k8s.rst
  gdi/opentelemetry/auto-instrumentation/dotnet/auto-instrumentation-dotnet-windows.rst
  gdi/opentelemetry/auto-instrumentation/dotnet/auto-instrumentation-dotnet.rst
  gdi/opentelemetry/auto-instrumentation/java/auto-instrumentation-java-k8s.rst
  gdi/opentelemetry/auto-instrumentation/java/auto-instrumentation-java-linux.rst
  gdi/opentelemetry/auto-instrumentation/java/auto-instrumentation-java.rst
  gdi/opentelemetry/auto-instrumentation/nodejs/auto-instrumentation-nodejs-k8s.rst
  gdi/opentelemetry/auto-instrumentation/nodejs/auto-instrumentation-nodejs-linux.rst
  gdi/opentelemetry/auto-instrumentation/nodejs/auto-instrumentation-nodejs.rst
  gdi/opentelemetry/zero-config.rst
  synthetics/api-test/set-up-api-test.rst
  synthetics/browser-test/set-up-browser-test.rst
  synthetics/uptime-test/set-up-uptime-test.rst
Labels: sync

#1250 Pulling refs/heads/main into main
  Makefile
  _images/logs/chrome-secure1A.png
  _images/logs/chrome-secure2A.png
  _images/logs/chrome-secure3A.png
  _includes/requirements/php.rst
  gdi/get-data-in/application/php/instrument-php-application.rst
  gdi/get-data-in/application/ruby/instrument-ruby.rst
  logs/intro-logconnect.rst
  logs/scp.rst
  logs/set-up-logconnect.rst
Labels: sync

#1251 Pulling refs/heads/main into main
  _includes/gdi/application-receiver-table.rst
  _includes/gdi/otel-receivers-table.rst
  gdi/get-data-in/compute/compute.rst
  gdi/get-data-in/integrations.rst
  gdi/index.rst
  gdi/integrations-list.rst
  gdi/integrations/cloud-aws.rst
  gdi/integrations/cloud-azure.rst
  gdi/integrations/cloud-gcp.rst
  gdi/integrations/community-integrations.rst
  gdi/opentelemetry/components/a-components-receivers.rst
  gdi/opentelemetry/smart-agent/monitors-common-config.rst
  gdi/opentelemetry/smart-agent/smart-agent-migration-to-otel-collector.rst
  gdi/requirements.rst
  index.rst
Labels: sync

#1253 Pulling refs/heads/main into main
  infrastructure/metrics-pipeline/metrics-pipeline-intro.rst
Labels: sync

#1252 Update kubernetes-config-advanced.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-advanced.rst
Labels: gdi, collector, external, stop-alert

#1254 Raise an error if the collector was already uninstalled
  gdi/opentelemetry/collector-windows/windows-uninstall.rst
Labels: gdi, collector, external, stop-alert

#1255 Pulling refs/heads/main into main
  gdi/opentelemetry/components/cloudfoundry-receiver.rst
  metrics-and-metadata/data-model.rst
Labels: sync

#1256 Update instrument-dotnet-application.rst
  gdi/get-data-in/application/otel-dotnet/sfx/instrumentation/instrument-dotnet-application.rst
Labels: gdi, instrumentation, external, stop-alert

#1257 Pulling refs/heads/main into main
  gdi/opentelemetry/components/attributes-processor.rst
  gdi/opentelemetry/components/metrics-transform-processor.rst
Labels: sync

#1258 Pulling refs/heads/main into main
  gdi/get-data-in/application/otel-dotnet/instrumentation/azure-webapps.rst
Labels: sync

#1259 Pulling refs/heads/main into main
  alerts-detectors-notifications/create-detectors-for-alerts.rst
  gdi/get-data-in/connect/aws/aws-prereqs.rst
  gdi/integrations/cloud-aws.rst
  logs/scp.rst
  logs/set-up-logconnect.rst
Labels: sync

#1260 Pulling refs/heads/main into main
  gdi/opentelemetry/auto-instrumentation/java/auto-instrumentation-java-linux.rst
  logs/logs.rst
Labels: sync

#1263 Remove duplicated permissions from GCP integration setup instructions
  gdi/get-data-in/connect/gcp/gcp.rst
Labels: external

#1262 Update intro-profiling.rst
  apm/profiling/intro-profiling.rst
Labels: external, stop-alert

#1264 Update advanced-python-otel-configuration.rst
  gdi/get-data-in/application/python/configuration/advanced-python-otel-configuration.rst
Labels: external, stop-alert

#1265 Pulling refs/heads/main into main
  apm/apm-data-links/apm-create-data-links.rst
Labels: sync

#1266 Pulling refs/heads/main into main
  gdi/get-data-in/connect/azure/azure.rst
Labels: sync

#1267 Pulling refs/heads/main into main
  gdi/opentelemetry/deployment-modes.rst
Labels: sync

#1268 Pulling refs/heads/main into main
  _images/apm/spans-traces/span-search-span-links.gif
  _includes/collector-env-vars.rst
  _includes/collector-upgrade-memory-ballast.rst
  _includes/collector-upgrade.rst
  apm/apm-spans-traces/span-search.rst
  gdi/opentelemetry/collector-linux/install-linux-manual.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/memory-ballast-extension.rst
  gdi/opentelemetry/components/resourcedetection-processor.rst
  gdi/opentelemetry/deployments/deployments-chef.rst
  gdi/opentelemetry/deployments/deployments-linux-ansible.rst
  gdi/opentelemetry/deployments/deployments-linux-puppet.rst
  gdi/opentelemetry/deployments/deployments-nomad.rst
  gdi/opentelemetry/deployments/deployments-salt.rst
  gdi/opentelemetry/deployments/deployments-windows-ansible.rst
  gdi/opentelemetry/deployments/deployments-windows-puppet.rst
  gdi/opentelemetry/smart-agent/smart-agent-migration-process.rst
Labels: sync
