Repository splunk/public-o11y-docs, pull requests merged in 2024-08, with the labels that each got.

#1471 Update traces-spans.rst
  apm/apm-spans-traces/traces-spans.rst
Labels: external, stop-alert

#1470 Performed a quick grammar/spell-check of the get started pages.
  get-started/contribute.rst
  get-started/download-mobile.rst
  get-started/education-resources.rst
  get-started/o11y-architecture.rst
  get-started/o11y.rst
Labels: external, stop-alert

#1469 Update manage-navigator-dashbds.rst
  infrastructure/manage-navigator-dashbds.rst
Labels: external, stop-alert

#1466 Update scenario-collector.rst
  scenarios-tutorials/scenario-collector.rst
Labels: external, stop-alert

#1472 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-kubernetes/install-k8s.rst
Labels: sync

#1473 Pulling refs/heads/main into main
  _images/images-slo/custom-metric-slo-scenario.png
  alerts-detectors-notifications/slo/create-slo.rst
  alerts-detectors-notifications/slo/custom-metric-scenario.rst
  alerts-detectors-notifications/slo/slo-intro.rst
Labels: sync

#1474 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-kubernetes/collector-kubernetes-intro.rst
  gdi/opentelemetry/collector-kubernetes/k8s-infrastructure-tutorial/about-k8s-tutorial.rst
  gdi/opentelemetry/collector-kubernetes/k8s-troubleshooting/troubleshoot-k8s-container.rst
  gdi/opentelemetry/collector-kubernetes/k8s-troubleshooting/troubleshoot-k8s-landing.rst
  gdi/opentelemetry/collector-kubernetes/k8s-troubleshooting/troubleshoot-k8s-missing-metrics.rst
  gdi/opentelemetry/collector-kubernetes/k8s-troubleshooting/troubleshoot-k8s-sizing.rst
  gdi/opentelemetry/collector-kubernetes/k8s-troubleshooting/troubleshoot-k8s.rst
  gdi/opentelemetry/components/kubelet-stats-receiver.rst
Labels: sync

#1475 Pulling refs/heads/main into main
  admin/notif-services/splunkoncall.rst
  sp-oncall/admin/sso/single-sign-sso.rst
  sp-oncall/admin/sso/sp-sso-google.rst
  sp-oncall/admin/sso/sp-sso-users.rst
  sp-oncall/spoc-integrations/catchpoint-integration.rst
  sp-oncall/spoc-integrations/grafana-integration.rst
  sp-oncall/spoc-integrations/jira-app-integration-guide-victorops.rst
  sp-oncall/spoc-integrations/setup-single-sign-on-sso-and-user-provisioning-with-okta-beta.rst
  sp-oncall/spoc-integrations/splunking-victorops-data.rst
Labels: sync

#1476 Pulling refs/heads/main into main
  _images/apm/set-up-apm/set-up-apm-01-1.png
  _images/apm/set-up-apm/set-up-apm-01.png
  _images/apm/span-tags/tag-spotlight-01.png
  _images/apm/span-tags/tag-spotlight-fy25pi2.png
  _images/rum/rum-metricset.png
  admin/notif-services/admin-notifs-index.rst
  admin/notif-services/splunkplatform.rst
  apm/apm-data-links/apm-create-data-links.rst
  apm/apm-data-links/apm-use-data-links.rst
  apm/apm-scenarios/troubleshoot-tag-spotlight.rst
  apm/apm-spans-traces/inferred-services.rst
  apm/apm-spans-traces/service-view.rst
  apm/set-up-apm/apm-orientation.rst
  apm/span-tags/cmms.rst
  apm/span-tags/index-span-tags.rst
  apm/span-tags/metricsets.rst
  apm/span-tags/tag-spotlight.rst
  apm/span-tags/troubleshoot-mms.rst
  data-visualization/navigate-with-data-links.rst
  gdi/get-data-in/rum/browser/manual-rum-browser-instrumentation.rst
  gdi/get-data-in/rum/browser/rum-browser-data-model.rst
  infrastructure/terms-concepts.rst
  infrastructure/use-navigators.rst
  metrics-and-metadata/link-metadata-to-content.rst
  rum/rum-alerts.rst
  rum/rum-custom-indexed-tags.rst
  rum/rum-scenario-library/scenario-monitoring.rst
  rum/rum-tag-search.rst
  rum/rum-terminology-concepts.rst
  synthetics/api-test/api-test-metrics.rst
  synthetics/browser-test/browser-test-metrics.rst
  synthetics/browser-test/set-up-browser-test.rst
  synthetics/test-config/rum-synth.rst
  synthetics/test-config/test-config.rst
Labels: sync

#1478 Pulling refs/heads/main into main
  admin/references/data-retention.rst
  gdi/private-connectivity/aws-privatelink.rst
  get-started/service-description.rst
  infrastructure/retention.rst
  logs/set-up-logconnect.rst
  synthetics/test-config/SynPublicLocations.zip
  synthetics/test-config/eu1-public-locations.csv
  synthetics/test-config/eu2-public-locations.csv
  synthetics/test-config/public-locations.rst
Labels: sync

#1479 Pulling refs/heads/main into main
  gdi/opentelemetry/discovery-mode.rst
Labels: sync

#1480 Pulling refs/heads/main into main
  gdi/monitors-cloudfoundry/cloudfoundry-firehose-nozzle.rst
  gdi/monitors-databases/microsoft-sql-server.rst
  gdi/monitors-hosts/apache-httpserver.rst
  gdi/monitors-hosts/health-checker.rst
  gdi/monitors-hosts/http.rst
  gdi/monitors-hosts/kafka-consumer.rst
  gdi/monitors-hosts/kafka-producer.rst
  gdi/monitors-messaging/rabbitmq.rst
  logs/scp.rst
Labels: sync

#1482 Update create-workflow-rule.rst
  apm/workflows/create-workflow-rule.rst
Labels: external

#1481 Pulling refs/heads/main into main
  gdi/get-data-in/application/php/sfx/instrumentation/instrument-php-application.rst
Labels: sync

#1484 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-logs.rst
  gdi/opentelemetry/collector-linux/install-linux.rst
  gdi/opentelemetry/collector-windows/install-windows.rst
  gdi/opentelemetry/collector-windows/windows-config.rst
  gdi/opentelemetry/components/fluentd-receiver.rst
  gdi/opentelemetry/install-the-collector.rst
  gdi/opentelemetry/opentelemetry.rst
Labels: sync

#1485 Pulling refs/heads/main into main
  _includes/gdi/otel-receivers-table.rst
  gdi/get-data-in/application/php/sfx/php-requirements.rst
  gdi/monitors-hosts/elasticsearch-query.rst
  gdi/monitors-hosts/elasticsearch.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-receivers.rst
  gdi/opentelemetry/components/elasticsearch-receiver.rst
  infrastructure/monitor/aws-infra-import.rst
Labels: sync

#1486 Pulling refs/heads/main into main
  _includes/gdi/otel-receivers-table.rst
  gdi/monitors-hosts/haproxy.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-receivers.rst
  gdi/opentelemetry/components/haproxy-receiver.rst
Labels: sync

#1488 Pulling refs/heads/main into main
  _includes/gdi/available-aws.rst
  gdi/integrations/cloud-aws.rst
Labels: sync

#1487 Update slack-integration-guide.rst
  sp-oncall/spoc-integrations/slack-integration-guide.rst
Labels: admin, external, stop-alert

#1489 Pulling refs/heads/main into main
  sp-oncall/spoc-integrations/slack-integration-guide.rst
Labels: sync

#1490 Pulling refs/heads/main into main
  gdi/monitors-orchestration/kubernetes-scheduler.rst
Labels: sync

#1491 Pulling refs/heads/main into main
  _includes/collector-components.rst
  apm/apm-spans-traces/inferred-services.rst
  apm/span-tags/metricsets.rst
  gdi/opentelemetry/collector-kubernetes/collector-kubernetes-intro.rst
  gdi/opentelemetry/collector-kubernetes/install-k8s.rst
  gdi/opentelemetry/collector-kubernetes/otel-commands.rst
  gdi/opentelemetry/install-the-collector.rst
  gdi/opentelemetry/opentelemetry.rst
  sp-oncall/spoc-integrations/servicenow-integration.rst
Labels: sync

#1492 Pulling refs/heads/main into main
  gdi/opentelemetry/deployment-modes.rst
Labels: sync

#1493 Pulling refs/heads/main into main
  gdi/get-data-in/application/java/instrumentation/connect-traces-logs.rst
  gdi/private-connectivity/aws-privatelink.rst
Labels: sync

#1494 Pulling refs/heads/main into main
  admin/references/per-product-limits.rst
  admin/references/system-limits/sys-limits-infra-details.rst
  admin/references/system-limits/sys-limits-infra.rst
Labels: sync

#1495 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/get-awstoc.rst
  gdi/get-data-in/connect/azure/azure.rst
  gdi/get-data-in/connect/gcp/gcp.rst
  infrastructure/monitor/aws.rst
  infrastructure/monitor/gcp.rst
Labels: sync

#1497 Pulling refs/heads/main into main
  _includes/logs/loc-availability.rst
  admin/notif-services/admin-notifs-index.rst
  gdi/opentelemetry/collector-kubernetes/collector-configuration-tutorial-k8s/about-collector-config-tutorial.rst
  gdi/opentelemetry/collector-kubernetes/collector-configuration-tutorial-k8s/collector-config-tutorial-edit.rst
  gdi/opentelemetry/collector-kubernetes/collector-kubernetes-intro.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-add.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-advanced.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config.rst
  logs/forward-logs.rst
Labels: sync

#1498 Pulling refs/heads/main into main
  gdi/opentelemetry/collector-kubernetes/k8s-troubleshooting/troubleshoot-k8s-container.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-advanced.rst
  gdi/opentelemetry/components/elasticsearch-receiver.rst
  infrastructure/metrics-pipeline/metrics-pipeline-intro.rst
  infrastructure/network-explorer/network-explorer-setup.rst
  logs/set-up-logconnect.rst
  rum/rum-rules.rst
Labels: sync

#1477 Update autodetect-list.rst
  alerts-detectors-notifications/autodetect/autodetect-list.rst
Labels: external, stop-alert

#1499 Update oracledb-receiver.rst
  gdi/opentelemetry/components/oracledb-receiver.rst
Labels: external, stop-alert

#1501 Update org-metrics.rst
  admin/org-metrics.rst
Labels: external, stop-alert

#1503 SYN-4307: Updates/corrections for Synthetics browser test advanced settings
  synthetics/browser-test/set-up-browser-test.rst
Labels: external

#1502 Pulling refs/heads/main into main
  gdi/opentelemetry/data-processing.rst
  gdi/opentelemetry/opentelemetry.rst
  gdi/opentelemetry/tags.rst
  splunkplatform/unified-id/unified-identity.rst
  synthetics/browser-test/set-up-browser-test.rst
  synthetics/browser-test/set-up-transactional-browser-test.rst
Labels: sync

#1504 Pulling refs/heads/main into main
  gdi/get-data-in/application/otel-dotnet/get-started.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/dotnet-pre-checks.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
Labels: sync

#1505 Pulling refs/heads/main into main
  gdi/monitors-hosts/nginx.rst
Labels: sync

#1500 Add --log-exporter option to the linux installer script
  gdi/opentelemetry/collector-linux/install-linux.rst
Labels: external

#1506 Pulling refs/heads/main into main
  gdi/monitors-hosts/kafka-consumer.rst
  gdi/monitors-hosts/kafka-producer.rst
  gdi/monitors-languages/genericjmx.rst
  gdi/monitors-languages/jmx.rst
  gdi/monitors-messaging/apache-kafka.rst
  gdi/opentelemetry/components/jmx-receiver.rst
  sp-oncall/spoc-integrations/observium-integration.rst
Labels: sync

#1508 Pulling refs/heads/main into main
  admin/notif-services/microsoftteams.rst
  index.rst
Labels: sync

#1507 add auto instrumentation options for ansible, chef, puppet, and salt
  gdi/opentelemetry/collector-linux/deployments-linux-ansible.rst
  gdi/opentelemetry/collector-linux/deployments-linux-chef.rst
  gdi/opentelemetry/collector-linux/deployments-linux-puppet.rst
  gdi/opentelemetry/collector-linux/deployments-linux-salt.rst
Labels: external, stop-alert

#1509 Pulling refs/heads/main into main
  _images/rum/metric-set-left-nav.png
  _includes/synthetics/metricset-def.rst
  index.rst
  rum/rum-custom-indexed-tags.rst
Labels: sync
