Repository splunk/public-o11y-docs, pull requests merged in 2025-01, with the labels that each got.

#1637 Update discovery-mode.rst
  gdi/opentelemetry/discovery-mode.rst
Labels: collector, external, stop-alert

#1633 Pulling refs/heads/main into main
  _images/synthetics/detector-one.png
  _templates/layout.html
  apm/set-up-apm/environments.rst
  conf.py
  data-visualization/charts/chart-builder.rst
  data-visualization/charts/chart-options.rst
  data-visualization/charts/chart-types.rst
  data-visualization/charts/charts.rst
  data-visualization/charts/create-charts.rst
  data-visualization/charts/simple-charts-dashboards.rst
  data-visualization/dashboards/dashboard-create-customize.rst
  data-visualization/dashboards/dashboard-group.rst
  data-visualization/dashboards/dashboards-add.rst
  gdi/get-data-in/application/java/java-otel-requirements.rst
  gdi/opentelemetry/components/apache-spark-receiver.rst
  gdi/opentelemetry/components/resource-processor.rst
  get-started/get-started-guide/get-started-guide.rst
  get-started/get-started-guide/initial-rollout.rst
  get-started/service-description.rst
  index.rst
  metrics-and-metadata/metric-categories.rst
  metrics-and-metadata/metrics-finder-metadata-catalog.rst
  sp-oncall/on-call-schedules/schedule-examples.rst
  splunkplatform/unified-id/unified-identity.rst
  synthetics/api-test/api-test-metrics.rst
  synthetics/api-test/api-test.rst
  synthetics/test-config/built-in-variables.rst
  synthetics/test-config/devices.rst
  synthetics/test-config/global-variables.rst
  synthetics/test-config/private-locations.rst
  synthetics/test-config/public-locations.rst
  synthetics/test-config/syn-downtimes.rst
  synthetics/test-config/synth-alerts.rst
  synthetics/test-config/test-config.rst
  synthetics/test-status/test-kpis.rst
  synthetics/test-status/test-status.rst
  synthetics/uptime-test/uptime-test.rst
Labels: sync

#1638 Pulling refs/heads/main into main
  gdi/opentelemetry/components/nginx-receiver.rst
Labels: sync

#1639 Update components.rst to correct aggretation to aggregation
  gdi/opentelemetry/components.rst
Labels: external, stop-alert

#1641 Update gain-insights-through-chart-analytics.rst fixed numbering
  data-visualization/charts/gain-insights-through-chart-analytics.rst
Labels: external, stop-alert

#1640 Pulling refs/heads/main into main
  gdi/opentelemetry/otel-other/otel-other-landing.rst
  gdi/opentelemetry/otel-other/other-ingestion-collectd.rst
  gdi/opentelemetry/otel-other/telegraf.rst
  sp-oncall/spoc-integrations/sensu-integration.rst
  synthetics/key-concepts.rst
  synthetics/test-config/private-locations.rst
Labels: sync

#1642 Pulling refs/heads/main into main
  _includes/gdi/collector-available-exporters.rst
  _includes/gdi/collector-available-extensions.rst
  _includes/gdi/collector-available-processors.rst
  _includes/gdi/otel-receivers-table.rst
  gdi/opentelemetry/components.rst
  gdi/opentelemetry/components/a-components-connectors.rst
  gdi/opentelemetry/components/a-components-exporters.rst
  gdi/opentelemetry/components/a-components-extensions.rst
  gdi/opentelemetry/components/a-components-processors.rst
  gdi/opentelemetry/components/a-components-receivers.rst
Labels: sync

#1643 Pulling refs/heads/main into main
  _includes/collector-config-ootb.rst
  apm/apm-spans-traces/span-formats.rst
  gdi/get-data-in/application/otel-dotnet/sfx/troubleshooting/common-dotnet-troubleshooting.rst
  gdi/monitors-cloud/heroku.rst
  gdi/opentelemetry/collector-addon/collector-addon-install.rst
  gdi/opentelemetry/collector-kubernetes/k8s-troubleshooting/troubleshoot-k8s-sizing.rst
  gdi/opentelemetry/components/attributes-processor.rst
  gdi/opentelemetry/components/filter-processor.rst
  gdi/opentelemetry/components/groupbyattrs-processor.rst
  gdi/opentelemetry/components/jaeger-receiver.rst
  gdi/opentelemetry/components/logging-exporter.rst
  gdi/opentelemetry/components/otlphttp-exporter.rst
  gdi/opentelemetry/components/sapm-receiver.rst
  gdi/opentelemetry/components/splunk-apm-exporter.rst
  gdi/opentelemetry/components/transform-processor.rst
  gdi/opentelemetry/deployment-modes.rst
  gdi/opentelemetry/exposed-endpoints.rst
  gdi/opentelemetry/metrics-internal-collector.rst
  gdi/opentelemetry/smart-agent/smart-agent-migration-monitors.rst
  metrics-and-metadata/relatedcontent-collector-apm.rst
Labels: sync

#1644 Pulling refs/heads/main into main
  _includes/gdi/auto-discovery-intro.rst
  gdi/opentelemetry/automatic-discovery/discovery-kubernetes.rst
  gdi/opentelemetry/automatic-discovery/discovery-linux.rst
  gdi/opentelemetry/automatic-discovery/discovery-windows.rst
Labels: sync

#1646 Pulling refs/heads/main into main
  gdi/get-data-in/connect/gcp/gcp-connect.rst
  metrics-and-metadata/relatedcontent.rst
Labels: sync

#1648 Pulling refs/heads/main into main
  _includes/requirements/collector-windows.rst
  gdi/opentelemetry/collector-windows/deployments-windows-ansible.rst
  gdi/opentelemetry/collector-windows/deployments-windows-chef.rst
  metrics-and-metadata/relatedcontent.rst
  synthetics/test-config/private-locations.rst
Labels: sync

#1650 Pulling refs/heads/main into main
  _includes/gdi/available-aws.rst
  gdi/opentelemetry/collector-kubernetes/metrics-ootb-k8s.rst
Labels: sync

#1652 Update export-and-share-charts.rst
  data-visualization/charts/export-and-share-charts.rst
Labels: external

#1653 Add new k8s automatic-discovery helm chart configuration `operatorcrds.install`
  gdi/opentelemetry/automatic-discovery/k8s/k8s-advanced-config.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-backend.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-java-traces-tutorial/config-k8s-for-java.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config.rst
Labels: external, stop-alert

#1654 Update intro-to-rum.rst
  rum/intro-to-rum.rst
Labels: external, stop-alert

#1655 Update manual-rum-browser-instrumentation.rst
  gdi/get-data-in/rum/browser/manual-rum-browser-instrumentation.rst
Labels: external, stop-alert

#1657 Fixed capitalization rum-session-replay.rst
  rum/rum-session-replay.rst
Labels: external
