Repository splunk/public-o11y-docs, pull requests merged in 2025-03, with the labels that each got.

#1697 Update chrony-receiver.rst
  gdi/opentelemetry/components/chrony-receiver.rst
Labels: external, stop-alert

#1693 feat(rum): add new API for rum browser agent
  gdi/get-data-in/rum/browser/configure-rum-browser-instrumentation.rst
Labels: external, stop-alert

#1702 Update action value for correctness
  gdi/opentelemetry/components/otlphttp-exporter.rst
Labels: external, stop-alert

#1701 Update centralized-rbac.rst
  splunkplatform/centralized-rbac.rst
Labels: external, stop-alert

#1703 PHP EOS
  gdi/get-data-in/application/php/sfx/sfx-instrumentation.rst
Labels: external, stop-alert

#1705 Update conf.py
  conf.py
Labels: external

#1704 Update dotnet manual instrumentation instructions
  gdi/get-data-in/application/otel-dotnet/instrumentation/manual-dotnet-instrumentation.rst
Labels: external, stop-alert

#1706 Remove note about retired SignalFx .NET instrumentation
  gdi/opentelemetry/automatic-discovery/windows/windows-backend.rst
Labels: external, stop-alert

#1699 Pulling refs/heads/main into main
  .github/workflows/heretto-reminder.yml
  _templates/404.html
  _templates/layout.html
  _templates/search.html
  gdi/get-data-in/application/otel-dotnet/instrumentation/manual-dotnet-instrumentation.rst
  gdi/get-data-in/connect/aws/aws-connect-polling.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  gdi/get-data-in/rum/browser/configure-rum-browser-instrumentation.rst
  index.rst
  infrastructure/metrics-pipeline/use-case-archive.rst
  infrastructure/monitor/k8s-nav.rst
  sp-oncall/admin/get-started/team-dashboard.rst
  sp-oncall/admin/sso/sp-sso-adfs.rst
  sp-oncall/admin/sso/sp-sso-google.rst
  sp-oncall/admin/sso/sp-sso-okta.rst
  sp-oncall/alerts/team-escalation-policy.rst
  sp-oncall/incidents/incident-pane.rst
  sp-oncall/notifications/call-notification-numbers.rst
  sp-oncall/reports/post-incident-review.rst
  splunkplatform/unified-id/unified-identity.rst
  synthetics/api-test/api-test.rst
Labels: sync

#1698 Update sql-query-receiver.rst
  gdi/opentelemetry/components/sqlquery-receiver.rst
Labels: external, stop-alert

#1711 Pulling refs/heads/main into main
  _images/synthetics/auth-basic-html-steps.png
  admin/references/system-limits/sys-limits-infra.rst
  gdi/opentelemetry/support-checklist.rst
  synthetics/test-config/auth.rst
Labels: sync

#1712 Pulling refs/heads/main into main
  _includes/gdi/troubleshoot-zeroconfig-k8s.rst
  _includes/requirements/collector-linux.rst
  admin/authentication/SSO/sso.rst
  admin/user-management/roles/users-assign-roles.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-backend.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-java-traces-tutorial/config-k8s-for-java.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-helm-releases.rst
  gdi/opentelemetry/collector-kubernetes/metrics-ootb-k8s.rst
  gdi/opentelemetry/collector-linux/deployments-linux-ansible.rst
  gdi/opentelemetry/collector-linux/deployments-linux-chef.rst
  gdi/opentelemetry/collector-linux/deployments-linux-puppet.rst
  gdi/opentelemetry/collector-linux/deployments-linux-salt.rst
Labels: sync

#1715 Updated otel linux requirements - removed Oracle 7
  _includes/requirements/collector-linux.rst
  gdi/opentelemetry/collector-linux/deployments-linux-ansible.rst
  gdi/opentelemetry/collector-linux/deployments-linux-chef.rst
  gdi/opentelemetry/collector-linux/deployments-linux-puppet.rst
  gdi/opentelemetry/collector-linux/deployments-linux-salt.rst
Labels: external

#1717 Pulling refs/heads/main into main
  gdi/opentelemetry/automatic-discovery/linux/linux-advanced-config.rst
  gdi/opentelemetry/automatic-discovery/linux/linux-backend.rst
  gdi/opentelemetry/install-the-collector.rst
Labels: sync
