Repository splunk/public-o11y-docs, pull requests merged in 2025-02, with the labels that each got.

#1659 Pulling refs/heads/main into main
  gdi/opentelemetry/components/otlphttp-exporter.rst
  gdi/opentelemetry/components/span-metrics-connector.rst
Labels: sync

#1660 Pulling refs/heads/main into main
  admin/authentication/authentication-tokens/manage-usage.rst
  alerts-detectors-notifications/alerts-and-detectors/autodetect/autodetect-customize.rst
  alerts-detectors-notifications/alerts-and-detectors/autodetect/autodetect-intro.rst
  alerts-detectors-notifications/alerts-and-detectors/autodetect/autodetect-subscribe-mute-turn-off.rst
  alerts-detectors-notifications/alerts-and-detectors/autodetect/autodetect-view.rst
  alerts-detectors-notifications/alerts-and-detectors/create-detectors-for-alerts.rst
  alerts-detectors-notifications/alerts-and-detectors/scenarios-detectors-alerts/find-detectors.rst
  alerts-detectors-notifications/alerts-and-detectors/scenarios-detectors-alerts/monitor-server-latency.rst
  alerts-detectors-notifications/alerts-and-detectors/scenarios-detectors-alerts/troubleshoot-noisy-detectors.rst
  alerts-detectors-notifications/alerts-and-detectors/view-detectors.rst
  apm/span-tags/migrate-apm-custom-reporting.rst
  references/glossary.rst
  rum/rum-dashboards/rum-built-in-dashboards.rst
  synthetics/syn-ottb-dashboards.rst
Labels: sync

#1634 Docs suggest only gateway collectors can support proxy settings
  admin/authentication/allow-services.rst
Labels: external, stop-alert

#1661 Pulling refs/heads/main into main
  admin/authentication/allow-services.rst
  data-visualization/charts/export-and-share-charts.rst
  locales/ja_JA/LC_MESSAGES/slo.po
  metrics-and-metadata/metric-names.rst
Labels: sync

#1662 Pulling refs/heads/main into main
  gdi/get-data-in/connect/gcp/gcp-connect.rst
  gdi/get-data-in/connect/gcp/gcp-prereqs.rst
Labels: sync

#1663 Pulling refs/heads/main into main
  _images/get-started/activate-assistant.png
  _includes/gdi/collector-available-processors.rst
  gdi/opentelemetry/automatic-discovery/discovery-kubernetes.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-backend.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-third-party.rst
  gdi/opentelemetry/components/a-components-processors.rst
  gdi/opentelemetry/components/metrics-generation-processor.rst
  gdi/opentelemetry/discovery-mode.rst
  get-started/o11y-ai-promptlibrary.rst
  get-started/o11y-ai.rst
  index.rst
  metrics-and-metadata/relatedcontent.rst
Labels: sync

#1664 Remove the section for SFx.NET from Chef
  gdi/opentelemetry/collector-windows/deployments-windows-chef.rst
Labels: external, stop-alert

#1656 Update go-otel-metrics.rst
  gdi/get-data-in/application/go/configuration/go-otel-metrics.rst
Labels: external, stop-alert

#1665 Pulling refs/heads/main into main
  _images/ai/ai2.png
  _images/ai/ai3.png
  _images/alerts-detectors-notifications/muting-notifications/mutingrule-modal2.png
  _images/alerts-detectors-notifications/muting-notifications/mutingtab.png
  _images/apm/apm-data-links/appd-data-links-sample-csv.png
  _images/infrastructure/k8s-nav/k8s-predefined-metric-classes.csv
  _images/synthetics/auth-basic-api-steps.png
  _images/synthetics/auth-basic-html-steps.png
  _images/synthetics/auth-multifactor-email-fillinfield.png
  _images/synthetics/auth-multifactor-sms-fillinfield.png
  _images/synthetics/auth-multifactor-sms-six.png
  _images/synthetics/auth-multifactor-sso-sample.png
  alerts-detectors-notifications/alerts-and-detectors/mute-notifications.rst
  apm/apm-data-links/apm-create-data-links.rst
  apm/apm-data-links/apm-datalinks-terraform/apm-create-data-links-terraform-batch.rst
  apm/apm-data-links/apm-datalinks-terraform/apm-create-data-links-terraform-file.rst
  apm/apm-data-links/apm-datalinks-terraform/apm-data-links-terraform.rst
  apm/apm-data-links/apm-datalinks-terraform/apm-delete-data-links-terraform.rst
  apm/apm-data-links/apm-use-data-links.rst
  apm/apm-data-links/data-links-landing.rst
  apm/apm-spans-traces/service-map.rst
  data-visualization/navigate-with-data-links.rst
  data-visualization/use-time-range-selector.rst
  gdi/get-data-in/gdi-guide/infrastructure/send-server-cluster-data.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-backend.rst
  gdi/opentelemetry/collector-kubernetes/k8s-infrastructure-tutorial/k8s-monitor-with-navigators.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-add.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-advanced.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-upgrade.rst
  gdi/opentelemetry/collector-kubernetes/metrics-ootb-k8s.rst
  gdi/opentelemetry/components/kubelet-stats-receiver.rst
  gdi/opentelemetry/components/kubernetes-attributes-processor.rst
  get-started/o11y-ai.rst
  index.rst
  infrastructure/infrastructure.rst
  infrastructure/monitor/aws-infra-import.rst
  infrastructure/monitor/azure.rst
  infrastructure/monitor/gcp-infra-monitor.rst
  infrastructure/monitor/k8s-nav.rst
  infrastructure/monitor/k8s.rst
  infrastructure/monitor/monitor-services-hosts.rst
  infrastructure/monitor/predefined-metric-classes.rst
  infrastructure/navigators-list.rst
  infrastructure/use-navigators.rst
  metrics-and-metadata/link-metadata-to-content.rst
  metrics-and-metadata/relatedcontent.rst
  package-lock.json
  release-notes/2025-2-rn.rst
  release-notes/release-notes-overview.rst
  synthetics/browser-test/set-up-browser-test.rst
  synthetics/browser-test/set-up-transactional-browser-test.rst
  synthetics/test-config/auth.rst
  synthetics/test-config/custom-variables.rst
  synthetics/test-config/private-locations.rst
  synthetics/test-config/test-config.rst
Labels: sync

#1667 Pulling refs/heads/main into main
  gdi/monitors-languages/asp-dot-net.rst
  gdi/monitors-languages/microsoft-dotnet.rst
  gdi/opentelemetry/components/basic-auth-extension.rst
  gdi/opentelemetry/components/bearertokenauth-extension.rst
Labels: sync

#1668 Pulling refs/heads/main into main
  apm/profiling/profiling-memory-metrics.rst
  gdi/get-data-in/application/otel-dotnet/configuration/dotnet-metrics-attributes.rst
  gdi/get-data-in/application/otel-dotnet/dotnet-requirements.rst
  gdi/get-data-in/application/otel-dotnet/get-started.rst
  gdi/monitors-languages/microsoft-dotnet.rst
  gdi/other-ingestion-methods/send-custom-metrics.rst
Labels: sync

#1669 Pulling refs/heads/main into main
  _images/gdi/gdi-discovered-services-tab.jpg
  gdi/opentelemetry/components/purefa-receiver.rst
  gdi/opentelemetry/components/snowflake-receiver.rst
  gdi/opentelemetry/components/vcenter-receiver.rst
  gdi/opentelemetry/discovery-mode.rst
  metrics-and-metadata/data-tools-landing.rst
  metrics-and-metadata/metrics-landing.rst
Labels: sync

#1670 Pulling refs/heads/main into main
  _includes/requirements/nodejs.rst
  infrastructure/metrics-pipeline/use-case-archive.rst
Labels: sync

#1671 Pulling refs/heads/main into main
  gdi/opentelemetry/automatic-discovery/k8s/k8s-backend.rst
  gdi/opentelemetry/collector-kubernetes/k8s-troubleshooting/troubleshoot-k8s-container.rst
Labels: sync

#1672 Pulling refs/heads/main into main
  _includes/requirements/android.rst
  _includes/requirements/ios.rst
  gdi/get-data-in/application/python/configuration/python-otel-metrics.rst
  gdi/get-data-in/application/python/splunk-python-otel-distribution.rst
  gdi/get-data-in/rum/android/configure-rum-android-instrumentation.rst
  gdi/get-data-in/rum/android/install-rum-android.rst
  gdi/get-data-in/rum/android/manual-rum-android-instrumentation.rst
  gdi/get-data-in/rum/ios/configure-rum-ios-instrumentation.rst
  gdi/get-data-in/rum/ios/install-rum-ios.rst
  gdi/get-data-in/rum/ios/rum-ios-data-model.rst
  gdi/get-data-in/rum/react/manual-rum-react-instrumentation.rst
  gdi/opentelemetry/components/sum-connector.rst
  gdi/opentelemetry/deployments/deployments-ecs-ec2.rst
  release-notes/2025-2-rn.rst
Labels: sync

#1673 Pulling refs/heads/main into main
  _includes/requirements/dotnet.rst
  apm/profiling/get-data-in-profiling.rst
  gdi/get-data-in/application/otel-dotnet/configuration/advanced-dotnet-configuration.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/connect-traces-logs.rst
  gdi/get-data-in/application/otel-dotnet/troubleshooting/common-dotnet-troubleshooting.rst
  gdi/get-data-in/serverless/azure/instrument-azure-functions-dotnet.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-third-party.rst
Labels: sync

#1674 Pulling refs/heads/main into main
  gdi/get-data-in/application/otel-dotnet/instrumentation/connect-traces-logs.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/manual-dotnet-instrumentation.rst
Labels: sync

#1675 Pulling refs/heads/main into main
  _includes/logs/query-logs.rst
  gdi/opentelemetry/components/span-metrics-connector.rst
  gdi/opentelemetry/components/sum-connector.rst
Labels: sync

#1678 Pulling refs/heads/main into main
  gdi/get-data-in/application/python/get-started.rst
  gdi/get-data-in/application/python/instrumentation/instrument-python-application.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-advanced-config.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-java-traces-tutorial/deploy-collector-k8s-java.rst
  gdi/opentelemetry/collector-kubernetes/collector-kubernetes-intro.rst
  gdi/opentelemetry/collector-kubernetes/kubernetes-config-add.rst
  gdi/opentelemetry/data-processing.rst
  gdi/opentelemetry/deployments/otel-deployments.rst
  gdi/opentelemetry/install-the-collector.rst
  gdi/opentelemetry/opentelemetry.rst
  get-started/o11y-ai-promptlibrary.rst
  get-started/o11y-ai.rst
  index.rst
Labels: sync

#1679 Pulling refs/heads/main into main
  gdi/opentelemetry/deployment-modes.rst
  gdi/opentelemetry/support-checklist.rst
Labels: sync

#1680 Pulling refs/heads/main into main
  gdi/monitors-hosts/haproxy.rst
Labels: sync

#1681 Pulling refs/heads/main into main
  admin/user-management/teams/enhanced-team-security.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/azure-webapps.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/azure-webjobs.rst
  gdi/opentelemetry/automatic-discovery/k8s/k8s-backend.rst
  gdi/opentelemetry/components/kubernetes-cluster-receiver.rst
Labels: sync

#1683 Pulling refs/heads/main into main
  alerts-detectors-notifications/alerts-and-detectors/alerts-detectors-notifications.rst
  gdi/opentelemetry/components/receiver-creator-receiver.rst
  get-started/overview.rst
  sp-oncall/admin/get-started/admin-getting-started.rst
  sp-oncall/admin/get-started/api.rst
  sp-oncall/admin/get-started/onboarding-milestones.rst
  sp-oncall/admin/get-started/team-dashboard.rst
  sp-oncall/admin/sso/single-sign-sso.rst
  sp-oncall/admin/sso/sp-sso-google.rst
  sp-oncall/admin/sso/sp-sso-other.rst
  sp-oncall/admin/sso/sp-sso-users.rst
  sp-oncall/alerts/alerts-main.rst
  sp-oncall/alerts/multiple-escalation-policies.rst
  sp-oncall/alerts/team-dashboard.rst
  sp-oncall/alerts/team-escalation-policy.rst
  sp-oncall/incidents/incident-pane.rst
  sp-oncall/notifications/call-notification-numbers.rst
  sp-oncall/reports/incident-frequency-report.rst
  sp-oncall/reports/post-incident-review.rst
  sp-oncall/spoc-integrations/alertsite-integration.rst
  sp-oncall/spoc-integrations/bugsnag-integration.rst
  sp-oncall/spoc-integrations/hipchat-integration.rst
  sp-oncall/spoc-integrations/icinga-integration.rst
  sp-oncall/spoc-integrations/integrations-main.rst
  sp-oncall/spoc-integrations/jenkins-integration.rst
  sp-oncall/spoc-integrations/microsoft-azure-oms-integration-guide-victorops.rst
  sp-oncall/spoc-integrations/pingdom-integration.rst
  sp-oncall/spoc-integrations/sensu-integration.rst
  sp-oncall/spoc-integrations/sentry-integration-guide-victorops.rst
  sp-oncall/spoc-integrations/setup-single-sign-on-sso-and-user-provisioning-with-okta-beta.rst
  sp-oncall/spoc-integrations/splunking-victorops-data.rst
Labels: sync

#1684 Pulling refs/heads/main into main
  gdi/integrations-list.rst
  gdi/opentelemetry/otel-other/other-ingestion-collectd.rst
Labels: sync

#1685 Pulling refs/heads/main into main
  gdi/monitors-hosts/vsphere.rst
  infrastructure/monitor/azure.rst
  splunkplatform/centralized-rbac.rst
Labels: sync

#1687 Update centralized-rbac.rst
  splunkplatform/centralized-rbac.rst
Labels: admin, external, stop-alert

#1686 Pulling refs/heads/main into main
  _includes/admin/roles_log_observer.rst
  admin/user-management/roles/roles-and-capabilities-table.rst
  alerts-detectors-notifications/slo/view-slo.rst
  apm/profiling/get-data-in-profiling.rst
  data-visualization/charts/export-and-share-charts.rst
  gdi/get-data-in/application/java/instrumentation/instrument-java-application.rst
  gdi/get-data-in/application/java/migrate-metrics.rst
  gdi/get-data-in/application/java/troubleshooting/common-java-troubleshooting.rst
  gdi/get-data-in/application/python/migration-guide.rst
  gdi/opentelemetry/components/signalfx-receiver.rst
Labels: sync

#1688 Update install-linux-manual.rst
  gdi/opentelemetry/collector-linux/install-linux-manual.rst
Labels: external, stop-alert

#1689 Pulling refs/heads/main into main
  gdi/get-data-in/application/otel-dotnet/sfx/configuration/advanced-dotnet-configuration.rst
  gdi/get-data-in/application/otel-dotnet/sfx/configuration/dotnet-metrics-attributes.rst
  gdi/get-data-in/application/otel-dotnet/sfx/dotnet-requirements.rst
  gdi/get-data-in/application/otel-dotnet/sfx/instrumentation/connect-traces-logs.rst
  gdi/get-data-in/application/otel-dotnet/sfx/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/application/otel-dotnet/sfx/instrumentation/manual-dotnet-instrumentation.rst
  gdi/get-data-in/application/otel-dotnet/sfx/sfx-instrumentation.rst
  gdi/get-data-in/application/otel-dotnet/sfx/troubleshooting/common-dotnet-troubleshooting.rst
  gdi/opentelemetry/deployment-modes.rst
  logs/lo-connect-landing.rst
  logs/severity-key.rst
Labels: sync

#1690 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-ts-metric-streams.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
  infrastructure/monitor/aws-infra-import.rst
  infrastructure/monitor/aws.rst
Labels: sync

#1692 Remove fluentforward
  apm/profiling/get-data-in-profiling.rst
Labels: external, stop-alert

#1691 Pulling refs/heads/main into main
  gdi/get-data-in/application/otel-dotnet/instrumentation/azure-webapps.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/azure-webjobs.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/opentelemetry/collector-addon/collector-addon-intro.rst
  sp-oncall/spoc-integrations/aws-cloudwatch-integration-guide.rst
  synthetics/browser-test/set-up-browser-test.rst
Labels: sync

#1609 Update rum-synth.rst
  synthetics/test-config/rum-synth.rst
Labels: external, stop-alert

#1694 Pulling refs/heads/main into main
  gdi/get-data-in/connect/aws/aws-troubleshooting.rst
  gdi/get-data-in/connect/aws/aws-ts-polling.rst
  gdi/get-data-in/connect/aws/get-awstoc.rst
Labels: sync
