Repository splunk/public-o11y-docs, pull requests merged in 2025-05, with the labels that each got.

#1736 Update telegraf.rst to fix section numbering
  gdi/opentelemetry/otel-other/telegraf.rst
Labels: external, stop-alert

#1739 Fix Send data directly to Splunk Observability Cloud
  gdi/get-data-in/application/go/instrumentation/instrument-go-application.rst
Labels: external

#1744 Pulling refs/heads/main into main
  _includes/requirements/collector-windows.rst
Labels: sync

#1745 Pulling refs/heads/main into main
  _includes/gdi/available-aws.rst
  gdi/get-data-in/connect/aws/aws-prereqs.rst
Labels: sync

#1746 Pulling refs/heads/main into main
  gdi/get-data-in/application/java/instrumentation/connect-traces-logs.rst
Labels: sync
