Repository splunk/public-o11y-docs, pull requests merged in 2025-08, with the labels that each got.

#1747 Pulling refs/heads/main into main
  _images/gdi/AWS_PL_region1.jpg
  _images/gdi/AWS_PL_region1.png
  _images/gdi/AWS_PL_region2.png
  _images/gdi/AWS_PL_region3.png
  _images/logs/CreateUser.png
  _includes/gdi/otel-receivers-table.rst
  _includes/requirements/ios.rst
  gdi/get-data-in/application/go/configuration/advanced-go-otel-configuration.rst
  gdi/get-data-in/application/go/instrumentation/instrument-go-application.rst
  gdi/get-data-in/application/otel-dotnet/instrumentation/instrument-dotnet-application.rst
  gdi/get-data-in/rum/android/add-mapping-file.rst
  gdi/get-data-in/rum/android/get-android-data-in.rst
  gdi/get-data-in/rum/android/rum-android-data-model.rst
  gdi/get-data-in/rum/browser/get-browser-data-in.rst
  gdi/get-data-in/rum/browser/rum-browser-data-model.rst
  gdi/get-data-in/rum/browser/set-up-javascript-source-mapping.rst
  gdi/get-data-in/rum/ios/add-dsyms.rst
  gdi/get-data-in/rum/ios/get-ios-data-in.rst
  gdi/get-data-in/rum/ios/install-rum-ios.rst
  gdi/get-data-in/rum/ios/rum-ios-data-model.rst
  gdi/get-data-in/rum/rum-instrumentation.rst
  gdi/opentelemetry/components/a-components-receivers.rst
  gdi/opentelemetry/components/activedirectory-ds-receiver.rst
  gdi/private-connectivity/aws-privatelink.rst
  rum/error-aggregates.rst
  synthetics/browser-test/browser-test-results.rst
Labels: sync

#1731 Update rules-engine-matching-conditions.rst
  sp-oncall/alerts/rules-engine/rules-engine-matching-conditions.rst
Labels: external, stop-alert, heretto

#1730 Update synthetics-usage.rst
  admin/subscription-usage/synthetics-usage.rst
Labels: external, stop-alert, heretto

#1700 Update unified-identity.rst
  splunkplatform/unified-id/unified-identity.rst
Labels: external, stop-alert
